export default {
  'Advanced Tense Nuances': {
    q: [
      ['I ___ you were coming! Why didn’t you say?', ['didn’t know', 'haven’t known', 'don’t know', 'hadn’t known'], 0, 'Past simple for a past state now changed.'],
      ['"I was hoping you could help" is:', ['a past event', 'a polite tentative request', 'a complaint', 'a future plan'], 1, 'Past continuous for politeness.'],
      ['"I’ll be seeing him tomorrow" suggests:', ['a firm plan', 'something that will happen as a matter of course', 'a surprise', 'a wish'], 1, 'Future continuous: natural course.'],
      ['"You’re always losing your keys" expresses:', ['a fact', 'irritation at a habit', 'a plan', 'sympathy'], 1, 'Complaint.'],
      ['"She’s forever complaining" uses:', ['present perfect', 'present continuous with an adverb for habits', 'past simple', 'future'], 1, 'Habitual complaint.'],
      ['"I’ve been meaning to call you" means:', ['I called', 'I’ve intended to for a while', 'I will call', 'I never call'], 1, 'Long-standing intention.'],
      ['"This time tomorrow, I’ll have finished" uses:', ['future continuous', 'future perfect', 'present perfect', 'past perfect'], 1, 'Future perfect.'],
      ['"I did think about it" is:', ['a question', 'emphatic past', 'a negative', 'a passive'], 1, 'Emphatic did.'],
    ],
    s: [
      ['I was wondering whether you might be free on Friday.', true, null, 'Polite tentative.'],
      ['He is always forgets his password.', false, 'He is always forgetting his password.', '-ing after is always.'],
      ['We will be seeing the client on Monday as usual.', true, null, 'Correct.'],
      ['I have been meaning to ask you something.', true, null, 'Correct.'],
      ['I didn’t realise you have already left.', false, 'I didn’t realise you had already left.', 'Past perfect.'],
      ['By the time you read this, I’ll be on a plane.', true, null, 'Correct.'],
    ],
  },
  'Aspect & Meaning: Progressive vs Simple': {
    q: [
      ['"He works in Bogotá" vs "He’s working in Bogotá": the second implies:', ['permanence', 'temporariness', 'the past', 'future'], 1, 'Temporary.'],
      ['"I read a book last night" means:', ['I finished it', 'I didn’t finish', 'I hated it', 'I started'], 0, 'Simple = completed.'],
      ['"I was reading a book last night" means:', ['I finished it', 'I was in the middle of it', 'I never started', 'I lost it'], 1, 'Progressive = in progress.'],
      ['"She lived in Rome for a year" – the stay is:', ['ongoing', 'finished', 'temporary now', 'planned'], 1, 'Finished.'],
      ['"She has lived in Rome for a year" – the stay is:', ['ongoing', 'finished', 'unknown', 'future'], 0, 'Ongoing.'],
      ['"The bus stops here" refers to:', ['now', 'a regular fact', 'yesterday', 'tomorrow only'], 1, 'Regular.'],
      ['"The bus is stopping" refers to:', ['a regular fact', 'this moment', 'yesterday', 'a schedule'], 1, 'Now.'],
      ['"I’m loving it" is an example of:', ['a formal rule', 'marketing/informal emphasis', 'a mistake always', 'passive'], 1, 'Informal emphasis.'],
    ],
    s: [
      ['I’m living with my parents until I find a flat.', true, null, 'Temporary.'],
      ['The sun is rising in the east every day.', false, 'The sun rises in the east every day.', 'Fact: simple.'],
      ['She was painting the kitchen all weekend.', true, null, 'Duration/in progress.'],
      ['I painted the kitchen; it looks great now.', true, null, 'Completed.'],
      ['Water is freezing at 0 degrees.', false, 'Water freezes at 0 degrees.', 'Fact.'],
      ['He was dying for years until 2001.', false, 'He was ill for years until he died in 2001.', 'Odd use of progressive.'],
    ],
  },
  'Advanced Conditionals & Hypotheticals': {
    q: [
      ['Were I ___ the offer, I’d move to Berlin.', ['accept', 'to accept', 'accepting', 'accepted'], 1, 'Were I to + verb (formal).'],
      ['Had I known, I ___ come.', ['would', 'would have', 'had', 'will'], 1, 'Had I known = If I had known.'],
      ['___ it not for your help, we’d have lost.', ['Were', 'Was', 'Had', 'If'], 0, 'Were it not for.'],
      ['Should you ___ any questions, contact us.', ['have', 'had', 'to have', 'having'], 0, 'Should you have.'],
      ['"If you should see him" is:', ['very likely', 'less likely / formal', 'impossible', 'past'], 1, 'Tentative.'],
      ['If he ___ to fail, we have a plan B.', ['were', 'was', 'is', 'would'], 0, 'If he were to fail.'],
      ['"It’s high time we ___."', ['leave', 'left', 'will leave', 'had left'], 1, 'high time + past.'],
      ['"I’d rather you ___ smoke here."', ['don’t', 'didn’t', 'won’t', 'not'], 1, 'would rather + past.'],
    ],
    s: [
      ['Had we left earlier, we would have caught the train.', true, null, 'Correct.'],
      ['Were I you, I would accept.', true, null, 'Correct (formal).'],
      ['Should you require assistance, please call reception.', true, null, 'Correct.'],
      ['Had I have known, I would have said something.', false, 'Had I known, I would have said something.', 'No extra have.'],
      ['It’s time we go home.', false, 'It’s time we went home.', 'Past after it’s time.'],
      ['I’d rather you don’t tell anyone.', false, 'I’d rather you didn’t tell anyone.', 'Past after would rather + subject.'],
    ],
  },
  'Modality: Nuances & Register': {
    q: [
      ['Most formal way to ask permission:', ['Can I…?', 'Could I…?', 'Might I…?', 'Lemme…'], 2, 'Might I (very formal).'],
      ['"You shall receive a reply within 5 days" (contract) means:', ['maybe', 'you will (obligation on us)', 'you should', 'never'], 1, 'Legal shall.'],
      ['"Dare" as a modal: "How ___ you!"', ['dare', 'dares', 'do dare', 'dared'], 0, 'How dare you.'],
      ['"Need" as a modal: "You ___ worry."', ['needn’t', 'don’t need', 'needn’t to', 'need not to'], 0, 'needn’t + base.'],
      ['"Ought to" is closest to:', ['must', 'should', 'can', 'may'], 1, 'should.'],
      ['"Would" for past habits: "Every summer we ___ visit our grandparents."', ['would', 'will', 'used', 'should'], 0, 'would.'],
      ['"That would be great" – would expresses:', ['past', 'polite/tentative', 'obligation', 'ability'], 1, 'Politeness.'],
      ['"Be to": "You are to report at 9" means:', ['maybe', 'official instruction', 'suggestion', 'past'], 1, 'Formal instruction.'],
    ],
    s: [
      ['You ought to check with legal first.', true, null, 'Correct.'],
      ['He needn’t have bought so much food.', true, null, 'Unnecessary action done.'],
      ['You ought not to have said that.', true, null, 'Correct.'],
      ['Might I to suggest an alternative?', false, 'Might I suggest an alternative?', 'No "to".'],
      ['Every Sunday, my father would to cook pancakes.', false, 'Every Sunday, my father would cook pancakes.', 'would + base.'],
      ['Visitors are to sign in at reception.', true, null, 'Correct.'],
    ],
  },
  'Discourse Grammar: Cohesion & Reference': {
    q: [
      ['"The CEO resigned. ___ shocked the market."', ['This', 'These', 'They', 'Those'], 0, 'This = the previous event.'],
      ['"We tried plan A; ___ failed." (plan A)', ['the latter', 'the former', 'it', 'Both it and the former'], 2, 'it.'],
      ['"Cats and dogs are popular; ___ are more independent." (cats)', ['the former', 'the latter', 'they', 'these'], 0, 'the former = cats.'],
      ['"Such" in "such measures" refers to:', ['new measures', 'measures mentioned before', 'no measures', 'future measures'], 1, 'Previously mentioned.'],
      ['"The above" in a document refers to:', ['earlier text', 'later text', 'the title', 'the sky'], 0, 'Earlier text.'],
      ['"As mentioned ___, the deadline is Friday."', ['above', 'below', 'here', 'there'], 0, 'as mentioned above.'],
      ['"Respectively" means:', ['with respect', 'in the same order as listed', 'later', 'in general'], 1, 'In that order.'],
      ['"The aforementioned" is:', ['informal', 'formal/legal for "mentioned before"', 'a name', 'a verb'], 1, 'Formal reference.'],
    ],
    s: [
      ['Sales rose in Q1 and fell in Q2, respectively by 5% and 3%.', true, null, 'Correct.'],
      ['Of tea and coffee, I prefer the latter.', true, null, 'latter = coffee.'],
      ['The manager said this, which he mentioned it before.', false, 'The manager repeated what he had mentioned before.', 'Redundant reference.'],
      ['Please see the figures below.', true, null, 'Correct.'],
      ['The former option is cheaper; the later is faster.', false, 'The former option is cheaper; the latter is faster.', 'latter (not later).'],
      ['Such an approach has proven effective.', true, null, 'Correct.'],
    ],
  },
  'Complex Noun Phrases': {
    q: [
      ['"a state-of-the-art customer relationship management system" – the head noun is:', ['state', 'customer', 'management', 'system'], 3, 'system.'],
      ['Which is a noun phrase with a reduced clause?', ['the man sleeping on the sofa', 'the man sleeps', 'sleep man', 'man is sleeping'], 0, 'Reduced relative.'],
      ['"The decision to expand" – "to expand" is:', ['a verb phrase', 'a post-modifier', 'a subject', 'an adverb'], 1, 'Post-modifying infinitive.'],
      ['Which order is correct?', ['annual company report', 'company annual report', 'report annual company', 'Both A and B are used'], 3, 'Both attested; A more common.'],
      ['"Something ___ about" (post-modification):', ['worth talking', 'worthing talk', 'worth to talk', 'to worth talking'], 0, 'worth + -ing.'],
      ['"The people involved" – "involved" is:', ['a verb', 'a reduced passive relative clause', 'a noun', 'an adverb'], 1, 'Reduced relative.'],
      ['Head noun of "several highly experienced senior software engineers from India":', ['several', 'software', 'engineers', 'India'], 2, 'engineers.'],
      ['"A five-year-old child" vs "The child is five years old": in the first, "year" is:', ['plural', 'singular (compound adjective)', 'a verb', 'omitted'], 1, 'Singular in compounds.'],
    ],
    s: [
      ['The results presented in the report are preliminary.', true, null, 'Reduced relative.'],
      ['The proposal discussing at the meeting was rejected.', false, 'The proposal discussed at the meeting was rejected.', 'Passive participle.'],
      ['There are a number of issues to be resolved.', true, null, 'Correct.'],
      ['She gave a 20-minutes presentation.', false, 'She gave a 20-minute presentation.', 'Singular.'],
      ['Anyone wishing to attend should register.', true, null, 'Correct.'],
      ['The person responsible of the error apologised.', false, 'The person responsible for the error apologised.', 'responsible for.'],
    ],
  },
  'Advanced Passive & Impersonal Style': {
    q: [
      ['Impersonal: "___ has been decided to close the branch."', ['It', 'There', 'This', 'That'], 0, 'It has been decided.'],
      ['"There is said to be a problem" – this is:', ['active', 'impersonal passive with there', 'imperative', 'future'], 1, 'There + passive.'],
      ['"Mistakes were made" avoids:', ['a verb', 'naming the agent', 'the past', 'the object'], 1, 'Agentless passive.'],
      ['Formal: "___ should be noted that…"', ['It', 'There', 'You', 'They'], 0, 'It should be noted.'],
      ['"Applications ___ by Friday."', ['must be submitted', 'must submit', 'must to be submitted', 'must submitted'], 0, 'Modal passive.'],
      ['"One" as impersonal pronoun: "___ should never assume."', ['One', 'You', 'They', 'Someone'], 0, 'Formal one.'],
      ['"The issue is being looked into" – the phrasal verb keeps:', ['its preposition', 'nothing', 'the object', 'an agent'], 0, 'look into → looked into.'],
      ['"It is to be hoped that…" is:', ['informal', 'very formal', 'a question', 'wrong'], 1, 'Very formal.'],
    ],
    s: [
      ['It is generally agreed that the policy failed.', true, null, 'Correct.'],
      ['The matter is been dealt with.', false, 'The matter is being dealt with.', 'being.'],
      ['There are thought to be over 100 species here.', true, null, 'Correct.'],
      ['It is to be expected that costs rise.', true, null, 'Correct.'],
      ['One should always double-check their figures.', true, null, 'Accepted in modern usage.'],
      ['The report was written by and sent to the board.', true, null, 'Correct.'],
    ],
  },
  'Advanced Linking & Cohesive Devices': {
    q: [
      ['"___, the results were disappointing." (concession)', ['Notwithstanding', 'Hence', 'Thus', 'Moreover'], 0, 'Notwithstanding = despite that.'],
      ['"Hence" means:', ['however', 'therefore', 'although', 'meanwhile'], 1, 'Therefore.'],
      ['"Albeit" means:', ['although', 'because', 'so', 'while'], 0, 'Although (formal).'],
      ['"___, we should consider the costs." (addition)', ['Furthermore', 'Nevertheless', 'Conversely', 'Otherwise'], 0, 'Furthermore.'],
      ['"Conversely" introduces:', ['an example', 'an opposite view', 'a result', 'a summary'], 1, 'Opposite.'],
      ['"Thereby" means:', ['by that means', 'there', 'thus far', 'then'], 0, 'By that means.'],
      ['"Whereby" means:', ['where', 'by which', 'why', 'when'], 1, 'by which.'],
      ['"In light of" means:', ['brightly', 'considering', 'despite', 'instead of'], 1, 'Considering.'],
    ],
    s: [
      ['The project was completed, albeit later than planned.', true, null, 'Correct.'],
      ['Sales fell; hence, we reduced staff.', true, null, 'Correct.'],
      ['Notwithstanding of the risks, we proceeded.', false, 'Notwithstanding the risks, we proceeded.', 'No "of".'],
      ['We introduced a system whereby staff can work remotely.', true, null, 'Correct.'],
      ['Moreover the costs, the timeline is a concern.', false, 'In addition to the costs, the timeline is a concern.', 'Moreover is not a preposition.'],
      ['In light of recent events, the trip is cancelled.', true, null, 'Correct.'],
    ],
  },
  'Metaphor & Figurative Language': {
    q: [
      ['"Time is money" is a:', ['simile', 'metaphor', 'fact', 'command'], 1, 'Metaphor.'],
      ['"As busy as a bee" is a:', ['metaphor', 'simile', 'idiom only', 'proverb'], 1, 'Simile (as…as).'],
      ['"The market is in free fall" means:', ['it is flying', 'prices are dropping fast', 'it is free', 'it is stable'], 1, 'Rapid drop.'],
      ['"A flood of complaints" means:', ['water damage', 'many complaints', 'a few complaints', 'no complaints'], 1, 'Many.'],
      ['"He has a heart of stone" means:', ['a medical condition', 'he is unfeeling', 'he is strong', 'he is old'], 1, 'Unfeeling.'],
      ['"The company is bleeding money" means:', ['losing money quickly', 'earning', 'injured', 'saving'], 0, 'Losing fast.'],
      ['"Bright idea" uses light as a metaphor for:', ['heat', 'intelligence', 'danger', 'money'], 1, 'Intelligence.'],
      ['"Hyperbole" is:', ['understatement', 'exaggeration', 'a question', 'a fact'], 1, 'Exaggeration.'],
    ],
    s: [
      ['We hit a wall with the negotiations.', true, null, 'Metaphor: obstacle.'],
      ['Her speech was as clear as a bell.', true, null, 'Simile.'],
      ['The new CEO is a breath of fresh air.', true, null, 'Metaphor.'],
      ['This deadline is killing me softly like a cat.', false, 'This deadline is killing me.', 'Mixed/confused metaphor.'],
      ['Our profits skyrocketed.', true, null, 'Metaphor.'],
      ['He is like a fish in the water with numbers.', false, 'He takes to numbers like a duck to water.', 'Correct idiom form.'],
    ],
  },
  'Irony, Understatement & Humour': {
    q: [
      ['British understatement: a disaster is "___".', ['a bit of a problem', 'catastrophic', 'the end', 'hopeless'], 0, 'a bit of a problem.'],
      ['"Not bad" (British) often means:', ['bad', 'quite good', 'terrible', 'nothing'], 1, 'Quite good.'],
      ['Irony is:', ['saying the opposite of what you mean for effect', 'a lie', 'a joke about iron', 'a metaphor'], 0, 'Opposite meaning.'],
      ['"Oh great, another meeting" (sighing) is:', ['sincere', 'sarcastic', 'a question', 'formal'], 1, 'Sarcasm.'],
      ['A "dry" sense of humour is:', ['boring', 'subtle and deadpan', 'loud', 'rude'], 1, 'Deadpan.'],
      ['"With respect" before disagreeing can be:', ['always sincere', 'a polite signal of strong disagreement', 'an insult', 'a compliment'], 1, 'Softened disagreement.'],
      ['"I might have a slight issue" (car on fire) is:', ['literal', 'understatement', 'hyperbole', 'a metaphor'], 1, 'Understatement.'],
      ['"Tongue-in-cheek" means:', ['serious', 'jokingly, not sincerely', 'angry', 'medical'], 1, 'Joking.'],
    ],
    s: [
      ['"Lovely weather!" said during a storm is ironic.', true, null, 'Irony.'],
      ['"Quite good" in British English can be a modest compliment.', true, null, 'Correct.'],
      ['Sarcasm is always appropriate in formal business emails.', false, 'Sarcasm is risky in formal business emails.', 'Avoid in writing.'],
      ['"It could be worse" is a typical understatement.', true, null, 'Correct.'],
      ['A pun is a joke based on words with similar sounds or meanings.', true, null, 'Correct.'],
      ['"I’m not entirely convinced" usually means "I strongly agree".', false, '"I’m not entirely convinced" usually means "I disagree".', 'Understatement.'],
    ],
  },
  'Academic & Report Writing Style': {
    q: [
      ['Academic style avoids:', ['contractions', 'evidence', 'references', 'paragraphs'], 0, 'No contractions.'],
      ['"A lot of" → academic:', ['tons of', 'a considerable number of', 'loads of', 'heaps of'], 1, 'Formal quantifier.'],
      ['"Get" → academic:', ['obtain', 'grab', 'take', 'catch'], 0, 'obtain.'],
      ['Which is a hedged claim?', ['This proves…', 'This suggests…', 'This is…', 'Everyone knows…'], 1, 'Hedging.'],
      ['"Show" → academic:', ['demonstrate', 'tell', 'give', 'point'], 0, 'demonstrate.'],
      ['Which is more academic?', ['Kids', 'Children', 'Youngsters', 'Little ones'], 1, 'Children.'],
      ['"Etc." in academic writing is:', ['recommended', 'usually avoided', 'required', 'formal'], 1, 'Avoid vagueness.'],
      ['"The data ___ that…" (formal)', ['says', 'indicate', 'tells', 'talks'], 1, 'indicate.'],
    ],
    s: [
      ['The findings indicate a significant correlation.', true, null, 'Correct.'],
      ['The results don’t show any big changes.', false, 'The results do not show any significant changes.', 'No contractions; formal vocab.'],
      ['It could be argued that the policy was premature.', true, null, 'Hedging.'],
      ['Lots of people think this is a good idea.', false, 'Many stakeholders consider this a viable option.', 'Formal register.'],
      ['Further research is required to confirm these results.', true, null, 'Correct.'],
      ['In conclusion, the evidence supports the hypothesis.', true, null, 'Correct.'],
    ],
  },
  'Critical Reading: Fact vs Opinion': {
    q: [
      ['Which is a fact?', ['Coffee is the best drink.', 'Coffee contains caffeine.', 'Everyone should drink coffee.', 'Coffee is delicious.'], 1, 'Verifiable.'],
      ['Which word signals opinion?', ['measured', 'arguably', 'recorded', 'counted'], 1, 'arguably.'],
      ['"Studies show" without a reference is:', ['strong evidence', 'a vague appeal to authority', 'proof', 'a fact'], 1, 'Vague.'],
      ['Bias means:', ['balance', 'unfair preference', 'neutrality', 'evidence'], 1, 'Unfair preference.'],
      ['"Clearly, the plan is wrong" – "clearly" is:', ['evidence', 'a persuasive device', 'a fact', 'neutral'], 1, 'Persuasive.'],
      ['An "inference" is:', ['a direct quote', 'a conclusion from evidence', 'a fact', 'a lie'], 1, 'Reasoned conclusion.'],
      ['Which is the most reliable source?', ['an anonymous blog', 'a peer-reviewed journal', 'a meme', 'a rumour'], 1, 'Peer-reviewed.'],
      ['"Allegedly" indicates:', ['proof', 'an unproven claim', 'certainty', 'a fact'], 1, 'Unproven.'],
    ],
    s: [
      ['"Sales rose 5% in Q2" is a fact.', true, null, 'Verifiable.'],
      ['"This is the best product ever" is a fact.', false, '"This is the best product ever" is an opinion.', 'Opinion.'],
      ['Words like "obviously" can signal persuasion rather than evidence.', true, null, 'Correct.'],
      ['A statistic is always true.', false, 'A statistic can be misleading depending on its source and context.', 'Critical reading.'],
      ['Checking the author and date helps evaluate a source.', true, null, 'Correct.'],
      ['"Experts agree" is proof without naming the experts.', false, '"Experts agree" is not proof without naming the experts.', 'Vague authority.'],
    ],
  },
  'Negotiation & Persuasion: Advanced': {
    q: [
      ['"Let’s explore some ___." (options)', ['alternatives', 'alternates', 'alternatively', 'alters'], 0, 'alternatives.'],
      ['"What would it ___ for you to agree?"', ['take', 'make', 'do', 'get'], 0, 'What would it take.'],
      ['"We’re not ___ far apart."', ['that', 'so much', 'such', 'as'], 0, 'not that far apart.'],
      ['BATNA stands for Best Alternative To a ___ Agreement.', ['Negotiated', 'Nice', 'New', 'National'], 0, 'Negotiated.'],
      ['"I hear what you’re saying, ___…"', ['but', 'so', 'because', 'unless'], 0, 'Acknowledge then counter.'],
      ['"Sweeten the deal" means:', ['add sugar', 'make the offer more attractive', 'cancel', 'delay'], 1, 'Improve offer.'],
      ['"Walk away" in negotiation means:', ['leave the room', 'end the negotiation', 'take a break', 'agree'], 1, 'End it.'],
      ['"Win-win" vs "zero-sum": zero-sum means:', ['everyone wins', 'one wins, one loses', 'nobody plays', 'zero cost'], 1, 'One side’s gain is the other’s loss.'],
    ],
    s: [
      ['If you can move on price, we can move on volume.', true, null, 'Trade-off.'],
      ['I’m afraid that falls outside our budget.', true, null, 'Polite refusal.'],
      ['Let me be frankly with you.', false, 'Let me be frank with you.', 'Adjective.'],
      ['We are prepared to compromise on delivery dates.', true, null, 'Correct.'],
      ['That is our bottom line; we can’t go lower.', true, null, 'Correct.'],
      ['Take it or leave it, we don’t care.', false, 'This is our final offer; we hope it works for you.', 'Too aggressive.'],
    ],
  },
  'Leadership & Management Vocabulary': {
    q: [
      ['To "delegate" means:', ['do everything yourself', 'give tasks to others', 'delay', 'cancel'], 1, 'Assign tasks.'],
      ['"KPI" stands for:', ['Key Performance Indicator', 'Kind Person Inside', 'Keep Pushing Ideas', 'Key Product Item'], 0, 'KPI.'],
      ['A "stakeholder" is:', ['a meat seller', 'someone with an interest in a project', 'a shareholder only', 'a boss'], 1, 'Interested party.'],
      ['"Micromanage" has a ___ connotation.', ['positive', 'negative', 'neutral', 'funny'], 1, 'Negative.'],
      ['"Onboarding" is:', ['leaving a company', 'integrating new employees', 'boarding a plane', 'firing'], 1, 'New hire integration.'],
      ['"Bottleneck" means:', ['a bottle', 'a point that slows the process', 'a neck injury', 'a meeting'], 1, 'Slow point.'],
      ['"Synergy" means:', ['conflict', 'combined effect greater than the sum', 'energy', 'salary'], 1, 'Combined effect.'],
      ['To "streamline" means:', ['complicate', 'make more efficient', 'stop', 'fund'], 1, 'Simplify.'],
    ],
    s: [
      ['We need to align our goals with the company strategy.', true, null, 'Correct.'],
      ['The manager gave us constructive feedback.', true, null, 'Correct.'],
      ['Let’s do a brainstorm to generate ideas.', false, 'Let’s brainstorm to generate ideas.', 'brainstorm is a verb.'],
      ['Our team has a lot of bandwidth this week.', true, null, 'bandwidth = capacity.'],
      ['She is very good in leading teams.', false, 'She is very good at leading teams.', 'good at.'],
      ['We should empower employees to make decisions.', true, null, 'Correct.'],
    ],
  },
  'Legal & Contract English': {
    q: [
      ['"Hereinafter" means:', ['before this', 'from now on in this document', 'never', 'yesterday'], 1, 'Later in this document.'],
      ['"The party of the first part" refers to:', ['a celebration', 'one of the contracting parties', 'a section', 'a lawyer'], 1, 'Contracting party.'],
      ['"Null and void" means:', ['valid', 'having no legal force', 'signed', 'pending'], 1, 'Invalid.'],
      ['"Breach of contract" means:', ['signing', 'breaking the agreement', 'reading', 'renewing'], 1, 'Violation.'],
      ['"Terms and conditions" are:', ['dates', 'rules of the agreement', 'prices only', 'signatures'], 1, 'Rules.'],
      ['"Indemnify" means:', ['to compensate for loss', 'to identify', 'to sign', 'to cancel'], 0, 'Compensate.'],
      ['"Pursuant to" means:', ['against', 'in accordance with', 'before', 'without'], 1, 'In accordance with.'],
      ['"Liability" means:', ['freedom', 'legal responsibility', 'a lie', 'ability'], 1, 'Responsibility.'],
    ],
    s: [
      ['This agreement shall be governed by the laws of Colombia.', true, null, 'Correct.'],
      ['Either party may terminate this contract with 30 days’ notice.', true, null, 'Correct.'],
      ['The contract is valid until it will expire.', false, 'The contract is valid until it expires.', 'No will after until.'],
      ['The tenant shall pay the rent on the first day of each month.', true, null, 'Correct.'],
      ['In case of dispute, both parties agree to arbitrate.', true, null, 'Correct.'],
      ['The supplier is responsible of any delays.', false, 'The supplier is responsible for any delays.', 'responsible for.'],
    ],
  },
  'Finance & Economics Vocabulary': {
    q: [
      ['"Revenue" is:', ['profit', 'total income before costs', 'tax', 'debt'], 1, 'Total income.'],
      ['"Inflation" means:', ['prices falling', 'prices rising generally', 'more jobs', 'a balloon'], 1, 'Rising prices.'],
      ['"Cash flow" refers to:', ['money coming in and going out', 'a river', 'salary', 'coins'], 0, 'Money movement.'],
      ['"Assets" are:', ['debts', 'things of value a company owns', 'employees', 'taxes'], 1, 'Owned value.'],
      ['"Liabilities" are:', ['profits', 'debts and obligations', 'buildings', 'sales'], 1, 'Debts.'],
      ['"Break even" means:', ['lose money', 'costs equal revenue', 'make a profit', 'go bankrupt'], 1, 'No profit, no loss.'],
      ['"Overheads" are:', ['fixed running costs', 'hats', 'profits', 'shares'], 0, 'Fixed costs.'],
      ['"Return on investment" measures:', ['travel', 'profit relative to cost', 'staff', 'time'], 1, 'ROI.'],
    ],
    s: [
      ['Our gross margin improved to 40%.', true, null, 'Correct.'],
      ['The company went bankrupt after years of losses.', true, null, 'Correct.'],
      ['We need to reduce our expenditures on marketing.', true, null, 'Correct.'],
      ['Interest rates were raised up by the central bank.', false, 'Interest rates were raised by the central bank.', 'No "up".'],
      ['Shareholders receive dividends.', true, null, 'Correct.'],
      ['The economy is in a recession since two years.', false, 'The economy has been in a recession for two years.', 'Present perfect + for.'],
    ],
  },
  'Technology & Innovation Vocabulary': {
    q: [
      ['"Cutting-edge" means:', ['dangerous', 'very advanced', 'old', 'sharp'], 1, 'Advanced.'],
      ['"To scale" a business means:', ['weigh it', 'grow it efficiently', 'close it', 'clean it'], 1, 'Grow.'],
      ['"Disruptive technology":', ['breaks things', 'radically changes an industry', 'is annoying', 'is illegal'], 1, 'Radical change.'],
      ['"A bug" in software is:', ['an insect', 'an error', 'a feature', 'a virus only'], 1, 'Error.'],
      ['"User-friendly" means:', ['polite', 'easy to use', 'social', 'cheap'], 1, 'Easy.'],
      ['"To roll out" a product means:', ['to cancel', 'to launch gradually', 'to test', 'to roll it'], 1, 'Launch.'],
      ['"Obsolete" means:', ['new', 'no longer used', 'expensive', 'popular'], 1, 'Outdated.'],
      ['"Machine learning" is a branch of:', ['mechanics', 'artificial intelligence', 'biology', 'law'], 1, 'AI.'],
    ],
    s: [
      ['The app crashed twice during the demo.', true, null, 'Correct.'],
      ['We are migrating our data to the cloud.', true, null, 'Correct.'],
      ['The software need an update.', false, 'The software needs an update.', 'Uncountable + singular verb.'],
      ['Our platform is fully automated.', true, null, 'Correct.'],
      ['Please download the informations from the server.', false, 'Please download the information from the server.', 'Uncountable.'],
      ['The startup secured seed funding last month.', true, null, 'Correct.'],
    ],
  },
  'Diplomacy & Conflict Resolution': {
    q: [
      ['Softening bad news: "___, we won’t be able to meet the deadline."', ['Unfortunately', 'Obviously', 'Whatever', 'Anyway'], 0, 'Unfortunately.'],
      ['"Let’s find some ___ ground."', ['common', 'middle', 'same', 'Both A and B'], 3, 'common/middle ground.'],
      ['"I understand your frustration" is:', ['dismissive', 'empathetic', 'aggressive', 'irrelevant'], 1, 'Empathy.'],
      ['"Perhaps we could revisit this later" is a way to:', ['refuse', 'postpone diplomatically', 'agree', 'insult'], 1, 'Postpone.'],
      ['"To de-escalate" means:', ['make worse', 'reduce tension', 'ignore', 'leave'], 1, 'Reduce tension.'],
      ['Which is the most diplomatic?', ['That’s a stupid idea.', 'I’m not sure that would work in practice.', 'No way.', 'Forget it.'], 1, 'Diplomatic.'],
      ['"Let’s take a step back" means:', ['leave', 'pause and reconsider', 'move backwards', 'quit'], 1, 'Reconsider.'],
      ['"To mediate" means:', ['to meditate', 'to help two sides reach agreement', 'to argue', 'to decide alone'], 1, 'Facilitate agreement.'],
    ],
    s: [
      ['I appreciate your perspective, and I’d like to share mine.', true, null, 'Correct.'],
      ['You always do this wrong!', false, 'I’ve noticed this has happened a few times; can we look at why?', 'Avoid accusations.'],
      ['Let’s focus on the solution rather than the blame.', true, null, 'Correct.'],
      ['Correct me if I’m wrong, but I think we agreed on Friday.', true, null, 'Correct.'],
      ['It’s not my problem, deal with it.', false, 'Let’s see how we can resolve this together.', 'Collaborative tone.'],
      ['I can see where you’re coming from.', true, null, 'Correct.'],
    ],
  },
  'Storytelling & Anecdotes': {
    q: [
      ['Opening an anecdote:', ['In conclusion…', 'You’ll never believe what happened to me…', 'Firstly…', 'To sum up…'], 1, 'Hook.'],
      ['"Out of the blue" means:', ['from the sky', 'unexpectedly', 'sadly', 'slowly'], 1, 'Unexpectedly.'],
      ['"To cut a long story short" means:', ['I’ll summarise', 'the story is short', 'stop talking', 'I forgot'], 0, 'Summarise.'],
      ['Historic present ("So he walks in and says…") is used to:', ['confuse', 'make a story vivid', 'be formal', 'show the future'], 1, 'Vividness.'],
      ['"In the end" vs "at the end": "in the end" means:', ['at the final position', 'finally, after everything', 'at the edge', 'in the finale'], 1, 'Finally.'],
      ['"Believe it or not" introduces:', ['a surprising fact', 'a lie', 'a question', 'a summary'], 0, 'Surprise.'],
      ['"Anyway, where was I?" is used to:', ['ask directions', 'return to the story', 'end', 'start'], 1, 'Return after digression.'],
      ['"The moral of the story is…" introduces:', ['the ending', 'the lesson', 'the characters', 'the setting'], 1, 'Lesson.'],
    ],
    s: [
      ['So there I was, standing in the rain with no umbrella.', true, null, 'Correct.'],
      ['At the end, everything worked out fine.', false, 'In the end, everything worked out fine.', 'In the end.'],
      ['Long story short, we missed the flight.', true, null, 'Correct.'],
      ['It turned out that he was the new CEO!', true, null, 'Correct.'],
      ['Suddenly, the lights go off and everyone screamed.', false, 'Suddenly, the lights went off and everyone screamed.', 'Consistent tense.'],
      ['And that’s how I ended up in Cali.', true, null, 'Correct.'],
    ],
  },
  'Public Speaking & Rhetoric': {
    q: [
      ['A rhetorical question:', ['expects an answer', 'is asked for effect', 'is rude', 'is a fact'], 1, 'For effect.'],
      ['"Rule of three" means:', ['three speakers', 'grouping ideas in threes for impact', 'three minutes', 'three slides'], 1, 'Grouping in threes.'],
      ['"Ladies and gentlemen" is a:', ['closing', 'formal opening', 'question', 'joke'], 1, 'Opening.'],
      ['Repetition of a word at the start of clauses is:', ['anaphora', 'a mistake', 'hyperbole', 'a metaphor'], 0, 'Anaphora.'],
      ['"Imagine a world where…" is a:', ['statistic', 'hook', 'summary', 'fact'], 1, 'Hook.'],
      ['Signposting means:', ['pointing', 'telling the audience where the talk is going', 'street signs', 'reading'], 1, 'Structure cues.'],
      ['"To wrap up" means:', ['to package', 'to conclude', 'to start', 'to wait'], 1, 'Conclude.'],
      ['A "call to action" is:', ['a phone call', 'asking the audience to do something', 'an emergency', 'a question'], 1, 'Ask for action.'],
    ],
    s: [
      ['Let me leave you with one final thought.', true, null, 'Correct.'],
      ['Isn’t it time we did something about this?', true, null, 'Rhetorical question.'],
      ['Firstly, secondly and at last.', false, 'Firstly, secondly and finally.', 'finally.'],
      ['We came, we saw, we delivered.', true, null, 'Rule of three.'],
      ['Thank you all for come today.', false, 'Thank you all for coming today.', 'for + -ing.'],
      ['I’d like to begin with a question.', true, null, 'Correct.'],
    ],
  },
  'Proverbs & Sayings': {
    q: [
      ['"Don’t count your chickens before they ___."', ['hatch', 'run', 'fly', 'eat'], 0, 'hatch.'],
      ['"The early bird catches the ___."', ['fish', 'worm', 'bus', 'sun'], 1, 'worm.'],
      ['"Actions speak louder than ___."', ['music', 'words', 'money', 'people'], 1, 'words.'],
      ['"Don’t put all your eggs in one ___."', ['box', 'basket', 'bag', 'hand'], 1, 'basket.'],
      ['"Every cloud has a silver ___."', ['line', 'lining', 'edge', 'side'], 1, 'lining.'],
      ['"When in Rome, do as the ___ do."', ['Italians', 'Romans', 'locals', 'tourists'], 1, 'Romans.'],
      ['"Better late than ___."', ['early', 'never', 'sorry', 'nothing'], 1, 'never.'],
      ['"Practice makes ___."', ['money', 'perfect', 'sense', 'time'], 1, 'perfect.'],
    ],
    s: [
      ['Two heads are better than one.', true, null, 'Correct.'],
      ['Don’t judge a book by its cover.', true, null, 'Correct.'],
      ['A picture is worth a thousand of words.', false, 'A picture is worth a thousand words.', 'No "of".'],
      ['Rome wasn’t built in a day.', true, null, 'Correct.'],
      ['The grass is always greener in the other side.', false, 'The grass is always greener on the other side.', 'on the other side.'],
      ['You can’t have your cake and eat it too.', true, null, 'Correct.'],
    ],
  },
  'Common Errors for Spanish Speakers': {
    q: [
      ['Correct sentence:', ['I have 30 years.', 'I am 30 years old.', 'I have 30 years old.', 'I am 30 years.'], 1, 'be + age.'],
      ['Correct sentence:', ['People is friendly.', 'People are friendly.', 'The people is friendly.', 'Peoples are friendly.'], 1, 'People = plural.'],
      ['Correct sentence:', ['I am agree.', 'I agree.', 'I am agreed.', 'I agree with.'], 1, 'agree is a verb.'],
      ['Correct sentence:', ['She explained me the rule.', 'She explained the rule to me.', 'She explained to me the rule me.', 'She explain me.'], 1, 'explain something to someone.'],
      ['Correct sentence:', ['Depends of you.', 'It depends on you.', 'It depends of you.', 'Depends on you.'], 1, 'It depends on.'],
      ['Correct sentence:', ['I have a doubt.', 'I have a question.', 'I have doubt.', 'I doubt a question.'], 1, 'question, not doubt.'],
      ['Correct sentence:', ['He is a very good actor.', 'He is a actor very good.', 'He is very good actor.', 'He is a actor good.'], 0, 'Article + adjective + noun.'],
      ['Correct sentence:', ['I like very much this song.', 'I like this song very much.', 'I very much like song.', 'I like much this song.'], 1, 'Object before "very much".'],
    ],
    s: [
      ['I am boring in this class.', false, 'I am bored in this class.', '-ed for feelings.'],
      ['She is married to an engineer.', true, null, 'Correct.'],
      ['I have been here since three hours.', false, 'I have been here for three hours.', 'for + duration.'],
      ['Can you borrow me your pen?', false, 'Can you lend me your pen?', 'lend vs borrow.'],
      ['We arrived home late last night.', true, null, 'Correct.'],
      ['The teacher gave us an advice.', false, 'The teacher gave us some advice.', 'Advice is uncountable.'],
    ],
  },
  'Exam Strategies & Test Language': {
    q: [
      ['"Skimming" means:', ['reading every word', 'reading quickly for the main idea', 'ignoring the text', 'translating'], 1, 'Gist.'],
      ['"Scanning" means:', ['reading for specific information', 'reading slowly', 'photocopying', 'summarising'], 0, 'Specific info.'],
      ['In multiple choice, distractors are:', ['correct answers', 'wrong options designed to tempt you', 'questions', 'instructions'], 1, 'Tempting wrong answers.'],
      ['"Paraphrase" in listening tests means the answer is:', ['said exactly', 'said in different words', 'not said', 'written'], 1, 'Different words.'],
      ['Best strategy when you don’t know an answer:', ['leave it blank', 'eliminate wrong options and guess', 'copy', 'panic'], 1, 'Eliminate and guess.'],
      ['"Word limit: 150 words" means you should write:', ['exactly 150', 'about 150, not much more', '300', '50'], 1, 'Approximately.'],
      ['"Justify your answer" means:', ['make it fair', 'give reasons', 'align text', 'repeat it'], 1, 'Give reasons.'],
      ['In speaking exams, "elaborate" means:', ['stop talking', 'give more detail', 'speak fast', 'repeat'], 1, 'More detail.'],
    ],
    s: [
      ['Read the instructions carefully before you start.', true, null, 'Correct.'],
      ['Underline key words in the question.', true, null, 'Correct.'],
      ['If you finish early, leave immediately without checking.', false, 'If you finish early, use the time to check your answers.', 'Check.'],
      ['Managing your time across sections is essential.', true, null, 'Correct.'],
      ['It is better to write nothing than to guess.', false, 'It is usually better to guess than to leave a blank.', 'Guess.'],
      ['Paraphrasing the question in your answer shows understanding.', true, null, 'Correct.'],
    ],
  },
  'Review: Capstone – Real-World Communication': {
    q: [
      ['Your flight is cancelled. Best response at the desk:', ['This is your fault!', 'Could you tell me what options I have?', 'I don’t care.', 'Whatever.'], 1, 'Polite and effective.'],
      ['A client complains by email. First line:', ['You’re wrong.', 'Thank you for bringing this to our attention.', 'Not our problem.', 'OK.'], 1, 'Acknowledge.'],
      ['Networking at an event: opening line:', ['Give me your card.', 'Hi, I don’t think we’ve met. I’m Ana from Sales.', 'Who are you?', 'Buy my product.'], 1, 'Friendly introduction.'],
      ['Declining an invitation politely:', ['No.', 'I’d love to, but I have a prior commitment.', 'I don’t want to.', 'Never.'], 1, 'Polite decline.'],
      ['Asking for clarification:', ['What?', 'Sorry, could you clarify what you mean by…?', 'Huh?', 'Say it again!'], 1, 'Polite clarification.'],
      ['Giving directions: "___ the second left."', ['Take', 'Do', 'Make', 'Go'], 0, 'Take the second left.'],
      ['At a restaurant: "Could we have the ___, please?"', ['bill', 'ticket', 'note', 'paper'], 0, 'bill (UK) / check (US).'],
      ['Ending a meeting: "Let’s ___ the next steps."', ['recap', 'reckon', 'record on', 'recall to'], 0, 'recap.'],
    ],
    s: [
      ['Would you mind if I opened the window?', true, null, 'Correct.'],
      ['I’m sorry for the inconvenience this has caused.', true, null, 'Correct.'],
      ['Let’s schedule a follow-up call for next week.', true, null, 'Correct.'],
      ['Excuse me, how I can get to the station?', false, 'Excuse me, how can I get to the station?', 'Inversion in questions.'],
      ['Nice to meet you. What do you do?', true, null, 'Correct.'],
      ['I want that you send me the report.', false, 'I want you to send me the report.', 'want + object + to.'],
    ],
  },
}
