export default {
  'Perfect Aspect in Depth': {
    q: [
      ['By next June, I ___ here for a decade.', ['will work', 'will have been working', 'am working', 'work'], 1, 'Future perfect continuous.'],
      ['She looked exhausted; she ___ all night.', ['worked', 'had been working', 'has worked', 'works'], 1, 'Past perfect continuous.'],
      ['I ___ to call you all day but the line was busy.', ['tried', 'have been trying', 'had tried', 'try'], 1, 'Repeated recent attempts.'],
      ['The perfect aspect links:', ['two points in time', 'two people', 'two places', 'two clauses'], 0, 'Connects times.'],
      ['He ___ the report twice before he submitted it.', ['had revised', 'revised', 'has revised', 'was revising'], 0, 'Earlier action.'],
      ['We ___ each other since university.', ['know', 'have known', 'have been knowing', 'knew'], 1, 'State verb: simple perfect.'],
      ['By the time the CEO arrives, we ___ the room.', ['prepare', 'will have prepared', 'prepared', 'have prepared'], 1, 'Future perfect.'],
      ['"I’ve been reading that book" implies:', ['I finished it', 'I haven’t finished', 'I never started', 'I hated it'], 1, 'Unfinished activity.'],
    ],
    s: [
      ['I have been finishing the report; here it is.', false, 'I have finished the report; here it is.', 'Completed: simple perfect.'],
      ['She had been waiting for an hour when he finally arrived.', true, null, 'Correct.'],
      ['By 2030, they will have been trading for 50 years.', true, null, 'Correct.'],
      ['He has been owning that car for years.', false, 'He has owned that car for years.', 'State verb.'],
      ['We’ve been having problems with the server lately.', true, null, 'have = experience (dynamic).'],
      ['I had been knowing the answer all along.', false, 'I had known the answer all along.', 'State verb.'],
    ],
  },
  'Stative vs Dynamic Verbs': {
    q: [
      ['I ___ this soup is delicious.', ['am thinking', 'think', 'have been thinking', 'thinks'], 1, 'Opinion: stative.'],
      ['I ___ of changing jobs.', ['think', 'am thinking', 'thought', 'thinks'], 1, 'Considering: dynamic.'],
      ['This cheese ___ strange.', ['is tasting', 'tastes', 'has tasted', 'taste'], 1, 'Perception: stative.'],
      ['The chef ___ the sauce.', ['tastes', 'is tasting', 'taste', 'has taste'], 1, 'Action: dynamic.'],
      ['She ___ two houses.', ['is having', 'has', 'is owning', 'have'], 1, 'Possession: stative.'],
      ['We ___ a great time!', ['have', 'are having', 'has', 'having'], 1, 'Experience: dynamic.'],
      ['He ___ very rude today.', ['is', 'is being', 'be', 'has been'], 1, 'Temporary behaviour: is being.'],
      ['Which is normally stative?', ['run', 'belong', 'build', 'write'], 1, 'belong.'],
    ],
    s: [
      ['I am loving this song!', true, null, 'Informal emphatic use (accepted).'],
      ['She is seeming tired today.', false, 'She seems tired today.', 'Seem is stative.'],
      ['This bag is belonging to me.', false, 'This bag belongs to me.', 'Stative.'],
      ['I’m seeing the doctor at 5.', true, null, 'see = meet (dynamic).'],
      ['You are being very helpful today, thank you.', true, null, 'Temporary behaviour.'],
      ['Are you understanding the instructions?', false, 'Do you understand the instructions?', 'Stative.'],
    ],
  },
  'Future in the Past': {
    q: [
      ['I ___ call you, but I forgot.', ['will', 'was going to', 'am going to', 'would have'], 1, 'Intention in the past.'],
      ['She said she ___ arrive at six.', ['will', 'would', 'is going to', 'shall'], 1, 'would = future in the past.'],
      ['We ___ leave when the storm hit.', ['are about to', 'were about to', 'will', 'had'], 1, 'were about to.'],
      ['He knew he ___ win.', ['will', 'was going to', 'is going to', 'has'], 1, 'was going to.'],
      ['They ___ meet at 8, but the meeting was cancelled.', ['are to', 'were to', 'will', 'would have'], 1, 'were to = were scheduled to.'],
      ['I thought it ___ rain.', ['will', 'would', 'is going to', 'shall'], 1, 'would.'],
      ['"I was going to tell you" implies:', ['I told you', 'I didn’t tell you', 'I will tell you', 'I am telling you'], 1, 'Unfulfilled intention.'],
      ['The train ___ at 9, but it was delayed.', ['is due to leave', 'was due to leave', 'will leave', 'would leaving'], 1, 'was due to.'],
    ],
    s: [
      ['I was going to email you, but I got busy.', true, null, 'Correct.'],
      ['She promised she will come.', false, 'She promised she would come.', 'Past reporting: would.'],
      ['We were about to give up when the client called.', true, null, 'Correct.'],
      ['He said he is going to resign the next day.', false, 'He said he was going to resign the next day.', 'was going to.'],
      ['The event was to take place in June.', true, null, 'Correct.'],
      ['They knew they would have to work late.', true, null, 'Correct.'],
    ],
  },
  'Subjunctive & Formal Structures': {
    q: [
      ['The board demanded that he ___.', ['resigns', 'resign', 'resigned', 'will resign'], 1, 'Subjunctive: base form.'],
      ['It is essential that every employee ___ on time.', ['is', 'be', 'will be', 'was'], 1, 'be (subjunctive).'],
      ['I suggest that she ___ a lawyer.', ['consults', 'consult', 'consulted', 'will consult'], 1, 'Base form.'],
      ['If I ___ you, I’d accept.', ['was', 'were', 'am', 'be'], 1, 'were (subjunctive).'],
      ['The manager insisted that the report ___ rewritten.', ['is', 'be', 'was', 'being'], 1, 'be rewritten.'],
      ['"God ___ the Queen."', ['saves', 'save', 'saved', 'saving'], 1, 'Fixed subjunctive expression.'],
      ['It is vital that he ___ informed.', ['is', 'be', 'will be', 'being'], 1, 'be.'],
      ['We recommend that the client ___ the contract carefully.', ['reads', 'read', 'will read', 'reading'], 1, 'Base form.'],
    ],
    s: [
      ['I propose that the meeting be postponed.', true, null, 'Correct.'],
      ['It is important that she attends.', false, 'It is important that she attend.', 'Subjunctive (formal).'],
      ['They requested that he leave immediately.', true, null, 'Correct.'],
      ['If I was you, I would call her.', false, 'If I were you, I would call her.', 'were.'],
      ['The doctor recommended that he stops smoking.', false, 'The doctor recommended that he stop smoking.', 'Base form.'],
      ['Long live the king!', true, null, 'Fixed subjunctive.'],
    ],
  },
  'Ellipsis & Substitution': {
    q: [
      ['"Do you want a coffee?" "I’d love ___."', ['it', 'one', 'that', 'a'], 1, 'one = a coffee.'],
      ['"Is it raining?" "I think ___."', ['it', 'so', 'yes', 'that'], 1, 'I think so.'],
      ['"Will he come?" "I hope ___."', ['it', 'yes', 'so', 'that'], 2, 'I hope so.'],
      ['She can swim and ___.', ['I can too', 'so can I', 'Both are correct', 'I can also swim'], 2, 'Both.'],
      ['"Are you going?" "I hope ___."', ['not', 'no', 'so not', 'don’t'], 0, 'I hope not.'],
      ['I asked him to help, but he didn’t want ___.', ['to', 'it', 'that', 'do'], 0, 'didn’t want to (ellipsis).'],
      ['"I don’t like Mondays." "___ do I."', ['So', 'Neither', 'Either', 'Also'], 1, 'Neither do I.'],
      ['He ordered pizza and ___ salad.', ['he ordered', 'she', '—', 'so'], 2, 'Ellipsis of repeated subject/verb.'],
    ],
    s: [
      ['"Can you help?" "I’d be glad to."', true, null, 'Ellipsis: to.'],
      ['I think so, too.', true, null, 'Correct.'],
      ['"Is she coming?" "I don’t think."', false, '"Is she coming?" "I don’t think so."', 'think so.'],
      ['I love this one; that one is too expensive.', true, null, 'Substitution: one.'],
      ['She plays tennis and he does so.', false, 'She plays tennis and so does he.', 'so does he.'],
      ['"Did you finish?" "Not yet, but I intend to."', true, null, 'Correct.'],
    ],
  },
  'Nominalisation in Formal Writing': {
    q: [
      ['Nominalised form of "decide":', ['decisive', 'decision', 'decided', 'decidedly'], 1, 'decision.'],
      ['Formal: "We analysed the data" →', ['Data analysis was carried out.', 'We did analyse.', 'Analysing data.', 'Data was analysing.'], 0, 'Nominalisation.'],
      ['Nominalised form of "fail":', ['failure', 'failed', 'failing', 'fails'], 0, 'failure.'],
      ['"The company grew quickly" →', ['The company’s rapid growth…', 'Growing company quickly', 'The company is growth', 'Quickly growth'], 0, 'rapid growth.'],
      ['Nominalisation makes writing more:', ['casual', 'formal and abstract', 'emotional', 'spoken'], 1, 'Formal/academic.'],
      ['Nominalised form of "improve":', ['improvable', 'improvement', 'improving', 'improved'], 1, 'improvement.'],
      ['"They refused the offer" →', ['Their refusal of the offer…', 'They refusal offer', 'Refusing they offer', 'Refusal they'], 0, 'refusal of.'],
      ['Nominalised form of "explain":', ['explanatory', 'explanation', 'explained', 'explaining'], 1, 'explanation.'],
    ],
    s: [
      ['The implementation of the new policy was successful.', true, null, 'Correct.'],
      ['The reduce of costs was significant.', false, 'The reduction of costs was significant.', 'reduction.'],
      ['Customer satisfaction has increased.', true, null, 'Correct.'],
      ['Their arrive was delayed.', false, 'Their arrival was delayed.', 'arrival.'],
      ['The investigation revealed several issues.', true, null, 'Correct.'],
      ['The develop of new products takes time.', false, 'The development of new products takes time.', 'development.'],
    ],
  },
  'Hedging & Softening Language': {
    q: [
      ['Softer version of "You are wrong":', ['You’re totally wrong.', 'I’m not sure that’s quite right.', 'Wrong.', 'No.'], 1, 'Hedging.'],
      ['"It ___ be a good idea to wait."', ['must', 'might', 'is', 'will'], 1, 'might = tentative.'],
      ['Softening a request: "___ possible to reschedule?"', ['Is it', 'Would it be', 'It is', 'Can'], 1, 'Would it be possible.'],
      ['"This ___ to suggest that sales will fall."', ['seems', 'is', 'proves', 'shows'], 0, 'seems to suggest.'],
      ['Which is a hedge?', ['definitely', 'perhaps', 'certainly', 'always'], 1, 'perhaps.'],
      ['"I ___ we could look at this differently."', ['demand', 'was wondering if', 'order', 'insist'], 1, 'I was wondering if.'],
      ['"It’s ___ a bit expensive."', ['very', 'somewhat', 'totally', 'extremely'], 1, 'somewhat.'],
      ['"There ___ be a small problem."', ['is', 'appears to', 'must', 'will'], 1, 'appears to be.'],
    ],
    s: [
      ['I’m afraid that might not be possible.', true, null, 'Correct.'],
      ['Your plan is bad and will fail.', false, 'Your plan may face some challenges.', 'Too direct; hedge it.'],
      ['It seems that there has been a misunderstanding.', true, null, 'Correct.'],
      ['I was wondering if you could send it today.', true, null, 'Correct.'],
      ['Give me the report now.', false, 'Could you possibly send me the report when you have a moment?', 'Soften the request.'],
      ['Perhaps we could consider an alternative.', true, null, 'Correct.'],
    ],
  },
  'Emphatic Structures & Fronting': {
    q: [
      ['___ came the rain. (fronting)', ['Down', 'It', 'Then', 'So'], 0, 'Adverb fronting: Down came the rain.'],
      ['"A good manager he was!" This is:', ['a question', 'fronting for emphasis', 'a mistake', 'passive'], 1, 'Fronting.'],
      ['___ is the fact that we have no budget.', ['What matters', 'Matters', 'It matters', 'Mattering'], 0, 'What-cleft.'],
      ['Such ___ his talent that everyone admired him.', ['is', 'was', 'were', 'be'], 1, 'Such was … that.'],
      ['So ___ the food that we ordered more.', ['delicious was', 'was delicious', 'delicious', 'was'], 0, 'So + adj + verb + subject.'],
      ['Here ___ the bus!', ['comes', 'come', 'is coming', 'came'], 0, 'Here comes.'],
      ['___ I do, I can’t open this file.', ['Whatever', 'However', 'Whoever', 'Wherever'], 0, 'Whatever I do.'],
      ['"Off they went" means:', ['They left', 'They are off work', 'They are angry', 'They stopped'], 0, 'They departed.'],
    ],
    s: [
      ['Up went the prices again.', true, null, 'Fronting.'],
      ['So tired I was that I fell asleep.', false, 'So tired was I that I fell asleep.', 'Inversion after so + adj.'],
      ['Such was the demand that we sold out in an hour.', true, null, 'Correct.'],
      ['Here your keys are.', false, 'Here are your keys.', 'Here + verb + subject.'],
      ['Little did they know what was coming.', true, null, 'Correct.'],
      ['What I really need is more time.', true, null, 'Correct.'],
    ],
  },
  'Complex Passive Structures': {
    q: [
      ['He was made ___ for the damage.', ['pay', 'to pay', 'paying', 'paid'], 1, 'Passive of make: to + verb.'],
      ['She was seen ___ the building.', ['leave', 'to leave', 'Both leaving and to leave', 'left'], 2, 'Both possible.'],
      ['I hate ___ told what to do.', ['be', 'being', 'to being', 'been'], 1, 'Passive gerund.'],
      ['He wants ___ seriously.', ['to take', 'to be taken', 'taking', 'be taken'], 1, 'Passive infinitive.'],
      ['The problem ___ having been caused by a virus.', ['is thought', 'is thought to', 'is thought as', 'thought'], 1, 'is thought to have been.'],
      ['I was given ___.', ['a raise', 'to a raise', 'a raise to me', 'raise'], 0, 'Indirect object as subject.'],
      ['The children ___ a story every night.', ['are read', 'read to', 'are reading', 'is read'], 0, 'Passive with two objects.'],
      ['She got ___ in the traffic.', ['stuck', 'sticking', 'stick', 'to stick'], 0, 'get + participle.'],
    ],
    s: [
      ['He was made to wait for two hours.', true, null, 'Correct.'],
      ['She was let go home early.', false, 'She was allowed to go home early.', 'Let has no common passive; use allowed.'],
      ['I remember being taken to the zoo.', true, null, 'Correct.'],
      ['The car got stolen last night.', true, null, 'get-passive (informal).'],
      ['We were offered to a discount.', false, 'We were offered a discount.', 'No "to".'],
      ['He is said to has lived in Japan.', false, 'He is said to have lived in Japan.', 'to have + participle.'],
    ],
  },
  'Advanced Relative Clauses': {
    q: [
      ['The client, ___ name I forgot, called again.', ['who', 'whose', 'which', 'that'], 1, 'Possession: whose.'],
      ['The report, ___ we discussed yesterday, is ready.', ['that', 'which', 'what', 'who'], 1, 'Non-defining: which.'],
      ['I have two brothers, ___ live abroad.', ['both of whom', 'both who', 'both which', 'whom both'], 0, 'both of whom.'],
      ['The company for ___ I work is expanding.', ['who', 'whom', 'which', 'that'], 2, 'Preposition + which (things).'],
      ['She was late, ___ annoyed the boss.', ['that', 'which', 'what', 'who'], 1, 'which = the whole previous clause.'],
      ['The person to ___ I spoke was helpful.', ['who', 'whom', 'which', 'that'], 1, 'Preposition + whom.'],
      ['There were 50 candidates, ___ were qualified.', ['few of which', 'few of whom', 'few who', 'few that'], 1, 'People: whom.'],
      ['The reason ___ he left is unclear.', ['why', 'which', 'what', 'who'], 0, 'the reason why.'],
    ],
    s: [
      ['The man whom I met yesterday is the CEO.', true, null, 'Formal object: whom.'],
      ['The team, that won the prize, is from Cali.', false, 'The team, which won the prize, is from Cali.', 'Non-defining: which.'],
      ['She has three cats, all of which are black.', true, null, 'Correct.'],
      ['He failed the exam, what surprised everyone.', false, 'He failed the exam, which surprised everyone.', 'which.'],
      ['The hotel where we stayed was excellent.', true, null, 'Correct.'],
      ['The people with who I work are friendly.', false, 'The people with whom I work are friendly.', 'Preposition + whom.'],
    ],
  },
  'Conditionals: Alternatives to If': {
    q: [
      ['___ you sign today, you get a discount.', ['Provided', 'Unless', 'In case', 'Even'], 0, 'Provided (that) = if.'],
      ['Take a coat ___ it gets cold.', ['unless', 'in case', 'provided', 'as long as'], 1, 'Precaution.'],
      ['___ the delay, we finished on time.', ['Even if', 'But for', 'Unless', 'Supposing'], 1, 'But for = without.'],
      ['___ you lost your job, what would you do?', ['Supposing', 'Unless', 'Provided', 'In case'], 0, 'Supposing = imagine if.'],
      ['I’ll help ___ you do your part.', ['unless', 'as long as', 'in case', 'otherwise'], 1, 'Condition.'],
      ['Hurry up; ___ we’ll be late.', ['unless', 'otherwise', 'provided', 'in case'], 1, 'otherwise = if not.'],
      ['___ your help, I would have failed.', ['Without', 'Unless', 'Provided', 'In case of'], 0, 'Without = if not for.'],
      ['"On condition that" means:', ['because', 'only if', 'although', 'even though'], 1, 'Only if.'],
    ],
    s: [
      ['You can borrow the car provided that you fill the tank.', true, null, 'Correct.'],
      ['Take an umbrella unless it rains.', false, 'Take an umbrella in case it rains.', 'Precaution: in case.'],
      ['But for your advice, I would have made a mistake.', true, null, 'Correct.'],
      ['Supposing you won the lottery, what would you buy?', true, null, 'Correct.'],
      ['I’ll come as long as you don’t not mind.', false, 'I’ll come as long as you don’t mind.', 'Double negative.'],
      ['Otherwise you don’t hurry, you’ll miss it.', false, 'Hurry up, otherwise you’ll miss it.', 'Otherwise is not a conjunction.'],
    ],
  },
  'Modal Perfects for Speculation': {
    q: [
      ['The road is wet. It ___ rained.', ['must have', 'can’t have', 'should have', 'would have'], 0, 'Logical conclusion.'],
      ['She isn’t here. She ___ the memo.', ['must not have', 'may not have seen', 'can’t have see', 'should not have'], 1, 'Possibility.'],
      ['He ___ passed; he never studied!', ['can’t have', 'must have', 'should have', 'may have'], 0, 'Impossible.'],
      ['We ___ won if we had trained more.', ['must have', 'might have', 'can’t have', 'should'], 1, 'Possible unreal past.'],
      ['I ___ left my keys in the car.', ['must have', 'could have', 'may have', 'All are possible'], 3, 'All express speculation.'],
      ['"He will have arrived by now" expresses:', ['past order', 'certainty about the present', 'future plan', 'doubt'], 1, 'Assumption about now.'],
      ['The email ___ been sent; it’s not in my sent folder.', ['can’t have', 'must have', 'would have', 'should have'], 0, 'Impossible.'],
      ['They ___ lost their way; it’s easy to get lost there.', ['can’t have', 'might have', 'should have', 'would have'], 1, 'Possible.'],
    ],
    s: [
      ['She must have been delayed by traffic.', true, null, 'Correct.'],
      ['He can’t have finish so quickly.', false, 'He can’t have finished so quickly.', 'Participle.'],
      ['They might have missed the announcement.', true, null, 'Correct.'],
      ['You mustn’t have seen my message.', false, 'You can’t have seen my message.', 'Impossible: can’t have.'],
      ['It could have been worse.', true, null, 'Correct.'],
      ['She would have known better, I think.', true, null, 'Correct.'],
    ],
  },
  'Adverbials & Position': {
    q: [
      ['She ___ arrives late. (frequency)', ['rarely', 'late rarely', 'rarely late', 'arrives rarely'], 0, 'Frequency adverb before main verb.'],
      ['He speaks English ___.', ['fluent', 'fluently', 'in fluent', 'fluency'], 1, 'Manner adverb.'],
      ['I ___ agree with you.', ['complete', 'completely', 'completing', 'completion'], 1, 'Degree adverb.'],
      ['Where does "yesterday" usually go?', ['between subject and verb', 'at the beginning or end', 'after the auxiliary', 'before the object'], 1, 'Time adverbs: front or end.'],
      ['We have ___ finished.', ['already', 'yet', 'still', 'always'], 0, 'already after auxiliary.'],
      ['He ___ has been to Asia.', ['ever', 'never', 'yet', 'still'], 1, 'never.'],
      ['"Hardly ever" means:', ['always', 'almost never', 'often', 'sometimes'], 1, 'Almost never.'],
      ['She works ___.', ['hard', 'hardly', 'hardy', 'hardness'], 0, 'hard (adverb); hardly = almost not.'],
    ],
    s: [
      ['I always have breakfast at 7.', true, null, 'Correct.'],
      ['She speaks very good English.', true, null, 'good = adjective before noun.'],
      ['He drives very careful.', false, 'He drives very carefully.', 'Adverb.'],
      ['We hardly have any time left.', true, null, 'Correct.'],
      ['I have seen never such a mess.', false, 'I have never seen such a mess.', 'never after auxiliary.'],
      ['They go usually to the gym after work.', false, 'They usually go to the gym after work.', 'Frequency adverb before verb.'],
    ],
  },
  'Collocations: Business & Finance': {
    q: [
      ['We need to ___ a profit this year.', ['do', 'make', 'earn', 'win'], 1, 'make a profit.'],
      ['The company ___ a loss in 2020.', ['made', 'did', 'earned', 'had'], 0, 'make a loss.'],
      ['They ___ funding from investors.', ['raised', 'rose', 'lifted', 'got up'], 0, 'raise funding.'],
      ['We must ___ the deadline.', ['reach', 'meet', 'arrive', 'touch'], 1, 'meet a deadline.'],
      ['She ___ a strong team.', ['built', 'made', 'did', 'created up'], 0, 'build a team.'],
      ['The board ___ the budget.', ['approved', 'accepted with', 'agreed', 'permitted'], 0, 'approve the budget.'],
      ['We ___ into a new market.', ['expanded', 'extended', 'grew', 'increased'], 0, 'expand into.'],
      ['They ___ a contract with us.', ['did', 'signed', 'wrote', 'sealed'], 1, 'sign a contract.'],
    ],
    s: [
      ['We launched a new product line in March.', true, null, 'Correct.'],
      ['The company did a big profit last year.', false, 'The company made a big profit last year.', 'make a profit.'],
      ['Sales exceeded our expectations.', true, null, 'Correct.'],
      ['We need to catch the deadline.', false, 'We need to meet the deadline.', 'meet.'],
      ['They cut costs by 15%.', true, null, 'Correct.'],
      ['The CEO took a decision to merge.', true, null, 'take/make a decision (both ok).'],
    ],
  },
  'Idioms & Fixed Expressions': {
    q: [
      ['"Break the ice" means:', ['freeze', 'start a conversation', 'be cold', 'cancel'], 1, 'Start social interaction.'],
      ['"Hit the nail on the head" means:', ['hurt yourself', 'be exactly right', 'build a house', 'be angry'], 1, 'Exactly right.'],
      ['"Bite off more than you can chew" means:', ['eat too much', 'take on too much', 'be hungry', 'be greedy'], 1, 'Too much responsibility.'],
      ['"Once in a blue moon" means:', ['often', 'very rarely', 'at night', 'never'], 1, 'Very rarely.'],
      ['"The elephant in the room" is:', ['a big animal', 'an obvious problem nobody discusses', 'a joke', 'a big office'], 1, 'Obvious ignored problem.'],
      ['"Burn the midnight oil" means:', ['cook late', 'work late at night', 'waste energy', 'sleep'], 1, 'Work late.'],
      ['"Keep me in the loop" means:', ['tie me up', 'keep me informed', 'ignore me', 'call me'], 1, 'Keep informed.'],
      ['"Pull someone’s leg" means:', ['hurt them', 'joke with them', 'help them', 'push them'], 1, 'Joke.'],
    ],
    s: [
      ['Let’s not beat around the bush; what’s the problem?', true, null, 'Avoid the point.'],
      ['He spilled the beans about the surprise party.', true, null, 'Reveal a secret.'],
      ['It costs an arm and one leg.', false, 'It costs an arm and a leg.', 'Fixed form.'],
      ['We’re all in the same boat.', true, null, 'Same situation.'],
      ['She is under the weather today, so she isn’t coming.', true, null, 'Ill.'],
      ['That’s the last straw which broke the camel.', false, 'That’s the last straw.', 'Fixed form.'],
    ],
  },
  'Word Formation: Prefixes & Suffixes': {
    q: [
      ['Opposite of "legal":', ['unlegal', 'illegal', 'dislegal', 'inlegal'], 1, 'il- before l.'],
      ['Opposite of "responsible":', ['unresponsible', 'irresponsible', 'disresponsible', 'inresponsible'], 1, 'ir- before r.'],
      ['Noun from "happy":', ['happyness', 'happiness', 'happity', 'happen'], 1, 'happiness.'],
      ['Adjective from "success":', ['successive', 'successful', 'succeeding', 'successly'], 1, 'successful.'],
      ['"Re-" means:', ['not', 'again', 'before', 'too much'], 1, 'again.'],
      ['"Over-" in "overworked" means:', ['under', 'too much', 'again', 'not'], 1, 'too much.'],
      ['Person who employs:', ['employee', 'employer', 'employment', 'employ'], 1, '-er = doer.'],
      ['Opposite of "agree":', ['unagree', 'disagree', 'inagree', 'misagree'], 1, 'disagree.'],
    ],
    s: [
      ['The instructions were unclear.', true, null, 'Correct.'],
      ['His behaviour was very unprofessional.', true, null, 'Correct.'],
      ['That was an irregular and impolite answer.', true, null, 'Correct.'],
      ['The product is very unexpensive.', false, 'The product is very inexpensive.', 'inexpensive.'],
      ['She is a well-known writter.', false, 'She is a well-known writer.', 'One t.'],
      ['Their decision was completely unlogical.', false, 'Their decision was completely illogical.', 'illogical.'],
    ],
  },
  'Punctuation & Sentence Structure': {
    q: [
      ['Which is correct?', ['Its raining.', 'It’s raining.', 'Its’ raining.', 'It raining.'], 1, 'It’s = it is.'],
      ['Choose the correct sentence:', ['I like tea, my sister likes coffee.', 'I like tea; my sister likes coffee.', 'I like tea my sister likes coffee.', 'I like tea, and, my sister likes coffee.'], 1, 'Semicolon joins two clauses.'],
      ['A colon is used to:', ['join two nouns', 'introduce a list or explanation', 'end a question', 'show possession'], 1, 'Introduce.'],
      ['The dog wagged ___ tail.', ['it’s', 'its', 'its’', 'it'], 1, 'Possessive: its.'],
      ['"The employees’ lounge" means the lounge of:', ['one employee', 'many employees', 'the boss', 'nobody'], 1, 'Plural possessive.'],
      ['Which is a run-on sentence?', ['I came. I saw.', 'I came, I saw, I conquered.', 'I came and I saw.', 'I came; I saw.'], 1, 'Comma splice.'],
      ['Which needs a comma?', ['However we agreed.', 'However, we agreed.', 'However; we agreed.', 'However: we agreed.'], 1, 'Comma after However.'],
      ['Which is correct?', ['Whose coat is this?', 'Who’s coat is this?', 'Whos coat is this?', 'Whose’s coat is this?'], 0, 'Possessive: whose.'],
    ],
    s: [
      ['Their going to the office tomorrow.', false, 'They’re going to the office tomorrow.', 'They’re.'],
      ['We need the following: pens, paper and folders.', true, null, 'Correct.'],
      ['The meeting, which was long, ended at six.', true, null, 'Correct.'],
      ['Your welcome!', false, 'You’re welcome!', 'You’re.'],
      ['The company’s profits rose.', true, null, 'Correct.'],
      ['Lets start the meeting.', false, 'Let’s start the meeting.', 'Let’s.'],
    ],
  },
  'Paraphrasing & Summarising': {
    q: [
      ['Paraphrase: "The project was delayed due to a lack of funds."', ['The project stopped forever.', 'Insufficient money held up the project.', 'The project had lots of money.', 'Funds were delayed.'], 1, 'Same meaning, new words.'],
      ['"In other words" is used to:', ['contrast', 'rephrase', 'conclude', 'list'], 1, 'Rephrase.'],
      ['Synonym for "important":', ['trivial', 'crucial', 'small', 'optional'], 1, 'crucial.'],
      ['Summarising means:', ['copying', 'giving the main points briefly', 'adding details', 'translating'], 1, 'Main points.'],
      ['"To put it simply" introduces:', ['a complication', 'a simpler explanation', 'a question', 'a list'], 1, 'Simplification.'],
      ['Synonym for "increase":', ['decline', 'boost', 'reduce', 'fall'], 1, 'boost.'],
      ['Paraphrase: "She was let go."', ['She left early.', 'She was dismissed.', 'She was promoted.', 'She was allowed to leave.'], 1, 'Dismissed.'],
      ['"Essentially" is used to:', ['give a detail', 'state the core idea', 'disagree', 'ask'], 1, 'Core idea.'],
    ],
    s: [
      ['In short, the plan needs more funding.', true, null, 'Summarising.'],
      ['To sum up, the results were positive.', true, null, 'Correct.'],
      ['In another words, we need help.', false, 'In other words, we need help.', 'Fixed phrase.'],
      ['Basically, the customer wants a refund.', true, null, 'Correct.'],
      ['Briefly saying, we agree.', false, 'Briefly, we agree.', 'Briefly / In brief.'],
      ['The gist of the report is that costs are too high.', true, null, 'gist = main idea.'],
    ],
  },
  'Job Interviews': {
    q: [
      ['"Tell me about yourself" – best answer:', ['I like pizza.', 'A short professional summary.', 'My whole life story.', 'Nothing to say.'], 1, 'Professional summary.'],
      ['"What are your ___?" (weak points)', ['weaknesses', 'weakness', 'weaks', 'weaknessess'], 0, 'weaknesses.'],
      ['"I’m a ___ person; I get on well with everyone."', ['people', 'peoples', 'person', 'persons'], 0, 'a people person.'],
      ['"Where do you see yourself ___ five years?"', ['in', 'on', 'at', 'after'], 0, 'in five years.'],
      ['Good closing question:', ['How much holiday do I get?', 'What does success look like in this role?', 'Can I leave early?', 'Do I have to work?'], 1, 'Shows interest.'],
      ['"I thrive ___ pressure."', ['under', 'on', 'in', 'Both A and B'], 3, 'thrive under/on pressure.'],
      ['"I’m ___ to learning new skills."', ['open', 'opened', 'opening', 'openly'], 0, 'open to.'],
      ['"Notice period" means:', ['time before you can start', 'a warning', 'a sign', 'lunch break'], 0, 'Time to leave current job.'],
    ],
    s: [
      ['I have five years’ experience in sales.', true, null, 'Correct.'],
      ['I am working in my current company since 2019.', false, 'I have been working at my current company since 2019.', 'Present perfect continuous.'],
      ['My greatest strength is my attention to detail.', true, null, 'Correct.'],
      ['I am very interesting in this position.', false, 'I am very interested in this position.', 'interested.'],
      ['I’m looking for new challenges.', true, null, 'Correct.'],
      ['I left my last job because my boss was stupid.', false, 'I left my last job to seek new opportunities.', 'Stay professional.'],
    ],
  },
  'Debating & Expressing Opinions': {
    q: [
      ['Strong agreement:', ['I suppose so.', 'I couldn’t agree more.', 'Maybe.', 'Not really.'], 1, 'Couldn’t agree more.'],
      ['Polite disagreement:', ['You’re wrong.', 'I see your point, but…', 'Nonsense.', 'No.'], 1, 'I see your point, but.'],
      ['Introducing an opinion:', ['As far as I’m concerned…', 'Because…', 'Although…', 'Unless…'], 0, 'Opinion phrase.'],
      ['"That’s a fair point" means:', ['I disagree', 'I accept your argument', 'That’s unfair', 'Repeat'], 1, 'Acceptance.'],
      ['Interrupting politely:', ['Shut up.', 'Sorry to interrupt, but…', 'Stop.', 'Me now.'], 1, 'Polite interruption.'],
      ['"On the one hand… on the other hand" shows:', ['two sides', 'agreement', 'time', 'cause'], 0, 'Two perspectives.'],
      ['"Let’s agree to disagree" means:', ['we agree', 'we accept different views', 'we fight', 'we decide'], 1, 'Accept difference.'],
      ['"Playing devil’s advocate" means:', ['being evil', 'arguing the opposite to test ideas', 'agreeing', 'praying'], 1, 'Testing arguments.'],
    ],
    s: [
      ['In my opinion, remote work increases productivity.', true, null, 'Correct.'],
      ['I’m agree with you.', false, 'I agree with you.', 'agree is a verb.'],
      ['That’s true to some extent, but…', true, null, 'Correct.'],
      ['According to me, the plan is risky.', false, 'In my view, the plan is risky.', '"According to" is for others.'],
      ['I strongly believe we should invest.', true, null, 'Correct.'],
      ['With all due respect, I have to disagree.', true, null, 'Correct.'],
    ],
  },
  'Describing Processes & Instructions': {
    q: [
      ['First, ___ the machine. (imperative)', ['switching on', 'switch on', 'to switch on', 'switched'], 1, 'Imperative.'],
      ['Sequencing word:', ['Because', 'Next', 'Although', 'Whereas'], 1, 'Next.'],
      ['"___ the button is pressed, the light turns on."', ['Once', 'Unless', 'Despite', 'However'], 0, 'Once = as soon as.'],
      ['Passive in processes: "The beans ___ and then ___."', ['are roasted / ground', 'roast / grind', 'roasting / grinding', 'roasted / ground'], 0, 'Passive present.'],
      ['"Make sure ___ the file."', ['saving', 'to save', 'you save', 'saved'], 2, 'Make sure (that) you save.'],
      ['"___ you have logged in, go to Settings."', ['After', 'Unless', 'Before', 'Whereas'], 0, 'After.'],
      ['Final step marker:', ['Firstly', 'Finally', 'Then', 'Meanwhile'], 1, 'Finally.'],
      ['"Meanwhile" means:', ['before', 'at the same time', 'after', 'never'], 1, 'Simultaneously.'],
    ],
    s: [
      ['First, open the app. Then, enter your password.', true, null, 'Correct.'],
      ['The data is collected and then it is analysing.', false, 'The data is collected and then analysed.', 'Passive participle.'],
      ['Don’t forget to back up your files.', true, null, 'Correct.'],
      ['Once the paint dries, you apply the second coat.', true, null, 'Correct.'],
      ['At the beginning, you turn on the computer.', false, 'First, you turn on the computer.', '"First" for steps.'],
      ['Finally, submit the form and wait for confirmation.', true, null, 'Correct.'],
    ],
  },
  'Understanding Fast Speech & Connected Speech': {
    q: [
      ['"Wanna" is the informal form of:', ['want to', 'won’t', 'when a', 'want a'], 0, 'want to.'],
      ['"Gonna" =', ['go on', 'going to', 'gone', 'got a'], 1, 'going to.'],
      ['"Whaddya" =', ['what do you', 'what did', 'who are you', 'where are'], 0, 'what do you.'],
      ['Linking: "an apple" sounds like:', ['a-napple', 'an-apple', 'a apple', 'anapple with a pause'], 0, 'Consonant to vowel linking.'],
      ['"Dunno" =', ['don’t know', 'do not', 'done', 'do now'], 0, 'don’t know.'],
      ['"Shoulda" =', ['should have', 'should a', 'shoulder', 'should do'], 0, 'should have.'],
      ['In "next day", the /t/ is often:', ['stressed', 'dropped (elision)', 'doubled', 'sung'], 1, 'Elision.'],
      ['"Lemme" =', ['let me', 'lemon', 'lame', 'leave me'], 0, 'let me.'],
    ],
    s: [
      ['"Gimme a sec" means "give me a second".', true, null, 'Correct.'],
      ['"Gotta" means "got to / have to".', true, null, 'Correct.'],
      ['"Kinda" means "kind of".', true, null, 'Correct.'],
      ['"Wanna" is appropriate in a formal business email.', false, '"Wanna" is only appropriate in informal speech.', 'Informal.'],
      ['"Ya" is a casual form of "you".', true, null, 'Correct.'],
      ['"Dunno" means "did not".', false, '"Dunno" means "don’t know".', 'don’t know.'],
    ],
  },
  'Cultural Awareness in Communication': {
    q: [
      ['In many English-speaking business cultures, being late is:', ['fine', 'considered rude', 'expected', 'a compliment'], 1, 'Punctuality matters.'],
      ['"Small talk" is:', ['a quiet voice', 'light conversation before business', 'gossip', 'a short speech'], 1, 'Light conversation.'],
      ['Which topic is generally safe for small talk?', ['salary', 'the weather', 'religion', 'politics'], 1, 'Weather.'],
      ['"How are you?" in the US usually expects:', ['a detailed answer', 'a short positive reply', 'silence', 'a medical report'], 1, 'Brief reply.'],
      ['Directness varies by culture. British English often prefers:', ['very direct orders', 'indirect, polite requests', 'shouting', 'silence'], 1, 'Indirect politeness.'],
      ['"Cheers" in the UK can mean:', ['thanks/goodbye', 'only a toast', 'be quiet', 'no'], 0, 'Thanks / bye.'],
      ['Eye contact in Anglo cultures generally shows:', ['aggression', 'confidence and attention', 'boredom', 'disrespect'], 1, 'Attention.'],
      ['A firm handshake in business is usually seen as:', ['rude', 'confident', 'weak', 'strange'], 1, 'Confidence.'],
    ],
    s: [
      ['It’s polite to say "please" and "thank you" often in English.', true, null, 'Correct.'],
      ['Asking a colleague’s age at a first meeting is always fine.', false, 'Asking a colleague’s age at a first meeting can be considered impolite.', 'Sensitive topic.'],
      ['Arriving a few minutes early to a meeting is a good idea.', true, null, 'Correct.'],
      ['"Would you mind…?" is a polite way to make a request.', true, null, 'Correct.'],
      ['It’s normal to interrupt loudly in a formal meeting.', false, 'It’s better to wait for a pause or signal before speaking in a formal meeting.', 'Turn-taking.'],
      ['Saying "I’m fine, thanks. And you?" is a standard reply.', true, null, 'Correct.'],
    ],
  },
  'Review: Writing Professional Emails': {
    q: [
      ['Formal greeting when you don’t know the name:', ['Hey!', 'Dear Sir or Madam,', 'Hi there,', 'Yo,'], 1, 'Dear Sir or Madam.'],
      ['Purpose line: "I am writing ___ the invoice."', ['for', 'regarding', 'to about', 'in'], 1, 'regarding.'],
      ['Attachment phrase:', ['Please find attached the report.', 'Here the report.', 'Look the report.', 'Report attached you.'], 0, 'Please find attached.'],
      ['Polite request:', ['Send it now.', 'Could you please send it by Friday?', 'I need it.', 'Give it.'], 1, 'Could you please.'],
      ['Closing when you used "Dear Mr Smith":', ['Yours faithfully', 'Yours sincerely', 'Love', 'Bye'], 1, 'Known name: sincerely.'],
      ['"I look forward to ___ from you."', ['hear', 'hearing', 'heard', 'be hearing'], 1, 'look forward to + -ing.'],
      ['To apologise:', ['Whatever.', 'Please accept my apologies for…', 'Not my fault.', 'Sorry not sorry.'], 1, 'Formal apology.'],
      ['Following up: "I’m writing to ___ up on my previous email."', ['follow', 'catch', 'check', 'go'], 0, 'follow up.'],
    ],
    s: [
      ['Thank you for your prompt reply.', true, null, 'Correct.'],
      ['I look forward to meet you.', false, 'I look forward to meeting you.', 'to + -ing.'],
      ['Please let me know if you have any questions.', true, null, 'Correct.'],
      ['Attached please find the document you requested.', true, null, 'Correct.'],
      ['I am writing you for ask about the vacancy.', false, 'I am writing to ask about the vacancy.', 'writing to ask.'],
      ['Should you need anything else, do not hesitate to contact me.', true, null, 'Correct.'],
    ],
  },
}
