// Basic 1 — 24 topics. q = steal/bomb/trapdoor question bank, s = auction sentences.
// q item: [prompt, [4 options], answerIndex, explanation]
// s item: [sentence, isCorrect, fix|null, explanation]
export default {
  'First Conditional & Business/Daily Life': {
    q: [
      ['If it ___ tomorrow, we will cancel the meeting.', ['rains', 'will rain', 'rained', 'raining'], 0, 'First conditional: if + present simple, will + verb.'],
      ['If the client signs today, we ___ the project on Monday.', ['start', 'will start', 'started', 'would start'], 1, 'Result clause uses will + base verb.'],
      ['If I ___ time, I will call you after work.', ['will have', 'have', 'had', 'having'], 1, 'Never use will in the if-clause.'],
      ['If you don’t hurry, you ___ the bus.', ['miss', 'will miss', 'missed', 'are missing'], 1, 'Negative condition, future result.'],
      ['Which sentence is correct?', ['If she will study, she will pass.', 'If she studies, she will pass.', 'If she studied, she will pass.', 'If she study, she will pass.'], 1, 'Third person -s in present simple; no will in the if-clause.'],
      ['If the price ___ too high, customers won’t buy it.', ['is', 'will be', 'be', 'were'], 0, 'if + present simple.'],
      ['We ___ a bonus if we reach the sales target.', ['get', 'will get', 'got', 'would get'], 1, 'Result clause: will + verb.'],
      ['Unless you ___ the report, the boss will be angry.', ['finish', 'will finish', 'don’t finish', 'finished'], 0, 'Unless = if not; use present simple affirmative.'],
      ['What ___ you do if the Wi-Fi stops working during the call?', ['do', 'will', 'did', 'would'], 1, 'Question form: What will you do...?'],
      ['She will send the contract as soon as she ___ approval.', ['gets', 'will get', 'got', 'getting'], 0, 'Time clauses (as soon as) also use present simple.'],
    ],
    s: [
      ['If we will finish early, we will go for coffee.', false, 'If we finish early, we will go for coffee.', 'No "will" in the if-clause.'],
      ['If the manager agrees, we will launch the product in May.', true, null, 'Perfect first conditional.'],
      ['You will get a discount if you pays before Friday.', false, 'You will get a discount if you pay before Friday.', '"You" takes the base form: pay.'],
      ['If it is sunny this weekend, we will have a barbecue.', true, null, 'Correct form and word order.'],
      ['If the team don’t meets the deadline, we will lose the client.', false, 'If the team doesn’t meet the deadline, we will lose the client.', 'Auxiliary + base verb: doesn’t meet.'],
      ['Unless sales improve, the company will close the store.', true, null, 'Unless + present simple is correct.'],
      ['If you need help with the presentation, I help you.', false, 'If you need help with the presentation, I will help you.', 'Result clause needs will.'],
      ['When the CEO arrives, we will start the meeting.', true, null, 'Time clause with present simple + will.'],
    ],
  },
  'Present Simple: Routines at Work': {
    q: [
      ['She ___ at 8:30 every morning.', ['start', 'starts', 'starting', 'is start'], 1, 'Third person singular adds -s.'],
      ['___ you check your email before lunch?', ['Do', 'Does', 'Are', 'Is'], 0, 'Questions with you use Do.'],
      ['My boss ___ coffee. He prefers tea.', ['don’t drink', 'doesn’t drink', 'doesn’t drinks', 'not drink'], 1, 'doesn’t + base verb.'],
      ['We usually ___ lunch at the office.', ['has', 'have', 'having', 'haves'], 1, 'Plural subject: have.'],
      ['How often ___ your team meet?', ['do', 'does', 'is', 'are'], 1, '"Your team" is singular: does.'],
      ['The store ___ at 9 p.m. on weekdays.', ['close', 'closes', 'is close', 'closing'], 1, 'Third person singular: closes.'],
      ['I ___ to work by bus.', ['go', 'goes', 'am go', 'going'], 0, 'First person: base form.'],
      ['Which is correct?', ['He work from home.', 'He works from home.', 'He is works from home.', 'He working from home.'], 1, 'He works.'],
    ],
    s: [
      ['She answer the phone at reception.', false, 'She answers the phone at reception.', 'Third person -s.'],
      ['We finish work at six on Fridays.', true, null, 'Plural subject, base form.'],
      ['Does he speaks English at meetings?', false, 'Does he speak English at meetings?', 'After does, use the base verb.'],
      ['My manager doesn’t like long meetings.', true, null, 'doesn’t + base verb.'],
      ['I am work in the sales department.', false, 'I work in the sales department.', 'No "am" with present simple.'],
      ['The bank opens at nine.', true, null, 'Correct third person form.'],
    ],
  },
  'Present Continuous: What Are You Doing Now?': {
    q: [
      ['Look! The manager ___ to the new client.', ['talk', 'talks', 'is talking', 'talking'], 2, 'Action happening now: is + -ing.'],
      ['What ___ you doing right now?', ['is', 'are', 'do', 'does'], 1, 'are + you + -ing.'],
      ['They ___ a meeting at the moment.', ['have', 'is having', 'are having', 'having'], 2, 'Plural: are having.'],
      ['I ___ the report now. Give me ten minutes.', ['finish', 'finishing', 'am finishing', 'is finishing'], 2, 'I am + -ing.'],
      ['She isn’t ___ today; she is on holiday.', ['work', 'working', 'works', 'worked'], 1, 'isn’t + -ing.'],
      ['Spell the -ing form of "write".', ['writeing', 'writting', 'writing', 'wroting'], 2, 'Drop the silent e: writing.'],
      ['Spell the -ing form of "sit".', ['siting', 'sitting', 'seating', 'sitteing'], 1, 'Double the consonant: sitting.'],
      ['___ the printer working?', ['Is', 'Are', 'Does', 'Do'], 0, 'Singular subject: Is.'],
    ],
    s: [
      ['He is talk to a customer right now.', false, 'He is talking to a customer right now.', 'Need the -ing form.'],
      ['We are waiting for the delivery.', true, null, 'are + -ing.'],
      ['I am not understanding this email.', false, 'I don’t understand this email.', 'Understand is a state verb; no continuous.'],
      ['Are you listening to me?', true, null, 'Question form correct.'],
      ['They is having lunch now.', false, 'They are having lunch now.', 'Plural: are.'],
      ['Sorry, she is driving at the moment.', true, null, 'Action in progress.'],
    ],
  },
  'Articles: A / An / The': {
    q: [
      ['I need ___ umbrella.', ['a', 'an', 'the', '—'], 1, 'Vowel sound: an umbrella.'],
      ['She works in ___ hospital near here.', ['a', 'an', 'the', '—'], 0, 'First mention, consonant sound.'],
      ['Can you close ___ door, please?', ['a', 'an', 'the', '—'], 2, 'Specific door we both know: the.'],
      ['He is ___ honest man.', ['a', 'an', 'the', '—'], 1, 'Silent h: an honest.'],
      ['It’s ___ university course.', ['a', 'an', 'the', '—'], 0, '"University" starts with a /j/ sound: a.'],
      ['___ sun rises in the east.', ['A', 'An', 'The', '—'], 2, 'Unique things take the.'],
      ['I love ___ music.', ['a', 'an', 'the', '—'], 3, 'General uncountable: no article.'],
      ['We had ___ meeting at 10. ___ meeting was long.', ['a / A', 'a / The', 'the / A', 'an / The'], 1, 'First mention a, second mention the.'],
    ],
    s: [
      ['She is a engineer.', false, 'She is an engineer.', 'Vowel sound: an.'],
      ['I have an appointment at the dentist.', true, null, 'an before vowel sound.'],
      ['The life is beautiful.', false, 'Life is beautiful.', 'General abstract noun: no article.'],
      ['He bought a new phone yesterday.', true, null, 'First mention, singular countable.'],
      ['Can you pass me a salt?', false, 'Can you pass me the salt?', 'Specific, shared context: the.'],
      ['It’s an hour by train.', true, null, 'Silent h: an hour.'],
    ],
  },
  'There is / There are': {
    q: [
      ['___ a printer on the second floor.', ['There is', 'There are', 'It is', 'They are'], 0, 'Singular: there is.'],
      ['___ many people in the meeting room.', ['There is', 'There are', 'Is there', 'There has'], 1, 'Plural: there are.'],
      ['___ any milk in the fridge?', ['Is there', 'Are there', 'There is', 'Have there'], 0, 'Uncountable: is there any.'],
      ['There ___ two new clients today.', ['is', 'are', 'be', 'has'], 1, 'Two clients: are.'],
      ['There ___ a lot of traffic this morning.', ['were', 'was', 'are', 'have'], 1, 'Traffic is uncountable; past: was.'],
      ['How many chairs ___ in the room?', ['there is', 'is there', 'there are', 'are there'], 3, 'Question: are there.'],
      ['There ___ any free desks.', ['isn’t', 'aren’t', 'not', 'no'], 1, 'Plural negative: aren’t.'],
      ['___ a problem with the invoice.', ['There is', 'There are', 'It has', 'Have'], 0, 'Singular: there is.'],
    ],
    s: [
      ['There is three meetings today.', false, 'There are three meetings today.', 'Plural: are.'],
      ['There are some emails for you.', true, null, 'Plural + some.'],
      ['Is there any water?', true, null, 'Uncountable question.'],
      ['There have a café downstairs.', false, 'There is a café downstairs.', 'Use there is, not there have.'],
      ['There aren’t any parking spaces left.', true, null, 'Plural negative.'],
      ['Are there a bank near here?', false, 'Is there a bank near here?', 'Singular: is there.'],
    ],
  },
  'Countable & Uncountable Nouns': {
    q: [
      ['Which noun is uncountable?', ['chair', 'information', 'email', 'meeting'], 1, 'Information has no plural.'],
      ['Can you give me some ___?', ['advices', 'advice', 'an advice', 'advise'], 1, 'Advice is uncountable.'],
      ['How ___ money do we have left?', ['many', 'much', 'few', 'lots'], 1, 'Uncountable: how much.'],
      ['We need two ___ of coffee.', ['cup', 'cups', 'coffee', 'a cup'], 1, 'Count the containers: cups.'],
      ['There isn’t ___ furniture in the office.', ['many', 'much', 'a lot', 'few'], 1, 'Furniture is uncountable.'],
      ['I have a lot of ___ to do.', ['work', 'works', 'jobs', 'a work'], 0, 'Work (activity) is uncountable.'],
      ['Which is correct?', ['a bread', 'a piece of bread', 'two breads', 'many bread'], 1, 'Bread is uncountable: a piece of.'],
      ['Her ___ is blond.', ['hairs', 'hair', 'a hair', 'hair are'], 1, 'Hair is uncountable here.'],
    ],
    s: [
      ['I need some informations about the course.', false, 'I need some information about the course.', 'Uncountable: no -s.'],
      ['We don’t have much time.', true, null, 'Time is uncountable: much.'],
      ['How many luggage do you have?', false, 'How much luggage do you have?', 'Luggage is uncountable.'],
      ['There are a few chairs in the hall.', true, null, 'Countable plural: a few.'],
      ['Can I have a water, please?', true, null, 'Informal: "a water" = a bottle/glass of water. Accepted.'],
      ['She gave me many good advice.', false, 'She gave me a lot of good advice.', 'Advice is uncountable.'],
    ],
  },
  'Past Simple: Regular Verbs': {
    q: [
      ['Yesterday I ___ the client at 3 p.m.', ['call', 'called', 'calling', 'calls'], 1, 'Regular past: -ed.'],
      ['We ___ the meeting because the boss was ill.', ['cancel', 'cancelled', 'cancels', 'canceling'], 1, 'Past: cancelled.'],
      ['___ you finish the report last night?', ['Did', 'Do', 'Does', 'Were'], 0, 'Past question: Did.'],
      ['She didn’t ___ the email.', ['open', 'opened', 'opens', 'opening'], 0, 'After didn’t use the base form.'],
      ['How do you pronounce the -ed in "worked"?', ['/t/', '/d/', '/ɪd/', 'silent'], 0, 'After /k/: /t/.'],
      ['How do you pronounce the -ed in "wanted"?', ['/t/', '/d/', '/ɪd/', 'silent'], 2, 'After t/d: /ɪd/.'],
      ['They ___ to the new office in June.', ['move', 'moved', 'moving', 'moves'], 1, 'Regular past.'],
      ['Spell the past of "study".', ['studyed', 'studied', 'studed', 'studdied'], 1, 'Consonant + y → ied.'],
    ],
    s: [
      ['I worked late yesterday.', true, null, 'Regular past.'],
      ['Did you called the supplier?', false, 'Did you call the supplier?', 'After did, base form.'],
      ['She don’t answered my email.', false, 'She didn’t answer my email.', 'Negative past: didn’t + base.'],
      ['We stopped for lunch at one.', true, null, 'Double p: stopped.'],
      ['He plaied football last weekend.', false, 'He played football last weekend.', 'Vowel + y: just add -ed.'],
      ['They started the project in March.', true, null, 'Correct.'],
    ],
  },
  'Past Simple: Irregular Verbs': {
    q: [
      ['Past of "go":', ['goed', 'went', 'gone', 'goes'], 1, 'go → went.'],
      ['Past of "buy":', ['buyed', 'bought', 'brought', 'buy'], 1, 'buy → bought.'],
      ['We ___ a great presentation last week.', ['have', 'had', 'has', 'haved'], 1, 'have → had.'],
      ['She ___ the email to the wrong person.', ['send', 'sended', 'sent', 'sending'], 2, 'send → sent.'],
      ['Past of "think":', ['thinked', 'thought', 'taught', 'think'], 1, 'think → thought.'],
      ['He ___ to the office by taxi.', ['came', 'come', 'comed', 'comes'], 0, 'come → came.'],
      ['Past of "make":', ['maked', 'made', 'mode', 'make'], 1, 'make → made.'],
      ['Did you ___ the news?', ['saw', 'see', 'seen', 'seed'], 1, 'After did: base form.'],
    ],
    s: [
      ['I taked the early train.', false, 'I took the early train.', 'take → took.'],
      ['We met the new director yesterday.', true, null, 'meet → met.'],
      ['She writed a long email.', false, 'She wrote a long email.', 'write → wrote.'],
      ['They didn’t come to the party.', true, null, 'didn’t + base.'],
      ['He telled me the price.', false, 'He told me the price.', 'tell → told.'],
      ['I forgot my password again.', true, null, 'forget → forgot.'],
    ],
  },
  'Prepositions of Time (in / on / at)': {
    q: [
      ['The meeting is ___ Monday.', ['in', 'on', 'at', 'to'], 1, 'Days: on.'],
      ['I start work ___ 8 o’clock.', ['in', 'on', 'at', 'for'], 2, 'Clock times: at.'],
      ['We opened the store ___ 2019.', ['in', 'on', 'at', 'since'], 0, 'Years: in.'],
      ['She was born ___ March.', ['in', 'on', 'at', 'of'], 0, 'Months: in.'],
      ['See you ___ the weekend!', ['in', 'on', 'at', 'for'], 2, 'British: at the weekend (US: on).'],
      ['The report is due ___ the end of the month.', ['in', 'on', 'at', 'by'], 2, 'at the end of.'],
      ['I usually work ___ the morning.', ['in', 'on', 'at', 'to'], 0, 'in the morning.'],
      ['The party is ___ New Year’s Eve.', ['in', 'on', 'at', 'to'], 1, 'Specific day: on.'],
    ],
    s: [
      ['I’ll see you in Friday.', false, 'I’ll see you on Friday.', 'Days: on.'],
      ['The office closes at noon.', true, null, 'at noon / at midnight.'],
      ['We have a meeting at the afternoon.', false, 'We have a meeting in the afternoon.', 'in the afternoon.'],
      ['He was born in 1995.', true, null, 'Years: in.'],
      ['The shop is closed on Sundays.', true, null, 'Days: on.'],
      ['My birthday is on June.', false, 'My birthday is in June.', 'Months: in.'],
    ],
  },
  'Prepositions of Place': {
    q: [
      ['The keys are ___ the table.', ['in', 'on', 'at', 'under'], 1, 'Surface: on.'],
      ['She is ___ the office today.', ['in', 'on', 'at', 'to'], 2, 'at the office / at work.'],
      ['The bank is ___ the supermarket and the pharmacy.', ['between', 'among', 'next', 'behind'], 0, 'Between two things.'],
      ['The printer is ___ to the window.', ['near', 'next', 'behind', 'in front'], 1, 'next to.'],
      ['My phone is ___ my bag.', ['in', 'on', 'at', 'over'], 0, 'Inside: in.'],
      ['He lives ___ Bogotá.', ['in', 'on', 'at', 'to'], 0, 'Cities: in.'],
      ['The car is ___ the building.', ['in front', 'in front of', 'front of', 'front'], 1, 'in front of.'],
      ['Turn left; the café is ___ the corner.', ['in', 'on', 'at', 'to'], 1, 'on the corner.'],
    ],
    s: [
      ['The meeting room is in the third floor.', false, 'The meeting room is on the third floor.', 'Floors: on.'],
      ['I’m at the bus stop.', true, null, 'Points: at.'],
      ['The cat is under the desk.', true, null, 'Correct.'],
      ['She is sitting next the manager.', false, 'She is sitting next to the manager.', 'next TO.'],
      ['We live on Colombia.', false, 'We live in Colombia.', 'Countries: in.'],
      ['There is a poster on the wall.', true, null, 'Surface: on.'],
    ],
  },
  'Adverbs of Frequency': {
    q: [
      ['I ___ check my email in the morning.', ['always', 'am always', 'always am', 'ever'], 0, 'Adverb before the main verb.'],
      ['She is ___ late for work.', ['never', 'never is', 'is never', 'not never'], 0, 'Adverb after be.'],
      ['Order from most to least frequent:', ['always > usually > sometimes > never', 'sometimes > always > never', 'never > always > usually', 'usually > always > never'], 0, 'always > usually > often > sometimes > rarely > never.'],
      ['How ___ do you travel for work?', ['often', 'many', 'much', 'frequency'], 0, 'How often.'],
      ['We ___ have meetings on Fridays.', ['rarely', 'rare', 'rarely are', 'not often'], 0, 'rarely + verb.'],
      ['He ___ takes the bus. He drives.', ['hardly ever', 'always', 'usually', 'often'], 0, 'hardly ever = almost never.'],
      ['Where does the adverb go? "They ___ work ___ late."', ['sometimes / —', '— / sometimes', 'Both are possible', 'Neither'], 2, 'Sometimes can go before the verb or at the end.'],
      ['I go to the gym ___.', ['twice a week', 'two times in week', 'twice in a week', 'two a week'], 0, 'twice a week.'],
    ],
    s: [
      ['I always am on time.', false, 'I am always on time.', 'Adverb after be.'],
      ['She usually works from home on Mondays.', true, null, 'Adverb before main verb.'],
      ['They never don’t answer the phone.', false, 'They never answer the phone.', 'Never is already negative.'],
      ['We often have lunch together.', true, null, 'Correct.'],
      ['He goes sometimes to the gym.', false, 'He sometimes goes to the gym.', 'Adverb before the verb.'],
      ['Do you ever work at the weekend?', true, null, 'Ever in questions.'],
    ],
  },
  'Question Words (Wh- Questions)': {
    q: [
      ['___ is your manager? — Mr. Ruiz.', ['What', 'Who', 'Where', 'When'], 1, 'Person: who.'],
      ['___ does the meeting start? — At ten.', ['What', 'Where', 'When', 'Why'], 2, 'Time: when.'],
      ['___ do you take the bus? — Because I don’t have a car.', ['Why', 'How', 'What', 'Where'], 0, 'Reason: why.'],
      ['___ is the new office? — Downtown.', ['What', 'Where', 'Who', 'Which'], 1, 'Place: where.'],
      ['___ do you spell your name?', ['What', 'How', 'Which', 'Who'], 1, 'Manner: how.'],
      ['___ is this laptop? — It’s mine.', ['Who', 'Whose', 'Which', 'What'], 1, 'Possession: whose.'],
      ['___ colour do you prefer, blue or red?', ['What', 'Which', 'How', 'Who'], 1, 'Limited choice: which.'],
      ['___ does the ticket cost?', ['How many', 'How much', 'What much', 'How'], 1, 'Price: how much.'],
    ],
    s: [
      ['Where you work?', false, 'Where do you work?', 'Need the auxiliary do.'],
      ['What time does the train leave?', true, null, 'Correct.'],
      ['Who is she talking to?', true, null, 'Correct informal question.'],
      ['Why he is late?', false, 'Why is he late?', 'Invert be and subject.'],
      ['How old are you?', true, null, 'Correct.'],
      ['Which one do you wants?', false, 'Which one do you want?', 'After do: base form.'],
    ],
  },
  'Can / Can’t for Ability': {
    q: [
      ['She ___ speak three languages.', ['can', 'cans', 'can to', 'is can'], 0, 'can + base verb, no -s.'],
      ['I ___ swim. I never learned.', ['can', 'can’t', 'don’t can', 'not can'], 1, 'Negative: can’t.'],
      ['___ you drive a truck?', ['Can', 'Do can', 'Are', 'Can you to'], 0, 'Question: Can you...?'],
      ['He can ___ very fast.', ['type', 'to type', 'types', 'typing'], 0, 'Base form after can.'],
      ['Which is correct?', ['She can’t to come.', 'She can’t come.', 'She doesn’t can come.', 'She can’t comes.'], 1, 'can’t + base verb.'],
      ['We ___ hear you. Speak louder, please.', ['can', 'can’t', 'cans', 'don’t'], 1, 'Negative ability.'],
      ['Short answer: "Can you cook?" — "Yes, I ___."', ['do', 'can', 'am', 'cook'], 1, 'Yes, I can.'],
      ['Ana ___ play the piano, but she ___ sing.', ['can / can’t', 'can’t / can’t', 'can / cans', 'cans / can'], 0, 'Contrast: can / can’t.'],
    ],
    s: [
      ['He cans use Excel very well.', false, 'He can use Excel very well.', 'No -s on can.'],
      ['I can’t find my badge.', true, null, 'Correct.'],
      ['Can you to help me?', false, 'Can you help me?', 'No "to" after can.'],
      ['She can speak Portuguese fluently.', true, null, 'Correct.'],
      ['They don’t can attend the meeting.', false, 'They can’t attend the meeting.', 'Negative: can’t.'],
      ['Can we start now?', true, null, 'Correct.'],
    ],
  },
  'Imperatives & Instructions': {
    q: [
      ['___ the door, please.', ['Close', 'Closes', 'To close', 'Closing'], 0, 'Imperative: base form.'],
      ['___ touch that button!', ['Don’t', 'Not', 'No', 'Doesn’t'], 0, 'Negative imperative: Don’t.'],
      ['___ turn left at the bank.', ['Please', 'You please', 'Pleased', 'Pleasing'], 0, 'Please + imperative.'],
      ['To make tea: first, ___ the water.', ['boil', 'boiling', 'boils', 'to boil'], 0, 'Instruction: base form.'],
      ['___ forget to save the file.', ['Don’t', 'No', 'Not', 'Never don’t'], 0, 'Don’t forget.'],
      ['Which is a polite request?', ['Give me that.', 'Could you pass me that, please?', 'You give that.', 'Pass that!'], 1, 'Could you... please?'],
      ['___ quiet, please.', ['Be', 'Are', 'Is', 'Being'], 0, 'Imperative of be: Be.'],
      ['___ have a seat.', ['Please', 'You', 'Do you', 'Being'], 0, 'Please have a seat.'],
    ],
    s: [
      ['Not open the window.', false, 'Don’t open the window.', 'Negative imperative uses don’t.'],
      ['Please sign here.', true, null, 'Correct.'],
      ['You sit down, please.', false, 'Sit down, please.', 'Imperatives have no subject.'],
      ['Turn off your phone during the meeting.', true, null, 'Correct.'],
      ['Be careful with the coffee!', true, null, 'Correct.'],
      ['Doesn’t be late.', false, 'Don’t be late.', 'Don’t + be.'],
    ],
  },
  'Possessives (my / your / ’s)': {
    q: [
      ['This is ___ office.', ['I', 'my', 'me', 'mine'], 1, 'Possessive adjective: my.'],
      ['That’s ___ car. It belongs to Ana.', ['Ana’s', 'Anas', 'Ana', 'Anas’'], 0, 'Possessive ’s.'],
      ['The dog wagged ___ tail.', ['it’s', 'its', 'his', 'their'], 1, 'its = possessive; it’s = it is.'],
      ['Is this ___ pen? — Yes, it’s mine.', ['you', 'your', 'yours', 'you’re'], 1, 'your + noun.'],
      ['The ___ office is on the left.', ['managers', 'manager’s', 'managers’s', 'manager'], 1, 'Singular possessive.'],
      ['We love ___ new house.', ['us', 'we', 'our', 'ours'], 2, 'our + noun.'],
      ['The ___ toys are everywhere.', ['childrens’', 'children’s', 'childrens', 'children'], 1, 'Irregular plural: children’s.'],
      ['Which is correct?', ['The car of my father', 'My father’s car', 'My fathers car', 'The my father car'], 1, 'Possessive ’s with people.'],
    ],
    s: [
      ['This is the office of John.', false, 'This is John’s office.', 'Use ’s for people.'],
      ['Their meeting starts at nine.', true, null, 'their = possessive.'],
      ['The company changed it’s logo.', false, 'The company changed its logo.', 'its (no apostrophe).'],
      ['Is this your umbrella?', true, null, 'Correct.'],
      ['My sisters’ husband is a lawyer.', false, 'My sister’s husband is a lawyer.', 'One sister: sister’s.'],
      ['Our clients are very happy.', true, null, 'Correct.'],
    ],
  },
  'Object Pronouns': {
    q: [
      ['Can you help ___? I’m lost.', ['I', 'me', 'my', 'mine'], 1, 'Object: me.'],
      ['I sent the invoice to ___ yesterday.', ['they', 'them', 'their', 'theirs'], 1, 'Object: them.'],
      ['Do you know Sara? I work with ___.', ['she', 'her', 'hers', 'she’s'], 1, 'Object: her.'],
      ['This laptop is old. I want to replace ___.', ['it', 'its', 'him', 'them'], 0, 'Object: it.'],
      ['Call ___ when you arrive. We’ll be waiting.', ['we', 'our', 'us', 'ours'], 2, 'Object: us.'],
      ['Tom is nice. Everybody likes ___.', ['he', 'his', 'him', 'himself'], 2, 'Object: him.'],
      ['Between you and ___, the boss is wrong.', ['I', 'me', 'my', 'mine'], 1, 'After a preposition: me.'],
      ['Which is correct?', ['Give it to she.', 'Give it to her.', 'Give her it to.', 'Give to her it.'], 1, 'Object pronoun after to.'],
    ],
    s: [
      ['Please email I the details.', false, 'Please email me the details.', 'Object: me.'],
      ['I saw them at the conference.', true, null, 'Correct.'],
      ['She invited he to the party.', false, 'She invited him to the party.', 'Object: him.'],
      ['Can you send it to us?', true, null, 'Correct.'],
      ['Listen to she carefully.', false, 'Listen to her carefully.', 'Object: her.'],
      ['We met them last year.', true, null, 'Correct.'],
    ],
  },
  'Like / Love / Hate + -ing': {
    q: [
      ['I love ___ new people at work.', ['meet', 'meeting', 'to meeting', 'met'], 1, 'love + -ing.'],
      ['She hates ___ early.', ['get up', 'getting up', 'to getting up', 'gets up'], 1, 'hate + -ing.'],
      ['Do you like ___ presentations?', ['give', 'giving', 'gave', 'to giving'], 1, 'like + -ing.'],
      ['He doesn’t mind ___ overtime.', ['work', 'working', 'to work', 'works'], 1, 'mind + -ing.'],
      ['We enjoy ___ to podcasts.', ['listen', 'listening', 'to listen', 'listened'], 1, 'enjoy + -ing.'],
      ['I can’t stand ___ in traffic.', ['sit', 'sitting', 'to sit', 'sat'], 1, 'can’t stand + -ing.'],
      ['Spell the -ing form of "swim".', ['swiming', 'swimming', 'swimmimg', 'swimeng'], 1, 'Double m.'],
      ['Which is correct?', ['She likes dance.', 'She likes dancing.', 'She likes to dancing.', 'She like dancing.'], 1, 'likes + -ing.'],
    ],
    s: [
      ['I like work in a team.', false, 'I like working in a team.', 'like + -ing.'],
      ['He loves cooking on Sundays.', true, null, 'Correct.'],
      ['They hate to waiting.', false, 'They hate waiting.', 'No "to" with -ing.'],
      ['Do you enjoy travelling for work?', true, null, 'Correct.'],
      ['She doesn’t like drive at night.', false, 'She doesn’t like driving at night.', '-ing form needed.'],
      ['We don’t mind sharing an office.', true, null, 'Correct.'],
    ],
  },
  'Comparatives': {
    q: [
      ['This laptop is ___ than the old one.', ['fast', 'faster', 'more fast', 'fastest'], 1, 'Short adjective: -er.'],
      ['Our new office is ___ than the previous one.', ['expensiver', 'more expensive', 'most expensive', 'expensive'], 1, 'Long adjective: more.'],
      ['Comparative of "good":', ['gooder', 'more good', 'better', 'best'], 2, 'Irregular: better.'],
      ['Comparative of "big":', ['biger', 'bigger', 'more big', 'biggest'], 1, 'Double consonant: bigger.'],
      ['Comparative of "happy":', ['happyer', 'happier', 'more happy', 'happiest'], 1, 'y → ier.'],
      ['My commute is ___ than yours.', ['long', 'longer', 'more long', 'longest'], 1, 'longer than.'],
      ['Comparative of "bad":', ['badder', 'worse', 'more bad', 'worst'], 1, 'Irregular: worse.'],
      ['Online meetings are ___ than in-person meetings.', ['convenienter', 'more convenient', 'most convenient', 'convenient'], 1, 'Long adjective: more.'],
    ],
    s: [
      ['This chair is more comfortable than that one.', true, null, 'Correct.'],
      ['The train is more fast than the bus.', false, 'The train is faster than the bus.', 'Short adjective: -er.'],
      ['My job is easier that yours.', false, 'My job is easier than yours.', 'Comparative + than.'],
      ['Today is hotter than yesterday.', true, null, 'Double t.'],
      ['Her English is more better now.', false, 'Her English is better now.', 'Better is already comparative.'],
      ['Gold is more expensive than silver.', true, null, 'Correct.'],
    ],
  },
  'Superlatives': {
    q: [
      ['She is the ___ person in the team.', ['taller', 'tallest', 'most tall', 'tall'], 1, 'the + -est.'],
      ['This is the ___ restaurant in town.', ['expensivest', 'more expensive', 'most expensive', 'expensiver'], 2, 'the most + long adjective.'],
      ['Superlative of "good":', ['goodest', 'best', 'better', 'most good'], 1, 'Irregular: best.'],
      ['Superlative of "bad":', ['baddest', 'worst', 'worse', 'most bad'], 1, 'Irregular: worst.'],
      ['Monday is the ___ day of the week.', ['busyest', 'busiest', 'most busy', 'busier'], 1, 'y → iest.'],
      ['Superlative of "far":', ['farest', 'farthest', 'more far', 'farer'], 1, 'far → farthest / furthest.'],
      ['He is the ___ employee in the company.', ['younger', 'youngest', 'most young', 'young'], 1, 'the youngest.'],
      ['Which is correct?', ['the most big', 'the biggest', 'the bigest', 'the more big'], 1, 'Double g: biggest.'],
    ],
    s: [
      ['This is the best coffee in the city.', true, null, 'Correct.'],
      ['She is the most smart person I know.', false, 'She is the smartest person I know.', 'Short adjective: -est.'],
      ['It was the worse day of my life.', false, 'It was the worst day of my life.', 'Superlative: worst.'],
      ['Everest is the highest mountain in the world.', true, null, 'Correct.'],
      ['He is the most experienced manager here.', true, null, 'Correct.'],
      ['That was the funnyest movie ever.', false, 'That was the funniest movie ever.', 'y → iest.'],
    ],
  },
  'Going to for Plans': {
    q: [
      ['We ___ open a new branch next year.', ['are going to', 'going to', 'are go to', 'will going to'], 0, 'be + going to.'],
      ['I ___ visit my parents this weekend.', ['am going to', 'going to', 'am going', 'go to'], 0, 'am going to + verb.'],
      ['___ she going to join the call?', ['Is', 'Are', 'Does', 'Do'], 0, 'Is she going to.'],
      ['They ___ going to sign the deal.', ['isn’t', 'aren’t', 'don’t', 'not'], 1, 'Plural: aren’t.'],
      ['Look at those clouds! It ___ rain.', ['is going to', 'goes to', 'going', 'will going to'], 0, 'Prediction from evidence.'],
      ['What ___ you going to do after class?', ['is', 'are', 'do', 'will'], 1, 'are you going to.'],
      ['He is going ___ a new job.', ['find', 'to find', 'finding', 'found'], 1, 'going to + base verb.'],
      ['Which is correct?', ['I going to study.', 'I am going to study.', 'I am going study.', 'I go to study.'], 1, 'am going to + verb.'],
    ],
    s: [
      ['We going to have a meeting at 3.', false, 'We are going to have a meeting at 3.', 'Need "are".'],
      ['She is going to start a business.', true, null, 'Correct.'],
      ['They are going to buying a car.', false, 'They are going to buy a car.', 'Base form after going to.'],
      ['I’m not going to work tomorrow.', true, null, 'Correct.'],
      ['Are you going to the party tonight?', true, null, 'going to + place is fine.'],
      ['He is going to calls the supplier.', false, 'He is going to call the supplier.', 'Base form: call.'],
    ],
  },
  'Present Simple vs Continuous': {
    q: [
      ['Normally I ___ the bus, but today I ___ a taxi.', ['take / am taking', 'am taking / take', 'take / take', 'am taking / am taking'], 0, 'Routine vs now.'],
      ['Shh! The baby ___.', ['sleeps', 'is sleeping', 'sleep', 'sleeping'], 1, 'Right now.'],
      ['Water ___ at 100 degrees.', ['is boiling', 'boils', 'boil', 'boiling'], 1, 'General fact: present simple.'],
      ['She ___ in Cali, but she ___ in Bogotá this month.', ['lives / is working', 'is living / works', 'live / working', 'lives / works'], 0, 'Permanent vs temporary.'],
      ['I ___ what you mean.', ['am understanding', 'understand', 'understanding', 'understands'], 1, 'State verb: no continuous.'],
      ['Which is a state verb?', ['run', 'know', 'eat', 'write'], 1, 'Know describes a state.'],
      ['They ___ football every Saturday.', ['are playing', 'play', 'plays', 'playing'], 1, 'Habit: present simple.'],
      ['Why ___ you wearing a suit today?', ['do', 'are', 'is', 'does'], 1, 'Continuous question.'],
    ],
    s: [
      ['I am wanting a coffee.', false, 'I want a coffee.', 'Want is a state verb.'],
      ['He usually drives to work.', true, null, 'Habit.'],
      ['Look! It snows!', false, 'Look! It’s snowing!', 'Happening now.'],
      ['We are having a meeting right now.', true, null, 'Action now.'],
      ['She works from home this week.', false, 'She is working from home this week.', 'Temporary situation.'],
      ['I don’t know his name.', true, null, 'State verb.'],
    ],
  },
  'Would like to / Want to': {
    q: [
      ['I ___ a table for two, please.', ['would like', 'like', 'would want', 'want like'], 0, 'Polite: would like.'],
      ['She wants ___ the manager.', ['see', 'to see', 'seeing', 'saw'], 1, 'want + to + verb.'],
      ['___ you like some coffee?', ['Do', 'Would', 'Are', 'Will'], 1, 'Would you like...?'],
      ['They ___ to work on Saturdays.', ['don’t want', 'doesn’t want', 'not want', 'wouldn’t want to'], 0, 'don’t want to.'],
      ['I’d like ___ a reservation.', ['make', 'to make', 'making', 'made'], 1, 'would like + to + verb.'],
      ['"I’d like" is short for:', ['I did like', 'I would like', 'I had like', 'I should like'], 1, '’d = would.'],
      ['Which is more polite?', ['I want a coffee.', 'Give me a coffee.', 'I’d like a coffee, please.', 'Coffee.'], 2, 'Would like + please.'],
      ['He ___ to be a pilot when he was a child.', ['wanted', 'wants', 'would like', 'want'], 0, 'Past: wanted.'],
    ],
    s: [
      ['I would like buy a new phone.', false, 'I would like to buy a new phone.', 'would like TO.'],
      ['Would you like to join us?', true, null, 'Correct.'],
      ['She want to change her schedule.', false, 'She wants to change her schedule.', 'Third person -s.'],
      ['We’d like two tickets, please.', true, null, 'Correct.'],
      ['Do you would like a receipt?', false, 'Would you like a receipt?', 'No "do" with would.'],
      ['They want to open a café.', true, null, 'Correct.'],
    ],
  },
  'Some / Any / Much / Many': {
    q: [
      ['Do we have ___ paper for the printer?', ['some', 'any', 'much', 'a'], 1, 'Question: any.'],
      ['There are ___ cookies in the kitchen.', ['any', 'some', 'much', 'a'], 1, 'Affirmative: some.'],
      ['How ___ employees work here?', ['much', 'many', 'some', 'any'], 1, 'Countable: many.'],
      ['We don’t have ___ time.', ['many', 'much', 'some', 'a few'], 1, 'Uncountable negative: much.'],
      ['I didn’t see ___ clients today.', ['some', 'any', 'much', 'a'], 1, 'Negative: any.'],
      ['Would you like ___ tea?', ['any', 'some', 'many', 'much'], 1, 'Offers use some.'],
      ['There isn’t ___ sugar left.', ['many', 'much', 'some', 'a'], 1, 'Uncountable: much.'],
      ['___ people prefer to work remotely.', ['Much', 'Many', 'Any', 'A lot'], 1, 'Countable plural: many.'],
    ],
    s: [
      ['I need any help with this.', false, 'I need some help with this.', 'Affirmative: some.'],
      ['Are there any questions?', true, null, 'Correct.'],
      ['We don’t have many money.', false, 'We don’t have much money.', 'Money is uncountable.'],
      ['How much does it cost?', true, null, 'Correct.'],
      ['There are some new messages.', true, null, 'Correct.'],
      ['I don’t have some meetings today.', false, 'I don’t have any meetings today.', 'Negative: any.'],
    ],
  },
  'Review: Small Talk & Emails': {
    q: [
      ['A good way to start an email to someone you don’t know:', ['Hey!', 'Dear Mr. Smith,', 'Hi dude,', 'Yo,'], 1, 'Formal greeting.'],
      ['"How’s it going?" means:', ['Where are you going?', 'How are you?', 'What is going?', 'Are you leaving?'], 1, 'Informal greeting.'],
      ['A polite closing for a business email:', ['Bye bye', 'Best regards,', 'See ya', 'Love,'], 1, 'Best regards / Kind regards.'],
      ['"I’m writing to ___ about the invoice."', ['ask', 'asking', 'asks', 'asked'], 0, 'writing to + base verb.'],
      ['Which is small talk?', ['Sign the contract now.', 'Nice weather today, isn’t it?', 'Your report is late.', 'Pay me.'], 1, 'Casual conversation.'],
      ['"Please find ___ the report."', ['attach', 'attached', 'attaching', 'attachment'], 1, 'Please find attached.'],
      ['Reply to "Thank you so much!":', ['Yes.', 'You’re welcome!', 'Thank you too much.', 'No.'], 1, 'You’re welcome.'],
      ['"Looking forward to ___ from you."', ['hear', 'hearing', 'heard', 'hears'], 1, 'look forward to + -ing.'],
    ],
    s: [
      ['I look forward to hear from you.', false, 'I look forward to hearing from you.', 'to + -ing.'],
      ['Thank you for your quick reply.', true, null, 'Correct.'],
      ['Please find attach the invoice.', false, 'Please find attached the invoice.', 'attached.'],
      ['Could you send me the details, please?', true, null, 'Polite request.'],
      ['How do you do? — I do fine.', false, 'How do you do? — How do you do?', 'Formal greeting; the reply repeats it or "Nice to meet you".'],
      ['Have a great weekend!', true, null, 'Correct.'],
    ],
  },
}
