export default {
  'Past Continuous': {
    q: [
      ['At 9 a.m. yesterday, I ___ a client.', ['called', 'was calling', 'am calling', 'call'], 1, 'Action in progress at a past time.'],
      ['They ___ when the fire alarm rang.', ['were working', 'worked', 'are working', 'work'], 0, 'Background action interrupted.'],
      ['What ___ you doing at midnight?', ['was', 'were', 'did', 'are'], 1, 'were you doing.'],
      ['She ___ listening; she was on her phone.', ['wasn’t', 'weren’t', 'didn’t', 'isn’t'], 0, 'Singular negative: wasn’t.'],
      ['It ___ raining all afternoon.', ['was', 'were', 'is', 'did'], 0, 'Singular: was.'],
      ['We ___ dinner when the power went out.', ['had', 'were having', 'have', 'are having'], 1, 'Interrupted action.'],
      ['___ he sleeping when you arrived?', ['Was', 'Were', 'Did', 'Is'], 0, 'Was he...?'],
      ['Which is correct?', ['I was work late.', 'I was working late.', 'I working late.', 'I were working late.'], 1, 'was + -ing.'],
    ],
    s: [
      ['I was watch TV at ten last night.', false, 'I was watching TV at ten last night.', '-ing form needed.'],
      ['They were waiting for the bus.', true, null, 'Correct.'],
      ['She were talking to her boss.', false, 'She was talking to her boss.', 'Singular: was.'],
      ['Were you sleeping when I called?', true, null, 'Correct.'],
      ['We wasn’t expecting visitors.', false, 'We weren’t expecting visitors.', 'Plural: weren’t.'],
      ['The sun was shining this morning.', true, null, 'Correct.'],
    ],
  },
  'Past Simple vs Past Continuous': {
    q: [
      ['While I ___ to work, I ___ an old friend.', ['walked / was seeing', 'was walking / saw', 'walk / see', 'was walking / was seeing'], 1, 'Long action + short interruption.'],
      ['When the phone rang, she ___ a shower.', ['took', 'was taking', 'takes', 'is taking'], 1, 'In progress when interrupted.'],
      ['He ___ his leg while he ___ football.', ['broke / was playing', 'was breaking / played', 'broke / played', 'was breaking / was playing'], 0, 'Short event during a long action.'],
      ['Yesterday I ___ up, ___ breakfast and ___ to work.', ['was getting / was having / was going', 'got / had / went', 'got / was having / went', 'get / have / go'], 1, 'Sequence of completed actions.'],
      ['We ___ TV when suddenly the lights ___ off.', ['watched / were going', 'were watching / went', 'watch / go', 'were watching / were going'], 1, 'Background + sudden event.'],
      ['"While" is usually followed by:', ['past simple', 'past continuous', 'present simple', 'will'], 1, 'While + past continuous.'],
      ['I ___ the email at exactly 5 p.m.', ['sent', 'was sending', 'send', 'am sending'], 0, 'Completed action at a specific time.'],
      ['She ___ when the manager ___ in.', ['was typing / walked', 'typed / was walking', 'was typing / was walking', 'typed / walked'], 0, 'Long / short.'],
    ],
    s: [
      ['I was seeing a car accident on my way home.', false, 'I saw a car accident on my way home.', 'Short completed event: past simple.'],
      ['While we were eating, the phone rang.', true, null, 'Correct.'],
      ['He was falling asleep during the meeting.', true, null, 'Gradual action in progress; acceptable.'],
      ['When I arrived, they had lunch.', false, 'When I arrived, they were having lunch.', 'In progress on arrival: continuous.'],
      ['She was reading when I called her.', true, null, 'Correct.'],
      ['I was breaking my phone yesterday.', false, 'I broke my phone yesterday.', 'Single completed event.'],
    ],
  },
  'Will for Predictions': {
    q: [
      ['I think it ___ rain tomorrow.', ['will', 'is going', 'wills', 'would'], 0, 'Prediction: will.'],
      ['Don’t worry, you ___ the exam.', ['will pass', 'pass', 'will passing', 'passing'], 0, 'will + base verb.'],
      ['She ___ be at the office tomorrow; she’s ill.', ['won’t', 'will not be', 'doesn’t will', 'not will'], 0, 'Negative: won’t.'],
      ['___ the meeting take long?', ['Will', 'Does will', 'Is', 'Do'], 0, 'Will + subject + verb.'],
      ['I ___ probably be late.', ['will', 'am', 'going to', 'would'], 0, 'will probably.'],
      ['In 2050, people ___ on Mars.', ['live', 'will live', 'are living', 'lives'], 1, 'Future prediction.'],
      ['"Won’t" is short for:', ['would not', 'will not', 'was not', 'want not'], 1, 'won’t = will not.'],
      ['I’m sure they ___ the deal.', ['will accept', 'accept', 'will accepting', 'accepted'], 0, 'will + base verb.'],
    ],
    s: [
      ['I think she will to win.', false, 'I think she will win.', 'No "to" after will.'],
      ['It will be sunny this weekend.', true, null, 'Correct.'],
      ['They will not comes tomorrow.', false, 'They will not come tomorrow.', 'Base form after will.'],
      ['Will you be at the conference?', true, null, 'Correct.'],
      ['He wills call you later.', false, 'He will call you later.', 'Will never takes -s.'],
      ['Prices will probably rise next year.', true, null, 'Correct.'],
    ],
  },
  'Will vs Going to': {
    q: [
      ['I’ve decided. I ___ quit my job.', ['will', 'am going to', 'would', 'go to'], 1, 'Decision already made: going to.'],
      ['The phone is ringing. — I ___ get it!', ['am going to', 'will', 'going to', 'am getting'], 1, 'Spontaneous decision: will.'],
      ['Look at the sky! It ___ storm.', ['will', 'is going to', 'would', 'going'], 1, 'Prediction from evidence: going to.'],
      ['I think Colombia ___ win the match.', ['will', 'is going to', 'Both are possible', 'Neither'], 2, 'Both express predictions.'],
      ['We ___ open a new store in Cali next year. It’s all planned.', ['will', 'are going to', 'would', 'going to'], 1, 'Plan: going to.'],
      ['Which expresses a promise?', ['I’m going to call you.', 'I will always help you.', 'It’s going to rain.', 'I’m calling you.'], 1, 'Promises use will.'],
      ['Waiter: "Are you ready?" — "Yes, I ___ have the fish."', ['will', 'am going to', 'going to', 'would going'], 0, 'Decision at the moment of speaking.'],
      ['She has bought the tickets. She ___ travel to Peru.', ['will', 'is going to', 'goes to', 'would'], 1, 'Arranged plan.'],
    ],
    s: [
      ['I’m going to answer the door!', false, 'I’ll answer the door!', 'Spontaneous reaction: will.'],
      ['We are going to move to a new house in June.', true, null, 'Plan.'],
      ['Careful! You will drop it!', false, 'Careful! You’re going to drop it!', 'Evidence now: going to.'],
      ['I promise I won’t be late.', true, null, 'Promise: will.'],
      ['I think it will be a good year.', true, null, 'Opinion prediction.'],
      ['She will has a baby in March.', false, 'She is going to have a baby in March.', 'Planned; and base form after will.'],
    ],
  },
  'Present Perfect: Experiences': {
    q: [
      ['I ___ to London twice.', ['have been', 'was', 'have gone', 'went'], 0, 'Life experience: have been.'],
      ['She ___ sushi before.', ['has never eaten', 'never ate', 'has never ate', 'never has eaten'], 0, 'has + past participle.'],
      ['Past participle of "see":', ['saw', 'seen', 'seed', 'seeing'], 1, 'see – saw – seen.'],
      ['___ you ever worked abroad?', ['Did', 'Have', 'Has', 'Do'], 1, 'Have you ever...?'],
      ['We ___ this client three times.', ['have met', 'met', 'have meet', 'meeting'], 0, 'Repeated experience up to now.'],
      ['Past participle of "write":', ['wrote', 'writed', 'written', 'writing'], 2, 'write – wrote – written.'],
      ['He ___ his homework yet.', ['hasn’t finished', 'didn’t finish', 'hasn’t finish', 'not finished'], 0, 'hasn’t + participle.'],
      ['I ___ that movie. Is it good?', ['haven’t seen', 'didn’t saw', 'haven’t saw', 'not have seen'], 0, 'haven’t + seen.'],
    ],
    s: [
      ['I have visit Mexico many times.', false, 'I have visited Mexico many times.', 'Past participle: visited.'],
      ['Have you ever tried Indian food?', true, null, 'Correct.'],
      ['She has went to Paris.', false, 'She has been to Paris.', 'Participle: been/gone.'],
      ['We have never lost a client.', true, null, 'Correct.'],
      ['They have saw the new office.', false, 'They have seen the new office.', 'seen.'],
      ['He has worked in three countries.', true, null, 'Correct.'],
    ],
  },
  'Present Perfect with Ever / Never': {
    q: [
      ['Have you ___ been to a conference?', ['ever', 'never', 'yet', 'already'], 0, 'Questions: ever.'],
      ['I have ___ driven a truck.', ['ever', 'never', 'yet', 'just'], 1, 'Negative meaning: never.'],
      ['This is the best pizza I have ___ eaten!', ['never', 'ever', 'yet', 'still'], 1, 'Superlative + ever.'],
      ['She has never ___ late.', ['be', 'was', 'been', 'being'], 2, 'never + participle.'],
      ['Where does "ever" go?', ['Have ever you been…', 'Have you ever been…', 'Ever have you been…', 'Have you been ever…'], 1, 'Between subject and participle.'],
      ['"Never" already means not, so we:', ['add not too', 'don’t add not', 'use didn’t', 'use no'], 1, 'Never is negative: I have never…'],
      ['Has he ___ met the CEO?', ['ever', 'never', 'yet', 'ago'], 0, 'ever in questions.'],
      ['I ___ seen such a big office.', ['have never', 'never have', 'have ever', 'did never'], 0, 'have never seen.'],
    ],
    s: [
      ['I haven’t never been to Brazil.', false, 'I have never been to Brazil.', 'Don’t double the negative.'],
      ['Have you ever lost your passport?', true, null, 'Correct.'],
      ['She has ever been to Japan.', false, 'She has never been to Japan.', 'Ever is for questions.'],
      ['It’s the worst traffic I have ever seen.', true, null, 'Superlative + ever.'],
      ['We have never missed a deadline.', true, null, 'Correct.'],
      ['Did you ever have been to Chile?', false, 'Have you ever been to Chile?', 'Use have, not did.'],
    ],
  },
  'Have to / Must / Should': {
    q: [
      ['You ___ wear a badge in the building. It’s the rule.', ['should', 'must', 'can', 'might'], 1, 'Strong obligation: must.'],
      ['She ___ work on Saturdays; her contract says so.', ['has to', 'have to', 'should', 'musts'], 0, 'Third person: has to.'],
      ['You look tired. You ___ go to bed early.', ['must', 'should', 'have to', 'can'], 1, 'Advice: should.'],
      ['We ___ hurry; there’s plenty of time.', ['mustn’t', 'don’t have to', 'shouldn’t', 'can’t'], 1, 'Not necessary: don’t have to.'],
      ['You ___ smoke here. It’s prohibited.', ['don’t have to', 'mustn’t', 'shouldn’t', 'have to'], 1, 'Prohibition: mustn’t.'],
      ['___ I have to bring my ID?', ['Do', 'Must', 'Have', 'Should'], 0, 'Do I have to...?'],
      ['Past of "must" (obligation):', ['musted', 'had to', 'must have', 'should'], 1, 'must → had to.'],
      ['He ___ be so rude to clients.', ['shouldn’t', 'doesn’t have to', 'must', 'has to'], 0, 'Advice negative: shouldn’t.'],
    ],
    s: [
      ['You don’t must park here.', false, 'You mustn’t park here.', 'Negative: mustn’t.'],
      ['I have to finish this by Friday.', true, null, 'Correct.'],
      ['She should to see a doctor.', false, 'She should see a doctor.', 'No "to" after should.'],
      ['We don’t have to wear a uniform.', true, null, 'Not necessary.'],
      ['He musts sign the form.', false, 'He must sign the form.', 'Must never takes -s.'],
      ['You should practise English every day.', true, null, 'Correct.'],
    ],
  },
  'Second Conditional': {
    q: [
      ['If I ___ rich, I would travel the world.', ['am', 'were', 'will be', 'would be'], 1, 'Hypothetical: if + past (were).'],
      ['If she had more time, she ___ a course.', ['will take', 'would take', 'takes', 'took'], 1, 'would + base verb.'],
      ['What ___ you do if you won the lottery?', ['will', 'would', 'do', 'did'], 1, 'Would you do.'],
      ['If we ___ in Miami, we would go to the beach every day.', ['live', 'lived', 'would live', 'will live'], 1, 'Past simple in the if-clause.'],
      ['I ___ that if I were you.', ['won’t do', 'wouldn’t do', 'don’t do', 'didn’t do'], 1, 'wouldn’t + base.'],
      ['The second conditional talks about:', ['real future', 'unreal/imaginary present', 'past facts', 'habits'], 1, 'Imaginary situations.'],
      ['If he ___ harder, he would get promoted.', ['works', 'worked', 'would work', 'will work'], 1, 'Past simple form.'],
      ['Which is correct?', ['If I would have money…', 'If I had money…', 'If I have had money…', 'If I will have money…'], 1, 'No would in the if-clause.'],
    ],
    s: [
      ['If I would be you, I would accept the offer.', false, 'If I were you, I would accept the offer.', 'No would in the if-clause.'],
      ['If we had a bigger office, we would hire more people.', true, null, 'Correct.'],
      ['She would travel more if she has time.', false, 'She would travel more if she had time.', 'Past simple in the if-clause.'],
      ['What would you do if you lost your job?', true, null, 'Correct.'],
      ['If it was cheaper, I would buy it.', true, null, '"Was" is accepted informally.'],
      ['If they knew the answer, they will tell us.', false, 'If they knew the answer, they would tell us.', 'would, not will.'],
    ],
  },
  'Zero Conditional': {
    q: [
      ['If you ___ water, it boils.', ['heat', 'will heat', 'heated', 'would heat'], 0, 'General truth: present + present.'],
      ['If employees ___ late, they lose points.', ['arrive', 'will arrive', 'arrived', 'arriving'], 0, 'Present simple in both parts.'],
      ['Ice ___ if you leave it in the sun.', ['melts', 'will melt', 'melt', 'melted'], 0, 'Present simple result.'],
      ['The zero conditional describes:', ['imaginary situations', 'facts and routines', 'past regrets', 'future plans'], 1, 'General truths.'],
      ['___ you mix red and blue, you get purple.', ['If', 'Would', 'Unless', 'Although'], 0, 'If/when.'],
      ['If the system ___, call IT.', ['crash', 'crashes', 'will crash', 'crashed'], 1, 'Third person -s.'],
      ['"If" in a zero conditional can be replaced by:', ['when', 'would', 'will', 'so'], 0, 'If = when for general truths.'],
      ['If I ___ coffee at night, I don’t sleep.', ['drink', 'drank', 'will drink', 'drinking'], 0, 'Habit.'],
    ],
    s: [
      ['If you press this button, the machine will stops.', false, 'If you press this button, the machine stops.', 'Present simple result.'],
      ['Plants die if they don’t get water.', true, null, 'General truth.'],
      ['When I am tired, I go to bed early.', true, null, 'Correct.'],
      ['If it will rain, the streets get wet.', false, 'If it rains, the streets get wet.', 'No will in zero conditional.'],
      ['If she eat too much, she feels sick.', false, 'If she eats too much, she feels sick.', 'Third person -s.'],
      ['If the light is red, you stop.', true, null, 'Correct.'],
    ],
  },
  'Too / Enough': {
    q: [
      ['This coffee is ___ hot to drink.', ['enough', 'too', 'very', 'so'], 1, 'too + adjective = excess.'],
      ['He isn’t old ___ to drive.', ['too', 'enough', 'very', 'much'], 1, 'adjective + enough.'],
      ['We don’t have ___ chairs for everyone.', ['too', 'enough', 'too many', 'so'], 1, 'enough + noun.'],
      ['There are ___ people in the room.', ['too much', 'too many', 'enough much', 'too'], 1, 'Countable: too many.'],
      ['She works ___ much.', ['too', 'enough', 'many', 'very'], 0, 'too much.'],
      ['Where does "enough" go with a noun?', ['money enough', 'enough money', 'the enough money', 'money the enough'], 1, 'Before nouns.'],
      ['Where does "enough" go with an adjective?', ['enough big', 'big enough', 'the big enough', 'enough the big'], 1, 'After adjectives.'],
      ['I’m ___ tired to go out tonight.', ['enough', 'too', 'very', 'much'], 1, 'too tired to.'],
    ],
    s: [
      ['The room is too small for twenty people.', true, null, 'Correct.'],
      ['He is enough tall to reach the shelf.', false, 'He is tall enough to reach the shelf.', 'adjective + enough.'],
      ['We have too much homework this week.', true, null, 'Uncountable: too much.'],
      ['There isn’t enough time to finish.', true, null, 'Correct.'],
      ['I ate too many food.', false, 'I ate too much food.', 'Food is uncountable.'],
      ['This box is too heavy for carry.', false, 'This box is too heavy to carry.', 'too + adjective + to-infinitive.'],
    ],
  },
  'Used to': {
    q: [
      ['I ___ live in Medellín, but now I live in Cali.', ['used to', 'use to', 'was used to', 'am used to'], 0, 'Past habit: used to.'],
      ['She ___ smoke, but she quit.', ['used to', 'uses to', 'is used to', 'used'], 0, 'Past habit.'],
      ['___ you use to play football?', ['Did', 'Do', 'Were', 'Have'], 0, 'Question: Did you use to.'],
      ['We ___ have a car; we always took the bus.', ['didn’t use to', 'didn’t used to', 'don’t used to', 'not used to'], 0, 'Negative: didn’t use to.'],
      ['"Used to" describes:', ['present habits', 'past habits or states that are no longer true', 'future plans', 'abilities'], 1, 'Past habits/states.'],
      ['He ___ be shy, but now he is very confident.', ['used to', 'use to', 'is used to', 'used'], 0, 'Past state.'],
      ['There ___ be a cinema here.', ['used to', 'use to', 'was used to', 'used'], 0, 'There used to be.'],
      ['Which is correct?', ['I use to work there.', 'I used to work there.', 'I was use to work there.', 'I am used to worked there.'], 1, 'used to + base verb.'],
    ],
    s: [
      ['I use to drink a lot of soda.', false, 'I used to drink a lot of soda.', 'Past: used to.'],
      ['She didn’t use to like coffee.', true, null, 'Correct negative.'],
      ['They used to going to the beach every summer.', false, 'They used to go to the beach every summer.', 'Base form after used to.'],
      ['Did you use to live here?', true, null, 'Correct.'],
      ['We used to have meetings every day.', true, null, 'Correct.'],
      ['He is used to work late.', false, 'He is used to working late.', 'be used to + -ing (different structure).'],
    ],
  },
  'Phrasal Verbs I': {
    q: [
      ['Please ___ the lights when you leave.', ['turn off', 'turn on', 'turn up', 'turn in'], 0, 'turn off = switch off.'],
      ['I need to ___ this word in the dictionary.', ['look after', 'look up', 'look for', 'look out'], 1, 'look up = search for information.'],
      ['Can you ___ me ___ at the airport?', ['pick / up', 'pick / out', 'take / off', 'give / up'], 0, 'pick up = collect.'],
      ['Don’t ___! You can do it.', ['give up', 'give in', 'give away', 'give back'], 0, 'give up = stop trying.'],
      ['The meeting was ___ because of the storm.', ['called off', 'called up', 'called in', 'called back'], 0, 'call off = cancel.'],
      ['I ___ at 6 every day.', ['get up', 'get on', 'get in', 'get over'], 0, 'get up = leave bed.'],
      ['Please ___ this form.', ['fill in', 'fill up', 'fill over', 'fill on'], 0, 'fill in = complete.'],
      ['I’ll ___ you ___ later. I’m busy now.', ['call / back', 'call / off', 'call / on', 'call / in'], 0, 'call back = return a call.'],
    ],
    s: [
      ['Can you turn the volume down, please?', true, null, 'Separable phrasal verb.'],
      ['I’m looking for my keys.', true, null, 'Correct.'],
      ['Please pick up me at seven.', false, 'Please pick me up at seven.', 'Pronoun goes between.'],
      ['She gave up smoking last year.', true, null, 'Correct.'],
      ['We ran out milk.', false, 'We ran out of milk.', 'run out OF.'],
      ['Turn on the computer and log in.', true, null, 'Correct.'],
    ],
  },
  'Relative Clauses (who / which / that)': {
    q: [
      ['The woman ___ works at reception is very friendly.', ['which', 'who', 'where', 'whose'], 1, 'People: who.'],
      ['This is the laptop ___ I bought last week.', ['who', 'which', 'where', 'whom'], 1, 'Things: which/that.'],
      ['The office ___ we work is downtown.', ['which', 'where', 'who', 'that'], 1, 'Places: where.'],
      ['He is the client ___ company is in Spain.', ['who', 'which', 'whose', 'that'], 2, 'Possession: whose.'],
      ['"That" can replace:', ['only who', 'only which', 'who and which', 'where'], 2, 'That is used for people and things.'],
      ['The people ___ came to the meeting were happy.', ['which', 'who', 'where', 'whose'], 1, 'People: who.'],
      ['The report ___ you sent is excellent.', ['who', 'that', 'where', 'whose'], 1, 'Things: that.'],
      ['The day ___ we met was rainy.', ['which', 'when', 'where', 'who'], 1, 'Time: when.'],
    ],
    s: [
      ['The man which called you is my boss.', false, 'The man who called you is my boss.', 'People: who.'],
      ['This is the café where we had lunch.', true, null, 'Correct.'],
      ['I liked the film that we watched.', true, null, 'Correct.'],
      ['She is the person who’s car is red.', false, 'She is the person whose car is red.', 'Possessive: whose.'],
      ['The phone who I bought is broken.', false, 'The phone that I bought is broken.', 'Things: that/which.'],
      ['The hotel which we stayed in was great.', true, null, 'Correct.'],
    ],
  },
  'Passive Voice: Present': {
    q: [
      ['English ___ in many countries.', ['speaks', 'is spoken', 'is speak', 'spoken'], 1, 'is + past participle.'],
      ['These products ___ in Colombia.', ['are made', 'is made', 'make', 'are make'], 0, 'Plural: are made.'],
      ['The office ___ every evening.', ['cleans', 'is cleaned', 'is clean', 'cleaned'], 1, 'is cleaned.'],
      ['Active: "They sell coffee here." Passive:', ['Coffee sells here.', 'Coffee is sold here.', 'Coffee is sell here.', 'Coffee sold here.'], 1, 'is sold.'],
      ['___ the invoices sent by email?', ['Do', 'Are', 'Is', 'Does'], 1, 'Plural question: Are.'],
      ['The passive is used when:', ['the agent is important', 'the action or object is more important than who does it', 'we talk about the future', 'never'], 1, 'Focus on the action/result.'],
      ['Reports ___ by the finance team.', ['are prepared', 'prepared', 'prepares', 'is prepared'], 0, 'are prepared by.'],
      ['This phone ___ in China.', ['is make', 'is made', 'makes', 'made'], 1, 'is made.'],
    ],
    s: [
      ['The emails are send every morning.', false, 'The emails are sent every morning.', 'Past participle: sent.'],
      ['Spanish is spoken in Colombia.', true, null, 'Correct.'],
      ['The rooms is cleaned daily.', false, 'The rooms are cleaned daily.', 'Plural: are.'],
      ['Our products are exported to Europe.', true, null, 'Correct.'],
      ['The meeting is hold on Mondays.', false, 'The meeting is held on Mondays.', 'Participle: held.'],
      ['Breakfast is served from 7 to 10.', true, null, 'Correct.'],
    ],
  },
  'Passive Voice: Past': {
    q: [
      ['The company ___ in 1998.', ['founded', 'was founded', 'was found', 'is founded'], 1, 'was + founded.'],
      ['The documents ___ yesterday.', ['were signed', 'was signed', 'signed', 'were sign'], 0, 'Plural: were signed.'],
      ['Active: "Someone stole my bike." Passive:', ['My bike was stolen.', 'My bike stole.', 'My bike was steal.', 'My bike is stolen.'], 0, 'was stolen.'],
      ['The building ___ by a famous architect.', ['designed', 'was designed', 'is designed', 'was design'], 1, 'was designed by.'],
      ['___ the package delivered on time?', ['Was', 'Were', 'Did', 'Is'], 0, 'Singular: Was.'],
      ['The Mona Lisa ___ by Leonardo da Vinci.', ['painted', 'was painted', 'is painted', 'were painted'], 1, 'was painted by.'],
      ['We ___ about the change.', ['weren’t told', 'didn’t told', 'weren’t tell', 'not told'], 0, 'weren’t + told.'],
      ['The car ___ last week.', ['was repaired', 'repaired', 'is repaired', 'was repair'], 0, 'was repaired.'],
    ],
    s: [
      ['The email was send to the wrong address.', false, 'The email was sent to the wrong address.', 'Participle: sent.'],
      ['The contract was signed on Monday.', true, null, 'Correct.'],
      ['The windows was broken by the storm.', false, 'The windows were broken by the storm.', 'Plural: were.'],
      ['Two employees were promoted last month.', true, null, 'Correct.'],
      ['The problem was solved quickly.', true, null, 'Correct.'],
      ['The photos were took by my brother.', false, 'The photos were taken by my brother.', 'Participle: taken.'],
    ],
  },
  'Reported Speech: Statements': {
    q: [
      ['"I am tired." → She said she ___ tired.', ['is', 'was', 'were', 'be'], 1, 'Present → past.'],
      ['"We work here." → They said they ___ there.', ['work', 'worked', 'working', 'works'], 1, 'Present simple → past simple.'],
      ['"I will call you." → He said he ___ call me.', ['will', 'would', 'was', 'shall'], 1, 'will → would.'],
      ['"I can swim." → She said she ___ swim.', ['can', 'could', 'may', 'will'], 1, 'can → could.'],
      ['"I bought a car." → He said he ___ a car.', ['bought', 'had bought', 'has bought', 'buys'], 1, 'Past simple → past perfect.'],
      ['"Today" in reported speech often becomes:', ['tomorrow', 'that day', 'this day', 'today'], 1, 'today → that day.'],
      ['"I am working now." → She said she ___ working then.', ['is', 'was', 'were', 'has been'], 1, 'am → was.'],
      ['Direct: "My boss is angry." Reported: She told me her boss ___ angry.', ['is', 'was', 'were', 'be'], 1, 'is → was.'],
    ],
    s: [
      ['He said me he was busy.', false, 'He told me he was busy.', 'tell + person; say without.'],
      ['She said that she would help us.', true, null, 'Correct.'],
      ['They told that the meeting was cancelled.', false, 'They said that the meeting was cancelled.', 'Tell needs an object.'],
      ['He said he had finished the report.', true, null, 'Correct.'],
      ['She said she can come tomorrow.', false, 'She said she could come the next day.', 'can → could; tomorrow → the next day.'],
      ['My manager told me I was doing a great job.', true, null, 'Correct.'],
    ],
  },
  'Quantifiers: A few / A little': {
    q: [
      ['We have ___ minutes before the call.', ['a little', 'a few', 'little', 'much'], 1, 'Countable: a few.'],
      ['Can I have ___ milk, please?', ['a few', 'a little', 'few', 'many'], 1, 'Uncountable: a little.'],
      ['There are ___ good restaurants near here.', ['a few', 'a little', 'little', 'much'], 0, 'Countable: a few.'],
      ['I speak ___ Portuguese.', ['a few', 'a little', 'few', 'many'], 1, 'Uncountable: a little.'],
      ['"Few" (without a) means:', ['some, enough', 'almost none, not enough', 'many', 'a lot'], 1, 'Negative meaning.'],
      ['She has ___ friends, so she is lonely.', ['a few', 'few', 'a little', 'little'], 1, 'few = not enough.'],
      ['We have ___ time; let’s hurry.', ['a little', 'little', 'few', 'a few'], 1, 'little = not enough.'],
      ['Only ___ people came to the event.', ['a little', 'a few', 'little', 'much'], 1, 'Countable: a few.'],
    ],
    s: [
      ['I need a few sugar in my coffee.', false, 'I need a little sugar in my coffee.', 'Uncountable: a little.'],
      ['We have a few questions.', true, null, 'Correct.'],
      ['There is a little water left.', true, null, 'Correct.'],
      ['He has a little friends in the city.', false, 'He has a few friends in the city.', 'Countable: a few.'],
      ['Few people know this secret.', true, null, 'Few = not many.'],
      ['I have little coins in my pocket.', false, 'I have a few coins in my pocket.', 'Countable: a few.'],
    ],
  },
  'Gerunds & Infinitives I': {
    q: [
      ['I want ___ a new job.', ['find', 'finding', 'to find', 'found'], 2, 'want + to-infinitive.'],
      ['She enjoys ___ with clients.', ['talk', 'talking', 'to talk', 'talked'], 1, 'enjoy + -ing.'],
      ['We decided ___ the offer.', ['accept', 'accepting', 'to accept', 'accepted'], 2, 'decide + to-infinitive.'],
      ['He finished ___ the report at 6.', ['write', 'writing', 'to write', 'wrote'], 1, 'finish + -ing.'],
      ['___ is good for your health.', ['Swim', 'Swimming', 'To swimming', 'Swam'], 1, 'Gerund as subject.'],
      ['I hope ___ you soon.', ['see', 'seeing', 'to see', 'saw'], 2, 'hope + to.'],
      ['Would you mind ___ the window?', ['open', 'opening', 'to open', 'opened'], 1, 'mind + -ing.'],
      ['They need ___ more staff.', ['hire', 'hiring', 'to hire', 'hired'], 2, 'need + to.'],
    ],
    s: [
      ['I want going home.', false, 'I want to go home.', 'want + to.'],
      ['She suggested taking a break.', true, null, 'suggest + -ing.'],
      ['We plan to launch in April.', true, null, 'plan + to.'],
      ['He avoided to answer the question.', false, 'He avoided answering the question.', 'avoid + -ing.'],
      ['Thanks for to help me.', false, 'Thanks for helping me.', 'Preposition + -ing.'],
      ['I’d like to make a reservation.', true, null, 'Correct.'],
    ],
  },
  'Adjectives -ed / -ing': {
    q: [
      ['The lecture was so ___ that I fell asleep.', ['bored', 'boring', 'bore', 'boredom'], 1, 'The thing is boring.'],
      ['I was very ___ by the news.', ['surprised', 'surprising', 'surprise', 'surprises'], 0, 'The person feels surprised.'],
      ['This game is really ___!', ['excited', 'exciting', 'excite', 'excites'], 1, 'The game is exciting.'],
      ['We were ___ after the long trip.', ['tiring', 'tired', 'tire', 'tires'], 1, 'People feel tired.'],
      ['The instructions were ___.', ['confused', 'confusing', 'confuse', 'confusion'], 1, 'The thing causes confusion.'],
      ['She is ___ in art.', ['interesting', 'interested', 'interest', 'interests'], 1, 'interested in.'],
      ['-ing adjectives describe:', ['how a person feels', 'the thing or person that causes the feeling', 'the past', 'plural nouns'], 1, 'Cause of the feeling.'],
      ['My boss is a very ___ person.', ['relaxed', 'relaxing', 'Both are possible', 'Neither'], 2, 'Relaxed (feels calm) or relaxing (makes others calm).'],
    ],
    s: [
      ['I am boring in this class.', false, 'I am bored in this class.', 'Feeling: bored.'],
      ['The movie was frightening.', true, null, 'Correct.'],
      ['She was disappointing with the results.', false, 'She was disappointed with the results.', 'Feeling: disappointed.'],
      ['It’s an amazing opportunity.', true, null, 'Correct.'],
      ['We are excited about the trip.', true, null, 'Correct.'],
      ['That was an embarrassed moment.', false, 'That was an embarrassing moment.', 'The moment causes embarrassment.'],
    ],
  },
  'So / Such': {
    q: [
      ['It was ___ a good meeting!', ['so', 'such', 'very', 'too'], 1, 'such + a + adj + noun.'],
      ['The coffee was ___ hot that I couldn’t drink it.', ['such', 'so', 'such a', 'too'], 1, 'so + adjective.'],
      ['They are ___ nice people.', ['so', 'such', 'such a', 'so a'], 1, 'such + adj + plural noun.'],
      ['He speaks ___ quickly!', ['such', 'so', 'such a', 'so a'], 1, 'so + adverb.'],
      ['We had ___ fun at the party.', ['so', 'such', 'such a', 'so much a'], 1, 'such + uncountable noun.'],
      ['There were ___ many people that we couldn’t enter.', ['such', 'so', 'such a', 'too'], 1, 'so many.'],
      ['It was ___ expensive restaurant.', ['so', 'such', 'such an', 'so an'], 2, 'such an + adj + noun.'],
      ['"So" is followed by:', ['a noun', 'an adjective or adverb', 'a verb', 'a sentence only'], 1, 'so + adj/adv.'],
    ],
    s: [
      ['It was so a long day.', false, 'It was such a long day.', 'such a + noun.'],
      ['She is so talented.', true, null, 'Correct.'],
      ['They gave us such good advice.', true, null, 'Correct.'],
      ['The test was such difficult.', false, 'The test was so difficult.', 'so + adjective.'],
      ['He is such a kind man.', true, null, 'Correct.'],
      ['I was so tired that I fell asleep on the bus.', true, null, 'Correct.'],
    ],
  },
  'Indefinite Pronouns': {
    q: [
      ['___ called while you were out.', ['Someone', 'Anyone', 'No one didn’t', 'Something'], 0, 'Affirmative: someone.'],
      ['Is there ___ in the office?', ['someone', 'anyone', 'no one', 'everyone'], 1, 'Question: anyone.'],
      ['I have ___ to tell you.', ['anything', 'something', 'nothing else', 'everything not'], 1, 'Affirmative: something.'],
      ['___ is ready. Let’s start.', ['Everything', 'Anything', 'Nothing', 'Something'], 0, 'Everything is ready.'],
      ['There was ___ in the room. It was empty.', ['anyone', 'someone', 'nobody', 'everybody'], 2, 'nobody = no person.'],
      ['I didn’t see ___ at the party.', ['someone', 'anyone', 'no one', 'everyone'], 1, 'Negative: anyone.'],
      ['Let’s go ___ quiet.', ['anywhere', 'somewhere', 'nowhere', 'everywhere'], 1, 'Affirmative: somewhere.'],
      ['Indefinite pronouns take a ___ verb.', ['plural', 'singular', 'past', 'continuous'], 1, 'Everyone IS.'],
    ],
    s: [
      ['Everybody are here.', false, 'Everybody is here.', 'Indefinite pronouns are singular.'],
      ['I don’t know nobody in this city.', false, 'I don’t know anybody in this city.', 'Avoid double negatives.'],
      ['Somebody left their umbrella.', true, null, 'Correct (their is fine).'],
      ['Is there anything I can do?', true, null, 'Correct.'],
      ['Nothing is impossible.', true, null, 'Correct.'],
      ['I need someone to help me, does anyone have time?', true, null, 'Correct.'],
    ],
  },
  'Be able to / Manage to': {
    q: [
      ['I won’t ___ attend the meeting tomorrow.', ['can', 'be able to', 'able to', 'could'], 1, 'Future: will be able to.'],
      ['She ___ finish the report despite the problems.', ['managed to', 'could to', 'was able', 'manage'], 0, 'managed to = succeeded.'],
      ['Have you ever ___ speak in public?', ['could', 'been able to', 'able to', 'can'], 1, 'Perfect: been able to.'],
      ['He ___ swim when he was five.', ['could', 'was able', 'managed', 'can'], 0, 'General past ability: could.'],
      ['We ___ solve the problem yesterday.', ['were able to', 'could to', 'were able', 'can'], 0, 'Specific achievement: were able to.'],
      ['"Manage to" is followed by:', ['-ing', 'base verb', 'to-infinitive', 'past participle'], 2, 'manage to + verb.'],
      ['I’d like to ___ speak French.', ['can', 'be able to', 'could', 'able'], 1, 'After to: be able to.'],
      ['Did you ___ contact the supplier?', ['can', 'manage to', 'able to', 'could'], 1, 'Did you manage to.'],
    ],
    s: [
      ['I will can help you tomorrow.', false, 'I will be able to help you tomorrow.', 'Can has no future form.'],
      ['She managed to catch the last train.', true, null, 'Correct.'],
      ['They weren’t able to finish on time.', true, null, 'Correct.'],
      ['He managed finishing the project.', false, 'He managed to finish the project.', 'manage + to.'],
      ['We have been able to reduce costs.', true, null, 'Correct.'],
      ['I could to swim when I was a child.', false, 'I could swim when I was a child.', 'No to after could.'],
    ],
  },
  'Question Tags': {
    q: [
      ['You’re from Cali, ___?', ['are you', 'aren’t you', 'you are', 'isn’t it'], 1, 'Positive → negative tag.'],
      ['She doesn’t like coffee, ___?', ['does she', 'doesn’t she', 'is she', 'did she'], 0, 'Negative → positive tag.'],
      ['They worked late, ___?', ['did they', 'didn’t they', 'don’t they', 'weren’t they'], 1, 'Past simple: didn’t they.'],
      ['He can drive, ___?', ['can he', 'can’t he', 'does he', 'isn’t he'], 1, 'Modal repeated.'],
      ['I’m late, ___?', ['am I not', 'aren’t I', 'amn’t I', 'isn’t I'], 1, 'I’m → aren’t I.'],
      ['Let’s go, ___?', ['shall we', 'will we', 'don’t we', 'let we'], 0, 'Let’s → shall we.'],
      ['Close the door, ___?', ['do you', 'will you', 'don’t you', 'are you'], 1, 'Imperative → will you.'],
      ['You have finished, ___?', ['have you', 'haven’t you', 'did you', 'don’t you'], 1, 'Present perfect: haven’t you.'],
    ],
    s: [
      ['It’s cold today, isn’t it?', true, null, 'Correct.'],
      ['You like pizza, don’t you?', true, null, 'Correct.'],
      ['She is a teacher, isn’t it?', false, 'She is a teacher, isn’t she?', 'Tag repeats the subject.'],
      ['They didn’t come, did they?', true, null, 'Correct.'],
      ['He works here, isn’t he?', false, 'He works here, doesn’t he?', 'Tag matches the auxiliary.'],
      ['We should leave now, shouldn’t we?', true, null, 'Correct.'],
    ],
  },
  'Review: Meetings & Requests': {
    q: [
      ['Polite request:', ['Give me the file.', 'Could you send me the file, please?', 'Send the file.', 'You send file now.'], 1, 'Could you… please?'],
      ['"Let’s ___ started."', ['get', 'to get', 'getting', 'got'], 0, 'Let’s get started.'],
      ['To interrupt politely:', ['Shut up.', 'Sorry to interrupt, but…', 'Stop talking.', 'Me now.'], 1, 'Sorry to interrupt.'],
      ['"Could we ___ the deadline?"', ['move', 'moving', 'to move', 'moved'], 0, 'Could we + base verb.'],
      ['To agree:', ['I disagree.', 'That’s a good point.', 'No way.', 'Whatever.'], 1, 'Agreement phrase.'],
      ['"I’m afraid I ___ agree."', ['not', 'don’t', 'no', 'doesn’t'], 1, 'I’m afraid I don’t agree.'],
      ['Ending a meeting:', ['Let’s wrap up.', 'Let’s start.', 'Let’s open.', 'Let’s begin.'], 0, 'wrap up = finish.'],
      ['"Would you mind ___ the report again?"', ['check', 'to check', 'checking', 'checked'], 2, 'mind + -ing.'],
    ],
    s: [
      ['Can you to help me with this?', false, 'Can you help me with this?', 'No to after can.'],
      ['Shall we move on to the next point?', true, null, 'Correct.'],
      ['I’d appreciate if you could reply today.', false, 'I’d appreciate it if you could reply today.', 'appreciate IT.'],
      ['Let’s schedule a follow-up meeting.', true, null, 'Correct.'],
      ['Could you explain me the process?', false, 'Could you explain the process to me?', 'explain something TO someone.'],
      ['Thanks everyone for coming.', true, null, 'Correct.'],
    ],
  },
}
