export default {
  'Present Perfect vs Past Simple': {
    q: [
      ['I ___ in this company since 2020.', ['worked', 'have worked', 'work', 'was working'], 1, 'Unfinished period: present perfect.'],
      ['She ___ the client yesterday.', ['has called', 'called', 'has been calling', 'calls'], 1, 'Finished time (yesterday): past simple.'],
      ['___ you ever ___ to Japan?', ['Did / go', 'Have / been', 'Have / went', 'Did / been'], 1, 'Life experience: Have you ever been.'],
      ['We ___ three new products this year.', ['launched', 'have launched', 'launch', 'were launching'], 1, 'This year is still unfinished.'],
      ['He ___ the report last night.', ['has finished', 'finished', 'has finish', 'finishes'], 1, 'Finished time.'],
      ['I ___ my keys! I can’t open the door.', ['lost', 'have lost', 'lose', 'was losing'], 1, 'Present result: have lost.'],
      ['When ___ you ___ the contract?', ['have / signed', 'did / sign', 'did / signed', 'have / sign'], 1, 'When + past simple.'],
      ['They ___ here for ten years.', ['lived', 'have lived', 'live', 'are living'], 1, 'for + present perfect (still true).'],
    ],
    s: [
      ['I have seen him yesterday.', false, 'I saw him yesterday.', 'Finished time: past simple.'],
      ['She has just left the office.', true, null, 'Recent past: just.'],
      ['We have finished the project last week.', false, 'We finished the project last week.', 'Last week: past simple.'],
      ['Have you ever worked abroad?', true, null, 'Correct.'],
      ['He didn’t call me yet.', false, 'He hasn’t called me yet.', 'Yet → present perfect.'],
      ['I’ve known her since university.', true, null, 'Correct.'],
    ],
  },
  'Present Perfect Continuous': {
    q: [
      ['I ___ for the bus for 40 minutes!', ['wait', 'have been waiting', 'am waiting', 'waited'], 1, 'Duration up to now: have been + -ing.'],
      ['She ___ English for three years.', ['has been learning', 'is learning', 'learns', 'learned'], 0, 'Continuing action with duration.'],
      ['How long ___ you ___ here?', ['are / working', 'have / been working', 'do / work', 'did / work'], 1, 'How long have you been working.'],
      ['They ___ all morning. They look tired.', ['have been running', 'ran', 'run', 'are running'], 0, 'Recent activity with present result.'],
      ['It ___ since Monday.', ['rains', 'has been raining', 'is raining', 'rained'], 1, 'since + present perfect continuous.'],
      ['Which verb is NOT usually continuous?', ['work', 'play', 'know', 'wait'], 2, 'State verb: know.'],
      ['We ___ on this deal for weeks.', ['have been negotiating', 'negotiate', 'are negotiating', 'negotiated'], 0, 'Duration: for weeks.'],
      ['He ___ too much coffee lately.', ['drinks', 'has been drinking', 'drank', 'is drink'], 1, 'Lately → present perfect continuous.'],
    ],
    s: [
      ['I have been knowing him for years.', false, 'I have known him for years.', 'Know is a state verb.'],
      ['We have been working on this since 8 a.m.', true, null, 'Correct.'],
      ['She has been study all day.', false, 'She has been studying all day.', '-ing form.'],
      ['How long have you been living in Cali?', true, null, 'Correct.'],
      ['They are waiting for two hours.', false, 'They have been waiting for two hours.', 'Duration up to now.'],
      ['It has been snowing all night.', true, null, 'Correct.'],
    ],
  },
  'For / Since / Ago': {
    q: [
      ['I have lived here ___ 2015.', ['for', 'since', 'ago', 'during'], 1, 'Starting point: since.'],
      ['She has worked here ___ six months.', ['for', 'since', 'ago', 'from'], 0, 'Duration: for.'],
      ['We moved to Cali two years ___.', ['for', 'since', 'ago', 'before'], 2, 'Past simple + ago.'],
      ['He has been ill ___ Monday.', ['for', 'since', 'ago', 'at'], 1, 'Since + day.'],
      ['"Ago" is used with:', ['present perfect', 'past simple', 'present simple', 'future'], 1, 'Ago → past simple.'],
      ['They have been married ___ a long time.', ['since', 'for', 'ago', 'during'], 1, 'for + period.'],
      ['I haven’t seen her ___ last Christmas.', ['for', 'since', 'ago', 'from'], 1, 'since + point in time.'],
      ['The meeting started ten minutes ___.', ['since', 'for', 'ago', 'before'], 2, 'ago.'],
    ],
    s: [
      ['I have known him since three years.', false, 'I have known him for three years.', 'Duration: for.'],
      ['She left five minutes ago.', true, null, 'Correct.'],
      ['We have been here since yesterday.', true, null, 'Correct.'],
      ['He has lived in Spain for 2010.', false, 'He has lived in Spain since 2010.', 'Starting point: since.'],
      ['They have finished the project two days ago.', false, 'They finished the project two days ago.', 'Ago → past simple.'],
      ['I’ve worked here for ten years.', true, null, 'Correct.'],
    ],
  },
  'Past Perfect': {
    q: [
      ['When I arrived, the meeting ___.', ['started', 'had started', 'has started', 'was starting'], 1, 'Earlier past action: had started.'],
      ['She ___ the email before the boss asked.', ['sent', 'had sent', 'has sent', 'was sending'], 1, 'Action before another past action.'],
      ['By 2019, the company ___ 50 stores.', ['opened', 'had opened', 'has opened', 'opens'], 1, 'By + past time → past perfect.'],
      ['I didn’t recognise him because he ___ a lot.', ['changed', 'had changed', 'has changed', 'was changing'], 1, 'Cause before the past moment.'],
      ['Past participle of "drink":', ['drank', 'drunk', 'drinked', 'drinking'], 1, 'drink – drank – drunk.'],
      ['___ you ever ___ sushi before that trip?', ['Did / eat', 'Had / eaten', 'Have / eaten', 'Had / ate'], 1, 'Had you ever eaten.'],
      ['After they ___ dinner, they watched a film.', ['had had', 'have had', 'had', 'were having'], 0, 'had had (have in past perfect).'],
      ['We were late because we ___ the bus.', ['missed', 'had missed', 'have missed', 'miss'], 1, 'Reason earlier in the past.'],
    ],
    s: [
      ['When we got to the cinema, the film had already started.', true, null, 'Correct.'],
      ['She had went home before the party ended.', false, 'She had gone home before the party ended.', 'Participle: gone.'],
      ['I had never see snow before I moved to Canada.', false, 'I had never seen snow before I moved to Canada.', 'Participle: seen.'],
      ['He realised he had forgotten his passport.', true, null, 'Correct.'],
      ['By the time you called, I have finished.', false, 'By the time you called, I had finished.', 'Past perfect.'],
      ['They had lived in Peru before they came here.', true, null, 'Correct.'],
    ],
  },
  'Narrative Tenses': {
    q: [
      ['It ___ heavily when we left the office.', ['rained', 'was raining', 'had rained', 'rains'], 1, 'Background: past continuous.'],
      ['She ___ the door, ___ in and ___ down.', ['opened / walked / sat', 'was opening / walking / sitting', 'had opened / walked / sat', 'opens / walks / sits'], 0, 'Sequence: past simple.'],
      ['He was nervous because he ___ never ___ a presentation before.', ['did / give', 'had / given', 'has / given', 'was / giving'], 1, 'Earlier past: past perfect.'],
      ['While I ___, someone ___ my laptop.', ['slept / stole', 'was sleeping / stole', 'was sleeping / was stealing', 'had slept / stole'], 1, 'Background + event.'],
      ['Which tense is for the main events of a story?', ['past continuous', 'past simple', 'past perfect', 'present perfect'], 1, 'Main events: past simple.'],
      ['By the time the police arrived, the thief ___.', ['escaped', 'was escaping', 'had escaped', 'escapes'], 2, 'Completed before.'],
      ['We ___ TV when the news ___.', ['watched / was breaking', 'were watching / broke', 'had watched / broke', 'watch / broke'], 1, 'Interrupted action.'],
      ['I ___ for two hours when she finally called.', ['waited', 'had been waiting', 'was waiting', 'have been waiting'], 1, 'Duration before past event: past perfect continuous.'],
    ],
    s: [
      ['Yesterday I was waking up late and missed the bus.', false, 'Yesterday I woke up late and missed the bus.', 'Events: past simple.'],
      ['The sun was shining and the birds were singing.', true, null, 'Background description.'],
      ['When I got home, my wife had already cooked dinner.', true, null, 'Correct.'],
      ['He had been working there for a year when he was promoted.', true, null, 'Correct.'],
      ['I was knowing something was wrong.', false, 'I knew something was wrong.', 'Know is a state verb.'],
      ['After she left, I was realising my mistake.', false, 'After she left, I realised my mistake.', 'Event: past simple.'],
    ],
  },
  'Third Conditional': {
    q: [
      ['If I ___ harder, I would have passed.', ['studied', 'had studied', 'have studied', 'would study'], 1, 'if + past perfect.'],
      ['If we had left earlier, we ___ the flight.', ['caught', 'would catch', 'would have caught', 'had caught'], 2, 'would have + participle.'],
      ['She ___ the job if she had prepared for the interview.', ['would get', 'would have got', 'got', 'had got'], 1, 'Unreal past result.'],
      ['The third conditional talks about:', ['real future', 'imaginary present', 'imaginary past (regrets)', 'habits'], 2, 'Hypothetical past.'],
      ['If you ___ me, I would have helped.', ['called', 'had called', 'would call', 'have called'], 1, 'had called.'],
      ['I wouldn’t have been late if the bus ___ on time.', ['came', 'had come', 'would come', 'has come'], 1, 'had come.'],
      ['"Would’ve" is short for:', ['would have', 'would of', 'will have', 'would be'], 0, 'would’ve = would have.'],
      ['If they hadn’t invested, the company ___.', ['failed', 'would fail', 'would have failed', 'had failed'], 2, 'would have failed.'],
    ],
    s: [
      ['If I would have known, I would have come.', false, 'If I had known, I would have come.', 'No would in the if-clause.'],
      ['If she had studied, she would have passed.', true, null, 'Correct.'],
      ['We would have won if we had played better.', true, null, 'Correct.'],
      ['If he had took the job, he would be rich now.', false, 'If he had taken the job, he would be rich now.', 'Participle: taken (mixed conditional ok).'],
      ['If they hadn’t helped us, we would of failed.', false, 'If they hadn’t helped us, we would have failed.', '"would of" is wrong: would have.'],
      ['I wouldn’t have called if it hadn’t been urgent.', true, null, 'Correct.'],
    ],
  },
  'Mixed Conditionals': {
    q: [
      ['If I had accepted the offer, I ___ in London now.', ['would be', 'would have been', 'am', 'was'], 0, 'Past condition, present result.'],
      ['If she ___ so shy, she would have spoken at the meeting.', ['isn’t', 'weren’t', 'hadn’t been', 'won’t be'], 1, 'Present state, past result.'],
      ['If we hadn’t missed the train, we ___ home by now.', ['were', 'would be', 'would have been', 'are'], 1, 'Past condition, present result.'],
      ['If I were taller, I ___ the basketball team last year.', ['would join', 'would have joined', 'joined', 'had joined'], 1, 'Present condition, past result.'],
      ['A mixed conditional combines:', ['two zero conditionals', 'a second and a third conditional', 'first and zero', 'only past tenses'], 1, 'Types 2 and 3.'],
      ['If he ___ his phone, he wouldn’t be so stressed now.', ['didn’t lose', 'hadn’t lost', 'doesn’t lose', 'wouldn’t lose'], 1, 'Past condition.'],
      ['If I ___ you, I wouldn’t have said that.', ['was', 'were', 'had been', 'am'], 1, 'Present hypothetical identity.'],
      ['If they lived closer, they ___ to the party last night.', ['would come', 'would have come', 'came', 'come'], 1, 'Past result.'],
    ],
    s: [
      ['If I had saved money, I would be able to buy a car now.', true, null, 'Correct mixed conditional.'],
      ['If she wasn’t so busy, she would have come yesterday.', true, null, 'Accepted (was/were).'],
      ['If I had listened to you, I wouldn’t have this problem now.', true, null, 'Correct.'],
      ['If he would have studied, he would have a better job now.', false, 'If he had studied, he would have a better job now.', 'No would in the if-clause.'],
      ['If we didn’t have a car, we would have took the bus.', false, 'If we didn’t have a car, we would have taken the bus.', 'Participle: taken.'],
      ['If I were rich, I would had bought that house.', false, 'If I were rich, I would have bought that house.', 'would have + participle.'],
    ],
  },
  'Wish / If only': {
    q: [
      ['I wish I ___ more free time.', ['have', 'had', 'will have', 'would have'], 1, 'Present wish: past simple.'],
      ['She wishes she ___ that email.', ['didn’t send', 'hadn’t sent', 'doesn’t send', 'wouldn’t send'], 1, 'Past regret: past perfect.'],
      ['I wish you ___ stop interrupting!', ['will', 'would', 'did', 'had'], 1, 'Annoying behaviour: wish + would.'],
      ['If only I ___ speak Chinese.', ['can', 'could', 'will', 'would'], 1, 'Present ability wish: could.'],
      ['"If only" is similar to:', ['I hope', 'I wish', 'I think', 'I want to'], 1, 'Strong wish.'],
      ['We wish we ___ in a warmer city.', ['live', 'lived', 'will live', 'have lived'], 1, 'Present wish.'],
      ['I wish I ___ that job.', ['took', 'had taken', 'take', 'would take'], 1, 'Past regret.'],
      ['I wish it ___ raining.', ['would stop', 'stops', 'stopped', 'will stop'], 0, 'Wish about a change: would.'],
    ],
    s: [
      ['I wish I have a bigger apartment.', false, 'I wish I had a bigger apartment.', 'Past simple after wish.'],
      ['She wishes she hadn’t said that.', true, null, 'Correct.'],
      ['I wish I would be taller.', false, 'I wish I were taller.', 'Don’t use would for yourself.'],
      ['If only we had more time!', true, null, 'Correct.'],
      ['I wish he would call me back.', true, null, 'Correct.'],
      ['They wish they didn’t sell the house last year.', false, 'They wish they hadn’t sold the house last year.', 'Past regret: past perfect.'],
    ],
  },
  'Modals of Deduction (must / might / can’t)': {
    q: [
      ['The lights are on. Someone ___ be home.', ['must', 'can’t', 'might not', 'should'], 0, 'Sure it’s true: must.'],
      ['He ___ be at work; I saw him at the beach!', ['must', 'can’t', 'might', 'may'], 1, 'Sure it’s impossible: can’t.'],
      ['She ___ be in a meeting, but I’m not sure.', ['must', 'can’t', 'might', 'has to'], 2, 'Possible: might.'],
      ['The opposite of "must be" (deduction) is:', ['mustn’t be', 'can’t be', 'might be', 'don’t have to be'], 1, 'can’t be.'],
      ['That ___ be John’s car; he doesn’t drive.', ['must', 'can’t', 'may', 'could'], 1, 'Impossible: can’t.'],
      ['You’ve worked 12 hours. You ___ be exhausted.', ['can’t', 'must', 'might', 'may not'], 1, 'Logical certainty: must.'],
      ['It ___ rain later; the forecast is unclear.', ['must', 'can’t', 'could', 'has to'], 2, 'Possibility: could.'],
      ['Which expresses 50% certainty?', ['must', 'can’t', 'may', 'has to'], 2, 'may/might/could.'],
    ],
    s: [
      ['She mustn’t be at home; her car isn’t there.', false, 'She can’t be at home; her car isn’t there.', 'Negative deduction: can’t.'],
      ['They must be tired after the trip.', true, null, 'Correct.'],
      ['He might be in the cafeteria.', true, null, 'Correct.'],
      ['It can be his birthday today; he brought cake.', false, 'It must be his birthday today; he brought cake.', '"Can" isn’t used for specific deductions.'],
      ['You can’t be serious!', true, null, 'Correct.'],
      ['She may be the new manager.', true, null, 'Correct.'],
    ],
  },
  'Modals in the Past': {
    q: [
      ['He’s late. He ___ the bus.', ['must miss', 'must have missed', 'must missed', 'can’t have miss'], 1, 'Past deduction: must have + participle.'],
      ['You ___ told me! Now it’s too late.', ['should have', 'must have', 'might have', 'could'], 0, 'Past criticism: should have.'],
      ['She ___ the email; her inbox was full.', ['can’t receive', 'might not have received', 'mustn’t have received', 'shouldn’t receive'], 1, 'Possibility in the past.'],
      ['They ___ left already; the lights are off.', ['must have', 'should', 'can’t', 'have to'], 0, 'must have left.'],
      ['I ___ gone to the party, but I stayed home.', ['could have', 'must have', 'can’t have', 'should'], 0, 'Unused possibility: could have.'],
      ['He ___ seen us; he was in another city.', ['must have', 'can’t have', 'should have', 'may have'], 1, 'Impossible past: can’t have.'],
      ['"Needn’t have done" means:', ['it was necessary', 'you did it but it wasn’t necessary', 'you didn’t do it', 'you must do it'], 1, 'Unnecessary action done.'],
      ['We ___ so much money on that trip.', ['shouldn’t have spent', 'mustn’t have spent', 'can’t spend', 'shouldn’t spend'], 0, 'Regret: shouldn’t have.'],
    ],
    s: [
      ['You should have call me earlier.', false, 'You should have called me earlier.', 'have + participle.'],
      ['She must have forgotten the meeting.', true, null, 'Correct.'],
      ['They can’t have finished already!', true, null, 'Correct.'],
      ['He might had lost his phone.', false, 'He might have lost his phone.', 'might have.'],
      ['I could have been a doctor.', true, null, 'Correct.'],
      ['We mustn’t have taken the wrong road.', false, 'We must have taken the wrong road.', 'mustn’t isn’t used for deduction.'],
    ],
  },
  'Reported Speech: Questions': {
    q: [
      ['"Where do you live?" → He asked me where I ___.', ['live', 'lived', 'do live', 'did live'], 1, 'Tense back, no auxiliary.'],
      ['"Are you busy?" → She asked ___ I was busy.', ['that', 'if', 'what', 'do'], 1, 'Yes/no question: if/whether.'],
      ['"What time is it?" → He asked what time ___.', ['is it', 'it is', 'it was', 'was it'], 2, 'Statement order + tense back.'],
      ['"Did you finish?" → They asked if I ___.', ['finished', 'had finished', 'have finished', 'did finish'], 1, 'Past simple → past perfect.'],
      ['"Can you help?" → She asked if I ___ help.', ['can', 'could', 'may', 'will'], 1, 'can → could.'],
      ['In reported questions we ___ use a question mark.', ['always', 'don’t', 'sometimes', 'must'], 1, 'No question mark.'],
      ['"Why are you late?" → He wanted to know why I ___ late.', ['am', 'was', 'were', 'be'], 1, 'am → was.'],
      ['"Will you come?" → He asked ___ I would come.', ['whether', 'that', 'what', 'will'], 0, 'whether/if.'],
    ],
    s: [
      ['She asked me where did I work.', false, 'She asked me where I worked.', 'No inversion in reported questions.'],
      ['He asked if I could send the file.', true, null, 'Correct.'],
      ['They asked me what I was doing.', true, null, 'Correct.'],
      ['I asked her that she was ready.', false, 'I asked her if she was ready.', 'Yes/no: if.'],
      ['He asked how much it cost?', false, 'He asked how much it cost.', 'No question mark.'],
      ['The manager asked why we had missed the deadline.', true, null, 'Correct.'],
    ],
  },
  'Reported Speech: Commands': {
    q: [
      ['"Close the door." → He told me ___ the door.', ['close', 'to close', 'closing', 'that close'], 1, 'tell + object + to-infinitive.'],
      ['"Don’t be late." → She told us ___ late.', ['don’t be', 'to not be', 'not to be', 'not be'], 2, 'not to + verb.'],
      ['"Please sit down." → He asked me ___.', ['sit down', 'to sit down', 'sitting down', 'that I sit'], 1, 'ask + to.'],
      ['"Wait here!" → The guard ___ us to wait there.', ['said', 'ordered', 'told to', 'asked that'], 1, 'ordered + object + to.'],
      ['Which verb needs an object before "to"?', ['say', 'tell', 'suggest', 'think'], 1, 'tell someone to.'],
      ['"Turn off your phones." → The teacher told the students ___ their phones.', ['turn off', 'to turn off', 'turning off', 'that turn off'], 1, 'to turn off.'],
      ['"Don’t touch that." → She warned him ___ that.', ['don’t touch', 'not to touch', 'to not touching', 'no touch'], 1, 'warn + not to.'],
      ['"Could you help me?" → He asked me ___ him.', ['help', 'to help', 'helping', 'that help'], 1, 'to help.'],
    ],
    s: [
      ['He told me to don’t worry.', false, 'He told me not to worry.', 'not to + verb.'],
      ['She asked us to be quiet.', true, null, 'Correct.'],
      ['The boss said me to finish early.', false, 'The boss told me to finish early.', 'tell + object.'],
      ['They told him to wait outside.', true, null, 'Correct.'],
      ['My doctor advised me to rest.', true, null, 'Correct.'],
      ['She ordered that we leaving immediately.', false, 'She ordered us to leave immediately.', 'order + object + to.'],
    ],
  },
  'Passive Voice: All Tenses': {
    q: [
      ['The report ___ right now.', ['is written', 'is being written', 'is writing', 'writes'], 1, 'Present continuous passive.'],
      ['The new office ___ by next year.', ['will build', 'will be built', 'is built', 'builds'], 1, 'Future passive.'],
      ['The decision ___ already ___.', ['has / made', 'has / been made', 'is / made', 'was / making'], 1, 'Present perfect passive.'],
      ['The road ___ when the accident happened.', ['was repairing', 'was being repaired', 'is repaired', 'repaired'], 1, 'Past continuous passive.'],
      ['This problem ___ be solved soon.', ['must', 'must to', 'is', 'has'], 0, 'Modal passive: must be solved.'],
      ['The contract ___ before the meeting started.', ['had signed', 'had been signed', 'was signing', 'has been signed'], 1, 'Past perfect passive.'],
      ['Which is the passive of "They are going to open a store"?', ['A store is going to open.', 'A store is going to be opened.', 'A store will open.', 'A store opens.'], 1, 'going to be + participle.'],
      ['Passive infinitive of "do":', ['to do', 'to be done', 'to done', 'being done'], 1, 'to be done.'],
    ],
    s: [
      ['The invoices are being process now.', false, 'The invoices are being processed now.', 'Participle: processed.'],
      ['The results will be announced tomorrow.', true, null, 'Correct.'],
      ['The car has been repaired.', true, null, 'Correct.'],
      ['The letter was be sent yesterday.', false, 'The letter was sent yesterday.', 'Only one be.'],
      ['The rules should be followed by everyone.', true, null, 'Correct.'],
      ['The cake had eaten before I arrived.', false, 'The cake had been eaten before I arrived.', 'had been + participle.'],
    ],
  },
  'Causative: Have / Get Something Done': {
    q: [
      ['I ___ my car ___ yesterday.', ['had / repaired', 'had / repair', 'have / repairing', 'got / repair'], 0, 'have + object + participle.'],
      ['She is going to ___ her hair cut.', ['make', 'have', 'do', 'be'], 1, 'have her hair cut.'],
      ['We need to ___ the printer fixed.', ['get', 'do', 'make', 'be'], 0, 'get + object + participle.'],
      ['"I had my house painted" means:', ['I painted it', 'Someone painted it for me', 'I will paint it', 'I painted someone’s house'], 1, 'Someone else did it.'],
      ['He ___ his teeth checked twice a year.', ['has', 'makes', 'does', 'gets checked'], 0, 'has his teeth checked.'],
      ['They ___ a new logo designed last month.', ['had', 'have had', 'made', 'did'], 0, 'had + object + participle.'],
      ['I’ll ___ my assistant call you.', ['have', 'get', 'make to', 'let to'], 0, 'have someone do (base form).'],
      ['She ___ him to fix the bug.', ['had', 'got', 'made', 'let'], 1, 'get someone TO do.'],
    ],
    s: [
      ['I had my phone repair last week.', false, 'I had my phone repaired last week.', 'Participle: repaired.'],
      ['We got the office cleaned before the visit.', true, null, 'Correct.'],
      ['She had cut her hair yesterday.', false, 'She had her hair cut yesterday.', 'Someone else cut it: causative.'],
      ['They are having a new website built.', true, null, 'Correct.'],
      ['I need to get my eyes tested.', true, null, 'Correct.'],
      ['He made the mechanic to check the car.', false, 'He got the mechanic to check the car.', 'make + base; get + to.'],
    ],
  },
  'Gerunds & Infinitives II': {
    q: [
      ['I stopped ___ coffee; it was bad for me.', ['drink', 'drinking', 'to drink', 'drank'], 1, 'stop + -ing = quit the activity.'],
      ['We stopped ___ a coffee on the way.', ['have', 'having', 'to have', 'had'], 2, 'stop + to = pause in order to.'],
      ['Remember ___ the door when you leave.', ['lock', 'locking', 'to lock', 'locked'], 2, 'remember + to = don’t forget (future).'],
      ['I remember ___ the door. I’m sure.', ['lock', 'locking', 'to lock', 'locked'], 1, 'remember + -ing = memory of the past.'],
      ['She tried ___ the window, but it was stuck.', ['open', 'opening', 'to open', 'opened'], 2, 'try + to = attempt.'],
      ['I forgot ___ the report. Sorry!', ['send', 'sending', 'to send', 'sent'], 2, 'forget + to = didn’t do it.'],
      ['He went on ___ for two hours.', ['talk', 'talking', 'to talk', 'talked'], 1, 'go on + -ing = continue.'],
      ['I regret ___ you that the position is filled.', ['tell', 'telling', 'to tell', 'told'], 2, 'regret + to inform (formal).'],
    ],
    s: [
      ['I’ll never forget meeting the president.', true, null, 'Memory: -ing.'],
      ['Please remember sending the invoice tomorrow.', false, 'Please remember to send the invoice tomorrow.', 'Future duty: to.'],
      ['She stopped to smoke last year.', false, 'She stopped smoking last year.', 'Quit: -ing.'],
      ['Try restarting the computer.', true, null, 'Experiment: -ing.'],
      ['He regrets not studying harder.', true, null, 'Regret about the past: -ing.'],
      ['We stopped having lunch at a café by the road.', false, 'We stopped to have lunch at a café by the road.', 'Pause in order to: to.'],
    ],
  },
  'Verb Patterns': {
    q: [
      ['My boss made me ___ late.', ['stay', 'to stay', 'staying', 'stayed'], 0, 'make + object + base verb.'],
      ['They let us ___ early on Fridays.', ['leave', 'to leave', 'leaving', 'left'], 0, 'let + object + base verb.'],
      ['She helped me ___ the presentation.', ['prepare', 'to prepare', 'Both are correct', 'preparing'], 2, 'help + (to) infinitive.'],
      ['I want you ___ this today.', ['finish', 'to finish', 'finishing', 'finished'], 1, 'want + object + to.'],
      ['He advised me ___ a lawyer.', ['see', 'to see', 'seeing', 'saw'], 1, 'advise + object + to.'],
      ['They suggested ___ a break.', ['take', 'to take', 'taking', 'took'], 2, 'suggest + -ing.'],
      ['I saw him ___ the building.', ['leave', 'to leave', 'Both are correct', 'left'], 0, 'see + object + base (or -ing).'],
      ['We expect sales ___.', ['rise', 'to rise', 'rising', 'rose'], 1, 'expect + object + to.'],
    ],
    s: [
      ['She made me to cry.', false, 'She made me cry.', 'make + base verb.'],
      ['Let me help you with that.', true, null, 'Correct.'],
      ['I suggested him to see a doctor.', false, 'I suggested that he see a doctor.', 'suggest + that / -ing.'],
      ['They allowed us to park here.', true, null, 'allow + object + to.'],
      ['He encouraged me to apply.', true, null, 'Correct.'],
      ['We heard them to argue.', false, 'We heard them arguing.', 'hear + object + -ing/base.'],
    ],
  },
  'Defining vs Non-defining Relative Clauses': {
    q: [
      ['My brother, ___ lives in Madrid, is a doctor.', ['that', 'who', 'which', 'whom'], 1, 'Non-defining: who (not that).'],
      ['Non-defining clauses are separated by:', ['nothing', 'commas', 'brackets only', 'colons'], 1, 'Commas.'],
      ['The man ___ sold me the car was honest.', ['who', 'which', 'whose', 'where'], 0, 'Defining: who/that.'],
      ['Our office, ___ is in the centre, has 50 people.', ['that', 'which', 'where', 'who'], 1, 'Non-defining: which.'],
      ['In which type can you use "that"?', ['defining only', 'non-defining only', 'both', 'neither'], 0, 'That only in defining clauses.'],
      ['The product ___ we launched last year is a success.', ['that', 'who', 'whose', 'Both that and which'], 3, 'Defining: that/which.'],
      ['Cali, ___ I was born, is famous for salsa.', ['which', 'where', 'that', 'who'], 1, 'Place: where.'],
      ['When can you omit the relative pronoun?', ['when it is the subject', 'when it is the object in a defining clause', 'always', 'never'], 1, 'Object of defining clause.'],
    ],
    s: [
      ['My boss, that is from Spain, speaks four languages.', false, 'My boss, who is from Spain, speaks four languages.', 'Non-defining: who.'],
      ['The book that you lent me was great.', true, null, 'Correct.'],
      ['Paris, which is the capital of France, is beautiful.', true, null, 'Correct.'],
      ['The people who work here they are friendly.', false, 'The people who work here are friendly.', 'No extra subject pronoun.'],
      ['The car I bought is red.', true, null, 'Omitted object pronoun.'],
      ['My sister who lives in Miami is visiting.', false, 'My sister, who lives in Miami, is visiting.', 'If you have one sister: commas.'],
    ],
  },
  'Phrasal Verbs II': {
    q: [
      ['We need to ___ a solution quickly.', ['come up with', 'come up', 'come across', 'come out'], 0, 'come up with = think of.'],
      ['I ___ an old friend at the airport.', ['ran into', 'ran out', 'ran over', 'ran away'], 0, 'run into = meet by chance.'],
      ['Can we ___ the meeting to Friday?', ['put off', 'put on', 'put up', 'put out'], 0, 'put off = postpone.'],
      ['She ___ a great idea during the meeting.', ['came across', 'brought up', 'broke down', 'took off'], 1, 'bring up = mention.'],
      ['The company ___ 20 people last month.', ['laid off', 'laid out', 'laid down', 'laid up'], 0, 'lay off = dismiss.'],
      ['The new product really ___.', ['took off', 'took out', 'took over', 'took in'], 0, 'take off = become successful.'],
      ['Our car ___ on the motorway.', ['broke up', 'broke down', 'broke in', 'broke out'], 1, 'break down = stop working.'],
      ['I need to ___ the numbers before the meeting.', ['go over', 'go out', 'go off', 'go by'], 0, 'go over = review.'],
    ],
    s: [
      ['Let’s put off the decision until Monday.', true, null, 'Correct.'],
      ['I came up an idea.', false, 'I came up with an idea.', 'come up WITH.'],
      ['She turned down the offer.', true, null, 'Correct.'],
      ['He gave up to smoke.', false, 'He gave up smoking.', 'give up + -ing.'],
      ['We ran out of paper.', true, null, 'Correct.'],
      ['Can you look after to my dog?', false, 'Can you look after my dog?', 'No "to".'],
    ],
  },
  'Linking Words: Contrast': {
    q: [
      ['___ it was raining, we went for a walk.', ['Although', 'However', 'Despite', 'But'], 0, 'Although + clause.'],
      ['The hotel was expensive. ___, the service was poor.', ['Although', 'However', 'Despite', 'Whereas'], 1, 'However starts a new sentence.'],
      ['___ the rain, the event was a success.', ['Although', 'Despite', 'However', 'Even though'], 1, 'Despite + noun.'],
      ['She is very rich, ___ she is unhappy.', ['despite', 'but', 'in spite', 'although'], 1, 'but joins clauses.'],
      ['"In spite of" is followed by:', ['a clause', 'a noun or -ing', 'will', 'a full sentence with subject and verb'], 1, 'Noun / gerund.'],
      ['I like tea ___ my wife prefers coffee.', ['whereas', 'despite', 'however', 'in spite of'], 0, 'whereas = contrast between two.'],
      ['___ being tired, he finished the report.', ['Although', 'Despite', 'However', 'But'], 1, 'Despite + -ing.'],
      ['"Nevertheless" is similar to:', ['because', 'however', 'therefore', 'so'], 1, 'Contrast.'],
    ],
    s: [
      ['Despite it was late, we continued working.', false, 'Although it was late, we continued working.', 'Despite + noun/-ing, not a clause.'],
      ['Although the price was high, we bought it.', true, null, 'Correct.'],
      ['In spite of the traffic, I arrived on time.', true, null, 'Correct.'],
      ['He is a good manager, however, he is often late.', false, 'He is a good manager. However, he is often late.', 'However needs a new sentence or semicolon.'],
      ['Even though she studied, she failed.', true, null, 'Correct.'],
      ['Despite of the cold, we went out.', false, 'Despite the cold, we went out.', 'No "of" after despite.'],
    ],
  },
  'Linking Words: Cause & Result': {
    q: [
      ['We stayed home ___ the storm.', ['because', 'because of', 'so', 'therefore'], 1, 'because of + noun.'],
      ['It was late, ___ we took a taxi.', ['because', 'so', 'due to', 'since'], 1, 'Result: so.'],
      ['The flight was cancelled ___ bad weather.', ['because', 'due to', 'so', 'as a result'], 1, 'due to + noun.'],
      ['Sales fell. ___, we reduced costs.', ['Because', 'As a result', 'Due to', 'Since'], 1, 'As a result starts a new sentence.'],
      ['___ he was ill, he didn’t come.', ['So', 'Since', 'Therefore', 'Due to'], 1, 'Since = because.'],
      ['"Therefore" expresses:', ['cause', 'result', 'contrast', 'time'], 1, 'Result.'],
      ['I was tired ___ I went to bed early.', ['because', 'so', 'because of', 'due to'], 1, 'Result: so.'],
      ['___ the high demand, prices rose.', ['Because', 'Owing to', 'So', 'Therefore'], 1, 'Owing to + noun.'],
    ],
    s: [
      ['We cancelled the trip because of it was raining.', false, 'We cancelled the trip because it was raining.', 'because + clause.'],
      ['She was promoted because she worked hard.', true, null, 'Correct.'],
      ['The road was closed due to an accident.', true, null, 'Correct.'],
      ['He didn’t study, therefore he failed.', false, 'He didn’t study; therefore, he failed.', 'Therefore needs a semicolon or new sentence.'],
      ['It was raining, so we stayed indoors.', true, null, 'Correct.'],
      ['Because the traffic, I was late.', false, 'Because of the traffic, I was late.', 'because of + noun.'],
    ],
  },
  'Articles: Advanced Uses': {
    q: [
      ['___ Amazon is the longest river in South America.', ['A', 'An', 'The', '—'], 2, 'Rivers take the.'],
      ['She plays ___ guitar.', ['a', 'an', 'the', '—'], 2, 'Instruments: the.'],
      ['I went to ___ bed at 11.', ['a', 'an', 'the', '—'], 3, 'Fixed expression: go to bed.'],
      ['___ Netherlands is a flat country.', ['A', 'An', 'The', '—'], 2, 'Plural / "kingdom/republic"-type names: the.'],
      ['We travelled to ___ Mount Everest.', ['a', 'an', 'the', '—'], 3, 'Single mountains: no article.'],
      ['He is in ___ hospital; he broke his leg.', ['a', 'an', 'the', '—'], 3, 'British: in hospital (as a patient).'],
      ['___ rich should help ___ poor.', ['A / a', 'The / the', '— / —', 'The / a'], 1, 'the + adjective = group.'],
      ['I watch TV ___ once a week.', ['a', 'an', 'the', '—'], 3, 'No article in "once a week".'],
    ],
    s: [
      ['The breakfast is served at 7.', false, 'Breakfast is served at 7.', 'Meals: no article.'],
      ['The Pacific is the largest ocean.', true, null, 'Oceans: the.'],
      ['He is the best player in the team.', true, null, 'Superlative: the.'],
      ['I love the Italian food.', false, 'I love Italian food.', 'General: no article.'],
      ['We visited the Lake Titicaca.', false, 'We visited Lake Titicaca.', 'Lakes: no article.'],
      ['The United States has 50 states.', true, null, 'Correct.'],
    ],
  },
  'Future Continuous': {
    q: [
      ['At 10 tomorrow, I ___ a meeting.', ['will have', 'will be having', 'am having', 'have'], 1, 'In progress at a future time.'],
      ['This time next week, we ___ on the beach.', ['lie', 'will be lying', 'will lie', 'are lying'], 1, 'will be + -ing.'],
      ['Don’t call at 8; I ___.', ['will drive', 'will be driving', 'drive', 'am driving'], 1, 'Action in progress.'],
      ['___ you ___ the car this weekend?', ['Will / be using', 'Are / using', 'Do / use', 'Will / using'], 0, 'Polite question about plans.'],
      ['She ___ when you arrive.', ['sleeps', 'will be sleeping', 'will sleep', 'is sleeping'], 1, 'In progress when.'],
      ['The future continuous is formed with:', ['will + -ing', 'will be + -ing', 'be going to + -ing', 'will + have + -ing'], 1, 'will be + -ing.'],
      ['They ___ dinner at 8, so come at 9.', ['will have', 'will be having', 'have', 'had'], 1, 'In progress.'],
      ['Next year at this time, I ___ in Canada.', ['will be studying', 'study', 'will study', 'am studying'], 0, 'will be studying.'],
    ],
    s: [
      ['I will be work at 9 tomorrow.', false, 'I will be working at 9 tomorrow.', '-ing form.'],
      ['Will you be attending the conference?', true, null, 'Correct.'],
      ['At noon we will be having lunch.', true, null, 'Correct.'],
      ['She will being travelling next week.', false, 'She will be travelling next week.', 'will be, not being.'],
      ['They won’t be using the room this afternoon.', true, null, 'Correct.'],
      ['I will be to wait for you.', false, 'I will be waiting for you.', 'will be + -ing.'],
    ],
  },
  'Future Perfect': {
    q: [
      ['By 2030, we ___ 100 stores.', ['open', 'will have opened', 'will open', 'are opening'], 1, 'Completed before a future time.'],
      ['She ___ the report by Friday.', ['will finish', 'will have finished', 'finishes', 'has finished'], 1, 'by + future time → future perfect.'],
      ['By the time you arrive, I ___.', ['will leave', 'will have left', 'leave', 'am leaving'], 1, 'Completed before.'],
      ['The future perfect is formed with:', ['will + participle', 'will have + participle', 'will be + -ing', 'have + participle'], 1, 'will have + participle.'],
      ['Next month I ___ here for ten years.', ['will work', 'will have worked', 'work', 'will be working'], 1, 'Duration completed at future point.'],
      ['___ they ___ the project by June?', ['Will / have finished', 'Will / finish', 'Have / finished', 'Do / finish'], 0, 'Will they have finished.'],
      ['I ___ my degree by the end of the year.', ['will complete', 'will have completed', 'complete', 'completed'], 1, 'by the end of.'],
      ['"By then" signals:', ['future continuous', 'future perfect', 'present', 'past simple'], 1, 'Completion before a time.'],
    ],
    s: [
      ['By 5 p.m. I will finished the report.', false, 'By 5 p.m. I will have finished the report.', 'will have + participle.'],
      ['She will have graduated by next summer.', true, null, 'Correct.'],
      ['By the time we get there, the film will have started.', true, null, 'Correct.'],
      ['They will have leave before midnight.', false, 'They will have left before midnight.', 'Participle: left.'],
      ['In ten years, robots will have replaced many jobs.', true, null, 'Correct.'],
      ['I will have been here since two years by December.', false, 'I will have been here for two years by December.', 'Duration: for.'],
    ],
  },
  'Review: Negotiation Language': {
    q: [
      ['"We ___ willing to offer a 10% discount."', ['are', 'would be', 'Both are possible', 'will'], 2, 'Both are common in negotiations.'],
      ['To make a counter-offer:', ['Take it or leave it.', 'How about 15%?', 'No.', 'I don’t care.'], 1, 'How about…?'],
      ['"That’s a deal!" means:', ['I refuse', 'I agree', 'Let me think', 'Repeat please'], 1, 'Agreement.'],
      ['"If you order 500 units, we ___ free shipping."', ['include', 'will include', 'included', 'including'], 1, 'First conditional.'],
      ['Polite refusal:', ['No way.', 'I’m afraid we can’t accept that.', 'Are you crazy?', 'Never.'], 1, 'I’m afraid…'],
      ['"Let’s meet ___."', ['halfway', 'half road', 'the middle', 'centre'], 0, 'meet halfway = compromise.'],
      ['"Could you ___ on the price?"', ['come down', 'go down', 'fall', 'lower down'], 0, 'come down on the price.'],
      ['To ask for time:', ['Decide now!', 'We need some time to consider this.', 'Never mind.', 'Forget it.'], 1, 'Buying time politely.'],
    ],
    s: [
      ['We’d be happy to extend the payment terms.', true, null, 'Correct.'],
      ['If you sign today, we give you a discount.', false, 'If you sign today, we’ll give you a discount.', 'Result clause: will.'],
      ['Let me get back to you on that.', true, null, 'Correct.'],
      ['That is not acceptable for us; can we discuss it?', true, null, 'Correct.'],
      ['We are agree with your proposal.', false, 'We agree with your proposal.', 'Agree is a verb, no "are".'],
      ['Would you be open to a longer contract?', true, null, 'Correct.'],
    ],
  },
}
