export default {
  'Present Tenses Review': {
    q: [
      ['Water ___ at 100 degrees.', ['is boiling', 'boils', 'has boiled', 'boil'], 1, 'General fact: present simple.'],
      ['I ___ to the gym more often these days.', ['go', 'am going', 'have gone', 'goes'], 1, 'Temporary trend: present continuous.'],
      ['She ___ three emails so far this morning.', ['writes', 'is writing', 'has written', 'wrote'], 2, 'so far → present perfect.'],
      ['He ___ always ___ my pens! It’s annoying.', ['— / takes', 'is / taking', 'has / taken', 'was / taking'], 1, 'always + continuous = annoying habit.'],
      ['The train ___ at 9:15 every morning.', ['is leaving', 'leaves', 'has left', 'leave'], 1, 'Timetable: present simple.'],
      ['I ___ this book for two weeks.', ['read', 'am reading', 'have been reading', 'reads'], 2, 'Duration: present perfect continuous.'],
      ['What ___ you ___ about?', ['do / think', 'are / thinking', 'have / thought', 'did / think'], 1, 'Think = mental activity now.'],
      ['I ___ this laptop belongs to Sara.', ['am thinking', 'think', 'have thought', 'am thinking that'], 1, 'Think = opinion: simple.'],
    ],
    s: [
      ['I am understanding the problem now.', false, 'I understand the problem now.', 'State verb.'],
      ['She has been working here since March.', true, null, 'Correct.'],
      ['He works in the marketing department.', true, null, 'Correct.'],
      ['They have visit Bogotá twice.', false, 'They have visited Bogotá twice.', 'Participle: visited.'],
      ['My phone is always dying at the worst moment!', true, null, 'always + continuous (complaint).'],
      ['Look! It snows!', false, 'Look! It’s snowing!', 'Now: continuous.'],
    ],
  },
  'Past Tenses Review': {
    q: [
      ['I ___ when the phone rang.', ['cooked', 'was cooking', 'had cooked', 'have cooked'], 1, 'Interrupted action.'],
      ['By the time we arrived, they ___.', ['left', 'were leaving', 'had left', 'have left'], 2, 'Earlier past.'],
      ['She ___ in Peru for two years before moving here.', ['lived', 'had lived', 'was living', 'Both A and B'], 3, 'Both acceptable.'],
      ['We ___ for hours before the bus came.', ['waited', 'had been waiting', 'were waiting', 'wait'], 1, 'Duration before past event.'],
      ['He ___ his leg while he ___ football.', ['broke / was playing', 'was breaking / played', 'had broken / played', 'broke / played'], 0, 'Event during background.'],
      ['I ___ never ___ such a beautiful place.', ['did / see', 'had / seen', 'have / saw', 'was / seeing'], 1, 'had never seen.'],
      ['"Used to" describes:', ['single past events', 'past habits or states', 'future plans', 'present routines'], 1, 'Past habits.'],
      ['When I was a child, I ___ climb trees.', ['would', 'was', 'had', 'am'], 0, 'would = repeated past action.'],
    ],
    s: [
      ['I was working there for five years.', false, 'I worked there for five years.', 'Completed period: past simple.'],
      ['She had already eaten when I arrived.', true, null, 'Correct.'],
      ['We were walking home when it started to rain.', true, null, 'Correct.'],
      ['He use to live in Cali.', false, 'He used to live in Cali.', 'used to.'],
      ['They had been arguing for an hour before I came.', true, null, 'Correct.'],
      ['I didn’t went to the party.', false, 'I didn’t go to the party.', 'Base after didn’t.'],
    ],
  },
  'Future Forms Review': {
    q: [
      ['The bus ___ at 7:30.', ['is leaving', 'leaves', 'will leave', 'is going to leave'], 1, 'Timetable.'],
      ['I ___ dinner with Ana tonight; it’s arranged.', ['will have', 'am having', 'have', 'would have'], 1, 'Arrangement: present continuous.'],
      ['Look at those clouds! It ___ rain.', ['will', 'is going to', 'is', 'shall'], 1, 'Prediction with evidence.'],
      ['"I’ll help you." This is:', ['a plan', 'a spontaneous offer', 'a timetable', 'an arrangement'], 1, 'Spontaneous decision.'],
      ['By 2040, most cars ___ electric.', ['are', 'will be', 'are being', 'were'], 1, 'Prediction.'],
      ['I ___ about to leave when you called.', ['am', 'was', 'will be', 'have been'], 1, 'be about to (past).'],
      ['She ___ to start her own business.', ['plans', 'will plan', 'is plan', 'plan'], 0, 'plan to + verb.'],
      ['We ___ a party next Saturday. Want to come?', ['will have', 'are having', 'have', 'had'], 1, 'Arrangement.'],
    ],
    s: [
      ['I will meet my dentist tomorrow at 3; it’s booked.', false, 'I’m meeting my dentist tomorrow at 3; it’s booked.', 'Arrangement: continuous.'],
      ['The flight departs at 6 a.m.', true, null, 'Correct.'],
      ['I think it will be a great year.', true, null, 'Correct.'],
      ['We are going to launching the app in May.', false, 'We are going to launch the app in May.', 'going to + base.'],
      ['She is about to give a presentation.', true, null, 'Correct.'],
      ['Don’t worry, I help you.', false, 'Don’t worry, I’ll help you.', 'Offer: will.'],
    ],
  },
  'Conditionals Review': {
    q: [
      ['If you heat ice, it ___.', ['melts', 'will melt', 'would melt', 'melted'], 0, 'Zero conditional.'],
      ['If it rains tomorrow, we ___ the picnic.', ['cancel', 'will cancel', 'would cancel', 'cancelled'], 1, 'First conditional.'],
      ['If I ___ you, I’d apologise.', ['am', 'was', 'were', 'be'], 2, 'Second conditional.'],
      ['If she had listened, she ___ the mistake.', ['wouldn’t make', 'wouldn’t have made', 'didn’t make', 'won’t make'], 1, 'Third conditional.'],
      ['___ you need help, call me.', ['Should', 'Would', 'Will', 'Had'], 0, 'Should you = if you.'],
      ['Unless you hurry, you ___ the train.', ['miss', 'will miss', 'would miss', 'missed'], 1, 'unless = if not.'],
      ['I’ll lend you money ___ you pay me back.', ['unless', 'as long as', 'in case', 'even if'], 1, 'Condition: as long as.'],
      ['Take an umbrella ___ it rains.', ['unless', 'if', 'in case', 'as long as'], 2, 'Precaution: in case.'],
    ],
    s: [
      ['If I will see him, I will tell him.', false, 'If I see him, I will tell him.', 'No will in the if-clause.'],
      ['If you mix red and blue, you get purple.', true, null, 'Correct.'],
      ['I would travel more if I had time.', true, null, 'Correct.'],
      ['Unless you don’t study, you will fail.', false, 'Unless you study, you will fail.', 'Unless is already negative.'],
      ['If they had known, they would have helped.', true, null, 'Correct.'],
      ['I’ll go provided that you come too.', true, null, 'Correct.'],
    ],
  },
  'Modals Review': {
    q: [
      ['You ___ wear a seatbelt. It’s the law.', ['should', 'must', 'might', 'could'], 1, 'Obligation.'],
      ['You ___ come if you don’t want to.', ['mustn’t', 'don’t have to', 'can’t', 'shouldn’t'], 1, 'Not necessary.'],
      ['___ I borrow your pen?', ['Must', 'Should', 'May', 'Would'], 2, 'Permission: may/can/could.'],
      ['She ___ swim when she was three.', ['can', 'could', 'might', 'must'], 1, 'Past ability.'],
      ['You ___ smoke here. It’s forbidden.', ['don’t have to', 'mustn’t', 'shouldn’t', 'might not'], 1, 'Prohibition.'],
      ['We ___ hurry; we have plenty of time.', ['mustn’t', 'needn’t', 'can’t', 'shouldn’t'], 1, 'Not necessary.'],
      ['He ___ be at the office; his car is outside.', ['must', 'can’t', 'might not', 'should'], 0, 'Deduction.'],
      ['___ you mind opening the window?', ['Could', 'Would', 'May', 'Must'], 1, 'Would you mind.'],
    ],
    s: [
      ['You must to submit the form by Friday.', false, 'You must submit the form by Friday.', 'No "to" after must.'],
      ['She can speak three languages.', true, null, 'Correct.'],
      ['We don’t have to work tomorrow.', true, null, 'Correct.'],
      ['He should to see a doctor.', false, 'He should see a doctor.', 'No "to".'],
      ['May I leave early today?', true, null, 'Correct.'],
      ['You mustn’t forget your passport.', true, null, 'Correct.'],
    ],
  },
  'Passive with Reporting Verbs': {
    q: [
      ['It ___ that the CEO will resign.', ['says', 'is said', 'said', 'is saying'], 1, 'It is said that.'],
      ['The CEO ___ to be resigning.', ['says', 'is said', 'said', 'has said'], 1, 'Subject + is said + to.'],
      ['He ___ to have stolen the money.', ['believes', 'is believed', 'believed', 'is believing'], 1, 'is believed to have + participle.'],
      ['The company ___ to be worth $1 billion.', ['thinks', 'is thought', 'thought', 'is thinking'], 1, 'is thought to be.'],
      ['It ___ that the project failed.', ['reports', 'is reported', 'reporting', 'reported'], 1, 'It is reported that.'],
      ['"They are expected to win" means:', ['They expect to win', 'People expect them to win', 'They won', 'They must win'], 1, 'Others expect.'],
      ['She ___ to be the best candidate.', ['considers', 'is considered', 'considered', 'is considering'], 1, 'is considered to be.'],
      ['It ___ that prices will rise.', ['is expected', 'expects', 'expecting', 'expected'], 0, 'It is expected that.'],
    ],
    s: [
      ['It is said that he is very rich.', true, null, 'Correct.'],
      ['He is said to being very rich.', false, 'He is said to be very rich.', 'to be.'],
      ['The company is believed to have lost millions.', true, null, 'Correct.'],
      ['It is thinking that the storm will hit tonight.', false, 'It is thought that the storm will hit tonight.', 'is thought.'],
      ['She is known to be a tough negotiator.', true, null, 'Correct.'],
      ['They are reported to has left the country.', false, 'They are reported to have left the country.', 'to have + participle.'],
    ],
  },
  'Reported Speech: Advanced': {
    q: [
      ['"I’ll call you tomorrow." → He said he ___ me ___.', ['will call / tomorrow', 'would call / the next day', 'called / tomorrow', 'would call / yesterday'], 1, 'will → would; tomorrow → the next day.'],
      ['"I’m working here." → She said she ___ there.', ['is working', 'was working', 'worked', 'had worked'], 1, 'Tense back; here → there.'],
      ['"I must go." → He said he ___ go.', ['must', 'had to', 'should', 'would'], 1, 'must → had to (obligation).'],
      ['"Water boils at 100 °C." → The teacher said water ___.', ['boiled', 'boils', 'had boiled', 'would boil'], 1, 'General truths keep the present.'],
      ['"Let’s go out." → He suggested ___ out.', ['to go', 'going', 'go', 'that go'], 1, 'suggest + -ing.'],
      ['"I’m sorry I’m late." → She ___ for being late.', ['said', 'apologised', 'told', 'refused'], 1, 'Reporting verb: apologise for.'],
      ['"Don’t forget!" → He ___ me not to forget.', ['reminded', 'said', 'suggested', 'promised'], 0, 'remind + object + to.'],
      ['"I didn’t do it!" → He ___ doing it.', ['denied', 'refused', 'admitted', 'agreed'], 0, 'deny + -ing.'],
    ],
    s: [
      ['She said me she was busy.', false, 'She told me she was busy.', 'tell + object.'],
      ['He promised to send the file.', true, null, 'Correct.'],
      ['They admitted making a mistake.', true, null, 'Correct.'],
      ['She suggested me to leave early.', false, 'She suggested that I leave early.', 'suggest + that / -ing.'],
      ['He denied that he had seen the email.', true, null, 'Correct.'],
      ['The manager insisted to pay for lunch.', false, 'The manager insisted on paying for lunch.', 'insist on + -ing.'],
    ],
  },
  'Participle Clauses': {
    q: [
      ['___ the news, she started to cry.', ['Hear', 'Hearing', 'Heard', 'To hear'], 1, 'Present participle: at the same time / because.'],
      ['___ in 1990, the company is now a leader.', ['Founding', 'Founded', 'To found', 'Found'], 1, 'Passive meaning: past participle.'],
      ['___ finished the report, he went home.', ['Have', 'Having', 'Had', 'To have'], 1, 'Having + participle = after.'],
      ['The man ___ by the door is my boss.', ['stands', 'standing', 'stood', 'to stand'], 1, 'Reduced relative: standing.'],
      ['The documents ___ yesterday are on your desk.', ['signing', 'signed', 'sign', 'to sign'], 1, 'Passive: signed.'],
      ['___ tired, I went to bed early.', ['Feel', 'Feeling', 'Felt', 'To feel'], 1, 'Feeling tired.'],
      ['Not ___ what to do, she asked for help.', ['know', 'knowing', 'known', 'to know'], 1, 'Not knowing.'],
      ['Participle clauses are common in:', ['casual chat', 'formal writing', 'texting', 'songs'], 1, 'Formal / written English.'],
    ],
    s: [
      ['Walking down the street, I saw an old friend.', true, null, 'Correct.'],
      ['Having lost the match, the team was sad.', true, null, 'Correct.'],
      ['Written in 1605, the novel is still popular.', true, null, 'Correct.'],
      ['Being tired, the meeting was postponed.', false, 'Being tired, we postponed the meeting.', 'Subject must match.'],
      ['The report attaching to this email is final.', false, 'The report attached to this email is final.', 'Passive: attached.'],
      ['Knowing the answer, he raised his hand.', true, null, 'Correct.'],
    ],
  },
  'Cleft Sentences (What / It was…)': {
    q: [
      ['___ I need is a holiday.', ['That', 'What', 'It', 'Which'], 1, 'What-cleft.'],
      ['It was Marta ___ solved the problem.', ['which', 'who', 'what', 'she'], 1, 'It was X who.'],
      ['___ annoys me is his attitude.', ['It', 'That', 'What', 'Which'], 2, 'What annoys me.'],
      ['It was in 2015 ___ we met.', ['who', 'when', 'that', 'Both when and that'], 3, 'Both possible.'],
      ['Cleft sentences are used to:', ['ask questions', 'emphasise information', 'report speech', 'give orders'], 1, 'Emphasis.'],
      ['___ she did was call the police.', ['What', 'That', 'It', 'Which'], 0, 'What she did was.'],
      ['It ___ the manager who made the decision.', ['is', 'was', 'Both possible', 'were'], 2, 'Depends on time.'],
      ['The reason ___ I left was the salary.', ['what', 'why', 'that', 'Both why and that'], 3, 'why/that.'],
    ],
    s: [
      ['What I want is a coffee.', true, null, 'Correct.'],
      ['It was John which broke the window.', false, 'It was John who broke the window.', 'People: who.'],
      ['The thing what I hate is traffic.', false, 'The thing I hate is traffic.', 'No "what" after "the thing".'],
      ['It was the price that surprised me.', true, null, 'Correct.'],
      ['What happened was that the server crashed.', true, null, 'Correct.'],
      ['It is here where I was born.', false, 'It is here that I was born.', 'It is … that.'],
    ],
  },
  'Inversion for Emphasis': {
    q: [
      ['Never ___ such a beautiful view.', ['I have seen', 'have I seen', 'I saw', 'did I saw'], 1, 'Negative adverb + inversion.'],
      ['Not only ___ late, but he also forgot the files.', ['he was', 'was he', 'he is', 'did he'], 1, 'Not only + auxiliary + subject.'],
      ['Rarely ___ so much rain.', ['we see', 'do we see', 'we do see', 'see we'], 1, 'Rarely do we.'],
      ['___ had I arrived when the phone rang.', ['Hardly', 'Only', 'Just', 'Never'], 0, 'Hardly had I… when.'],
      ['Under no circumstances ___ leave this room.', ['you should', 'should you', 'you must', 'must to'], 1, 'Inversion after negative phrase.'],
      ['Only then ___ the truth.', ['I understood', 'did I understand', 'I did understand', 'understood I'], 1, 'Only then + inversion.'],
      ['"Little did he know" means:', ['He knew little', 'He didn’t know at all', 'He knew a bit', 'He learned little'], 1, 'He had no idea.'],
      ['Inversion is typical of:', ['informal speech', 'formal or literary style', 'text messages', 'children’s speech'], 1, 'Formal/literary.'],
    ],
    s: [
      ['Never have I been so embarrassed.', true, null, 'Correct.'],
      ['Not only she sings, but she also dances.', false, 'Not only does she sing, but she also dances.', 'Inversion after not only.'],
      ['Seldom do we get such an opportunity.', true, null, 'Correct.'],
      ['No sooner had we sat down than the show began.', true, null, 'Correct.'],
      ['Only after the meeting I realised my mistake.', false, 'Only after the meeting did I realise my mistake.', 'Only after + inversion.'],
      ['Under no circumstances you can open this door.', false, 'Under no circumstances can you open this door.', 'Inversion.'],
    ],
  },
  'Quantifiers: Advanced': {
    q: [
      ['___ of the students passed the exam.', ['Most', 'The most', 'Most of', 'Almost'], 0, 'Most of the students.'],
      ['I have ___ friends in Bogotá.', ['a few', 'a little', 'few of', 'little'], 0, 'Countable: a few.'],
      ['___ team member has a laptop.', ['Every', 'All', 'Both', 'Most'], 0, 'Every + singular.'],
      ['___ of them wanted to leave early.', ['Every', 'Neither', 'Each one', 'Both A and C'], 1, 'Neither of them.'],
      ['There is ___ milk left; buy some.', ['little', 'a little', 'few', 'a few'], 0, 'little = almost none.'],
      ['___ my colleagues speak English.', ['All', 'All of', 'Both are correct', 'Every'], 2, 'All / All of my.'],
      ['I don’t like ___ of those two options.', ['neither', 'either', 'none', 'both'], 1, 'not … either.'],
      ['___ people know about this.', ['Few', 'A few', 'Little', 'A little'], 0, 'Few = not many (negative).'],
    ],
    s: [
      ['Every students must register online.', false, 'Every student must register online.', 'Every + singular.'],
      ['Most of the time I work from home.', true, null, 'Correct.'],
      ['Neither of the answers is correct.', true, null, 'Correct.'],
      ['I have very little friends here.', false, 'I have very few friends here.', 'Countable: few.'],
      ['Each of the reports has been reviewed.', true, null, 'Correct.'],
      ['Both of the twins are tall.', true, null, 'Correct.'],
    ],
  },
  'Comparison: Advanced Structures': {
    q: [
      ['The ___ you practise, the ___ you get.', ['more / better', 'most / best', 'more / good', 'much / better'], 0, 'The more…, the better.'],
      ['This is ___ the same as the original.', ['exact', 'exactly', 'more', 'as'], 1, 'exactly the same as.'],
      ['Her presentation was ___ better than mine.', ['very', 'far', 'much more', 'more'], 1, 'far better = much better.'],
      ['It’s getting ___ and ___ expensive to live here.', ['more / more', 'most / most', 'much / much', 'more / most'], 0, 'more and more.'],
      ['This phone is ___ as good as that one.', ['not', 'nothing', 'nearly', 'Both A and C'], 3, 'not / nearly as good as.'],
      ['He is ___ intelligent as his brother.', ['every bit as', 'as much', 'more', 'so'], 0, 'every bit as = equally.'],
      ['The sooner, the ___.', ['best', 'better', 'good', 'well'], 1, 'The sooner, the better.'],
      ['Sales were ___ higher than last year.', ['slight', 'slightly', 'less', 'the most'], 1, 'Adverb: slightly.'],
    ],
    s: [
      ['The more I study, the more I learn.', true, null, 'Correct.'],
      ['This is by far the best restaurant in town.', true, null, 'Correct.'],
      ['My car is much more faster than yours.', false, 'My car is much faster than yours.', 'Double comparative.'],
      ['Life is getting more and more complicated.', true, null, 'Correct.'],
      ['She is twice as older than me.', false, 'She is twice as old as me.', 'twice as + adjective + as.'],
      ['It’s not nearly as difficult as I thought.', true, null, 'Correct.'],
    ],
  },
  'Adjective Order & Compound Adjectives': {
    q: [
      ['a ___ table', ['wooden big round', 'big round wooden', 'round big wooden', 'wooden round big'], 1, 'Size → shape → material.'],
      ['a ___ jacket', ['leather black old', 'old black leather', 'black old leather', 'old leather black'], 1, 'Age → colour → material.'],
      ['a ___ meeting', ['two-hours', 'two-hour', 'two hours', 'hours-two'], 1, 'Compound adjective: singular.'],
      ['She is a ___ woman.', ['well-known', 'known-well', 'well known-', 'knowing well'], 0, 'well-known.'],
      ['a ___ building', ['ten-storey', 'ten-storeys', 'ten storeys', 'storeys-ten'], 0, 'Hyphenated, singular.'],
      ['Which order is correct?', ['opinion → size → colour', 'colour → size → opinion', 'size → opinion → colour', 'material → opinion → size'], 0, 'Opinion first.'],
      ['a ___ employee', ['hard-working', 'working-hard', 'hardly-working', 'hard work'], 0, 'hard-working.'],
      ['a ___ decision', ['last-minute', 'last minute-', 'minute-last', 'lastly minute'], 0, 'last-minute.'],
    ],
    s: [
      ['She bought a beautiful small Italian car.', true, null, 'Opinion → size → origin.'],
      ['We had a three-days conference.', false, 'We had a three-day conference.', 'Singular in compound adjectives.'],
      ['He is a well-paid consultant.', true, null, 'Correct.'],
      ['It’s a red big house.', false, 'It’s a big red house.', 'Size before colour.'],
      ['The 25-year-old manager was promoted.', true, null, 'Correct.'],
      ['They live in a modern lovely flat.', false, 'They live in a lovely modern flat.', 'Opinion before age.'],
    ],
  },
  'Prepositions after Adjectives & Verbs': {
    q: [
      ['I’m interested ___ your proposal.', ['on', 'in', 'about', 'for'], 1, 'interested in.'],
      ['She is responsible ___ the budget.', ['of', 'for', 'about', 'with'], 1, 'responsible for.'],
      ['We depend ___ our suppliers.', ['of', 'on', 'from', 'in'], 1, 'depend on.'],
      ['He apologised ___ being late.', ['for', 'about', 'of', 'by'], 0, 'apologise for.'],
      ['I’m worried ___ the exam.', ['for', 'about', 'of', 'on'], 1, 'worried about.'],
      ['It depends ___ the weather.', ['of', 'on', 'in', 'from'], 1, 'depend on.'],
      ['She is good ___ negotiating.', ['in', 'at', 'on', 'for'], 1, 'good at.'],
      ['They insisted ___ paying.', ['in', 'on', 'for', 'to'], 1, 'insist on.'],
    ],
    s: [
      ['I’m married with a doctor.', false, 'I’m married to a doctor.', 'married to.'],
      ['She is afraid of spiders.', true, null, 'Correct.'],
      ['We arrived to the airport late.', false, 'We arrived at the airport late.', 'arrive at/in.'],
      ['He is keen on football.', true, null, 'Correct.'],
      ['I agree with you.', true, null, 'Correct.'],
      ['It depends of the price.', false, 'It depends on the price.', 'depend on.'],
    ],
  },
  'Phrasal Verbs III (Business)': {
    q: [
      ['We need to ___ costs this quarter.', ['cut down on', 'cut off', 'cut in', 'cut up'], 0, 'cut down on = reduce.'],
      ['The company was ___ by a competitor.', ['taken over', 'taken off', 'taken up', 'taken in'], 0, 'take over = acquire.'],
      ['Can you ___ this proposal and give feedback?', ['look through', 'look after', 'look up to', 'look out'], 0, 'look through = review.'],
      ['We ___ a new marketing plan.', ['drew up', 'drew out', 'drew in', 'drew off'], 0, 'draw up = prepare a document.'],
      ['The talks ___ because of the price.', ['fell through', 'fell out', 'fell off', 'fell down'], 0, 'fall through = fail.'],
      ['Let’s ___ the main points.', ['sum up', 'sum out', 'sum in', 'sum on'], 0, 'sum up = summarise.'],
      ['She ___ a new business last year.', ['set up', 'set off', 'set out', 'set in'], 0, 'set up = establish.'],
      ['We must ___ the deadline.', ['stick to', 'stick out', 'stick up', 'stick in'], 0, 'stick to = keep to.'],
    ],
    s: [
      ['We need to follow up on the client’s request.', true, null, 'Correct.'],
      ['The manager called off the meeting.', true, null, 'call off = cancel.'],
      ['They set up a new branch in Lima.', true, null, 'Correct.'],
      ['Let’s go through over the numbers.', false, 'Let’s go through the numbers.', 'One phrasal verb.'],
      ['We carried on the project despite problems.', false, 'We carried on with the project despite problems.', 'carry on WITH + noun.'],
      ['Please fill the form out in.', false, 'Please fill out the form.', 'fill out / fill in.'],
    ],
  },
  'Collocations: Make / Do / Take / Have': {
    q: [
      ['I need to ___ a decision.', ['do', 'make', 'take', 'have'], 1, 'make a decision.'],
      ['Did you ___ your homework?', ['make', 'do', 'take', 'have'], 1, 'do homework.'],
      ['Let’s ___ a break.', ['make', 'do', 'take', 'give'], 2, 'take a break (or have).'],
      ['She ___ a great presentation.', ['did', 'made', 'gave', 'Both B and C'], 3, 'make/give a presentation.'],
      ['We ___ a lot of progress this month.', ['did', 'made', 'took', 'had'], 1, 'make progress.'],
      ['He ___ business with Chinese companies.', ['makes', 'does', 'takes', 'has'], 1, 'do business.'],
      ['I ___ a shower every morning.', ['make', 'do', 'take', 'Both C and have'], 3, 'take/have a shower.'],
      ['Please ___ a note of this.', ['do', 'make', 'have', 'give'], 1, 'make a note.'],
    ],
    s: [
      ['She made a mistake in the report.', true, null, 'Correct.'],
      ['I have to make my homework.', false, 'I have to do my homework.', 'do homework.'],
      ['We did a lot of money last year.', false, 'We made a lot of money last year.', 'make money.'],
      ['Can I make a suggestion?', true, null, 'Correct.'],
      ['He took a photo of the team.', true, null, 'Correct.'],
      ['Let’s make a party!', false, 'Let’s have a party!', 'have a party.'],
    ],
  },
  'Idioms at Work': {
    q: [
      ['"Let’s touch base next week" means:', ['fight', 'make contact', 'play baseball', 'finish'], 1, 'Touch base = get in touch.'],
      ['"Think outside the box" means:', ['be creative', 'leave the room', 'follow rules', 'think slowly'], 0, 'Creative thinking.'],
      ['"We’re on the same page" means:', ['we read the same book', 'we agree', 'we are late', 'we are bored'], 1, 'Agreement.'],
      ['"It’s a win-win situation" means:', ['one team wins', 'everyone benefits', 'nobody wins', 'a sports game'], 1, 'Both sides benefit.'],
      ['"Cut corners" means:', ['do something cheaply/badly', 'turn left', 'work harder', 'measure'], 0, 'Skip steps to save.'],
      ['"Back to the drawing board" means:', ['start again', 'draw a picture', 'give up', 'go home'], 0, 'Start over.'],
      ['"Ballpark figure" means:', ['exact number', 'rough estimate', 'sports score', 'salary'], 1, 'Approximate number.'],
      ['"Get the ball rolling" means:', ['start something', 'play sports', 'stop', 'delay'], 0, 'Start.'],
    ],
    s: [
      ['Let’s call it a day and go home.', true, null, 'call it a day = stop working.'],
      ['We are in the same page about the budget.', false, 'We are on the same page about the budget.', 'on the same page.'],
      ['He learned the ropes very quickly.', true, null, 'learn the ropes = learn the job.'],
      ['Give me a ballpark number.', true, null, 'Correct.'],
      ['Let’s think out of the box.', true, null, 'Accepted variant.'],
      ['She is the person going-to for tech problems.', false, 'She is the go-to person for tech problems.', 'go-to person.'],
    ],
  },
  'Formal vs Informal Register': {
    q: [
      ['Formal version of "Sorry for the delay":', ['My bad.', 'Please accept our apologies for the delay.', 'Oops.', 'Sorry!!!'], 1, 'Formal apology.'],
      ['Informal version of "I would appreciate your reply":', ['Kindly respond.', 'Let me know!', 'I await your response.', 'Please advise.'], 1, 'Casual.'],
      ['Which is formal?', ['Thanks a lot!', 'Cheers!', 'Thank you for your assistance.', 'Ta!'], 2, 'Formal thanks.'],
      ['Formal: "I am writing to ___ about the invoice."', ['ask', 'enquire', 'tell', 'talk'], 1, 'enquire = formal ask.'],
      ['Contractions (I’m, don’t) are typical of:', ['formal writing', 'informal writing', 'legal contracts', 'academic essays'], 1, 'Informal.'],
      ['Formal: "We ___ inform you that…"', ['regret to', 'are sad to', 'hate to', 'don’t like to'], 0, 'We regret to inform you.'],
      ['Informal closing:', ['Yours sincerely', 'Best regards', 'Cheers', 'Yours faithfully'], 2, 'Cheers.'],
      ['Formal: "Get in touch" →', ['Contact us', 'Hit us up', 'Drop us a line', 'Ping us'], 0, 'Contact us.'],
    ],
    s: [
      ['Dear Sir/Madam, I am writing to enquire about your services.', true, null, 'Formal.'],
      ['Hey Mr. Johnson, gimme the report ASAP.', false, 'Dear Mr. Johnson, could you please send the report as soon as possible?', 'Too informal for a boss.'],
      ['Should you require further information, please do not hesitate to contact me.', true, null, 'Formal.'],
      ['Yours faithfully, Ana', true, null, 'Formal closing (unknown name).'],
      ['I wanna apply for the job.', false, 'I would like to apply for the position.', 'Formal register.'],
      ['We look forward to hearing from you.', true, null, 'Correct.'],
    ],
  },
  'Emphasis: Do / Really / Own': {
    q: [
      ['I ___ like your idea!', ['do', 'am', 'does', 'did'], 0, 'Emphatic do.'],
      ['She ___ call you; I saw her.', ['does', 'did', 'do', 'is'], 1, 'Emphatic did (past).'],
      ['I cooked this ___.', ['by myself', 'myself', 'Both are correct', 'on my own self'], 2, 'Both fine.'],
      ['It’s my ___ business!', ['self', 'own', 'proper', 'only'], 1, 'my own.'],
      ['This is ___ what I needed.', ['exactly', 'exact', 'very', 'do'], 0, 'exactly.'],
      ['He is ___ very talented.', ['do', 'indeed', 'own', 'does'], 1, 'indeed.'],
      ['I ___ told you so!', ['do', 'did', 'does', 'am'], 1, 'did tell (past emphasis).'],
      ['She did it ___ any help.', ['with', 'without', 'own', 'herself'], 1, 'without any help.'],
    ],
    s: [
      ['I do hope you can come.', true, null, 'Emphatic do.'],
      ['He does works hard.', false, 'He does work hard.', 'Base verb after does.'],
      ['We built the website ourselves.', true, null, 'Correct.'],
      ['It’s her own decision.', true, null, 'Correct.'],
      ['I did went to the meeting.', false, 'I did go to the meeting.', 'did + base.'],
      ['That was the very thing I wanted.', true, null, 'Correct.'],
    ],
  },
  'Discourse Markers in Speech': {
    q: [
      ['"___, how was your trip?" (changing topic)', ['Anyway', 'Because', 'Although', 'Then'], 0, 'Anyway = change topic.'],
      ['"___, I think we should wait." (giving an opinion)', ['Actually', 'Whereas', 'Unless', 'However much'], 0, 'Actually / To be honest.'],
      ['"___, it was a great event." (summarising)', ['All in all', 'Anyway', 'By the way', 'Mind you'], 0, 'All in all.'],
      ['"___, did you see Ana?" (adding side topic)', ['By the way', 'As a result', 'In contrast', 'Therefore'], 0, 'By the way.'],
      ['"It’s expensive. ___, it’s good quality."', ['Mind you', 'Because', 'So', 'Hence'], 0, 'Mind you = but consider.'],
      ['"___, I disagree." (to soften)', ['To be honest', 'Absolutely', 'Exactly', 'Right'], 0, 'To be honest.'],
      ['"___ I know, the meeting is at 3."', ['As far as', 'As long as', 'As soon as', 'As much as'], 0, 'As far as I know.'],
      ['"I mean" is used to:', ['clarify', 'contrast', 'conclude', 'order'], 0, 'Clarify.'],
    ],
    s: [
      ['Anyway, let’s get back to work.', true, null, 'Correct.'],
      ['By the way, I saw your brother yesterday.', true, null, 'Correct.'],
      ['As far as I concerned, the plan is fine.', false, 'As far as I’m concerned, the plan is fine.', 'I’m concerned.'],
      ['Actually, I’ve already finished.', true, null, 'Correct.'],
      ['At the end, we decided to go.', false, 'In the end, we decided to go.', 'In the end = finally.'],
      ['To be honest, I didn’t like the film.', true, null, 'Correct.'],
    ],
  },
  'Pronunciation & Word Stress': {
    q: [
      ['Where is the stress in "photograph"?', ['PHO-to-graph', 'pho-TO-graph', 'pho-to-GRAPH', 'no stress'], 0, 'First syllable.'],
      ['Where is the stress in "photography"?', ['PHO-tog-raphy', 'pho-TOG-raphy', 'photo-GRA-phy', 'photogra-PHY'], 1, 'Second syllable.'],
      ['"Record" (noun) is stressed on the:', ['first syllable', 'second syllable', 'both', 'neither'], 0, 'RE-cord (noun).'],
      ['"Record" (verb) is stressed on the:', ['first syllable', 'second syllable', 'both', 'neither'], 1, 're-CORD (verb).'],
      ['Which word has a silent letter?', ['cat', 'knife', 'dog', 'sun'], 1, 'Silent k.'],
      ['Which "-ed" is pronounced /ɪd/?', ['worked', 'played', 'wanted', 'stopped'], 2, 'After t/d: /ɪd/.'],
      ['"Comfortable" has how many syllables (usual)?', ['2', '3', '4', '5'], 1, 'COMF-ter-ble.'],
      ['Which pair rhymes?', ['though / through', 'great / meat', 'blue / through', 'read (past) / bead'], 2, 'blue / through.'],
    ],
    s: [
      ['"Present" (gift) is stressed on the first syllable.', true, null, 'PRE-sent.'],
      ['"Present" (give) is stressed on the first syllable.', false, '"Present" (give) is stressed on the second syllable.', 'pre-SENT.'],
      ['The "b" in "climb" is silent.', true, null, 'Correct.'],
      ['"Walked" is pronounced with two syllables.', false, '"Walked" is pronounced with one syllable.', '/wɔːkt/.'],
      ['"Hotel" is stressed on the second syllable.', true, null, 'ho-TEL.'],
      ['"Vegetable" has four spoken syllables.', false, '"Vegetable" usually has three spoken syllables.', 'VEG-ta-ble.'],
    ],
  },
  'Describing Trends & Data': {
    q: [
      ['Sales ___ sharply in Q3.', ['rose', 'raised', 'risen', 'rise up'], 0, 'rise – rose (intransitive).'],
      ['Profits ___ by 10% last year.', ['fell', 'felt', 'fallen', 'falls'], 0, 'fall – fell.'],
      ['The number of users ___ stable.', ['remained', 'stayed still', 'kept on', 'holds'], 0, 'remained stable.'],
      ['Costs ___ from $5m to $8m.', ['increased', 'raised', 'grew up', 'climbed up'], 0, 'increased from … to.'],
      ['There was a ___ decrease in complaints.', ['slight', 'slightly', 'slow down', 'few'], 0, 'Adjective + noun.'],
      ['Revenue ___ dramatically.', ['dropped', 'was dropping down', 'has drop', 'dropping'], 0, 'dropped.'],
      ['Sales ___ at 200 units in May.', ['peaked', 'topped up', 'highest', 'summit'], 0, 'peaked at.'],
      ['"Fluctuate" means:', ['stay the same', 'go up and down', 'fall', 'rise'], 1, 'Up and down.'],
    ],
    s: [
      ['Prices rose by 5% in March.', true, null, 'Correct.'],
      ['The company raised its prices last month.', true, null, 'raise + object.'],
      ['Unemployment has raised this year.', false, 'Unemployment has risen this year.', 'Intransitive: rise.'],
      ['There was a sharp fall in demand.', true, null, 'Correct.'],
      ['Sales decreased dramatic in 2020.', false, 'Sales decreased dramatically in 2020.', 'Adverb.'],
      ['The figures levelled off in the summer.', true, null, 'Correct.'],
    ],
  },
  'Telephone & Video Call English': {
    q: [
      ['"Could you ___ on, please?"', ['hold', 'wait', 'stay', 'keep'], 0, 'hold on.'],
      ['"I’m afraid the line is ___."', ['busy', 'full', 'bad', 'Both A and C'], 3, 'busy / bad.'],
      ['"Could you ___ that? I didn’t catch it."', ['repeat', 'say again', 'Both are fine', 'return'], 2, 'Both fine.'],
      ['"You’re ___ up." (video call)', ['breaking', 'cutting', 'stopping', 'shaking'], 0, 'breaking up = poor connection.'],
      ['"I’ll ___ you through to the sales team."', ['put', 'send', 'pass', 'give'], 0, 'put you through.'],
      ['"Can I ___ a message?"', ['leave', 'let', 'drop', 'lay'], 0, 'leave a message.'],
      ['"You’re on ___." (video)', ['mute', 'silent', 'quiet', 'off'], 0, 'on mute.'],
      ['"Let me ___ my screen."', ['share', 'show', 'open', 'send'], 0, 'share my screen.'],
    ],
    s: [
      ['Who’s calling, please?', true, null, 'Correct.'],
      ['I call you back in ten minutes.', false, 'I’ll call you back in ten minutes.', 'Promise: will.'],
      ['Sorry, you’re breaking up. Can you repeat that?', true, null, 'Correct.'],
      ['Can you speak more slowly, please?', true, null, 'Correct.'],
      ['I think you are in mute.', false, 'I think you are on mute.', 'on mute.'],
      ['Thanks for calling. Have a good day.', true, null, 'Correct.'],
    ],
  },
  'Review: Presentations & Reports': {
    q: [
      ['Opening a presentation:', ['So, bye.', 'Good morning everyone. Today I’m going to talk about…', 'Any questions?', 'In conclusion…'], 1, 'Opening line.'],
      ['Moving to the next point:', ['Let’s move on to…', 'That’s all.', 'Thanks for coming.', 'Any questions?'], 0, 'Transition.'],
      ['Referring to a chart:', ['As you can see in this chart…', 'Look, a picture.', 'This is nothing.', 'Later.'], 0, 'Referring to visuals.'],
      ['Ending:', ['Hi everyone.', 'To sum up, …', 'Firstly, …', 'Let me introduce…'], 1, 'Conclusion.'],
      ['Inviting questions:', ['Don’t ask.', 'I’d be happy to answer any questions.', 'Goodbye.', 'Moving on.'], 1, 'Q&A.'],
      ['A report’s first section is usually the:', ['conclusion', 'introduction', 'appendix', 'references'], 1, 'Introduction.'],
      ['"The purpose of this report is ___ the results."', ['present', 'to present', 'presenting', 'presented'], 1, 'to + verb.'],
      ['"Based ___ the findings, we recommend…"', ['in', 'on', 'at', 'of'], 1, 'based on.'],
    ],
    s: [
      ['Let me start by giving you a brief overview.', true, null, 'Correct.'],
      ['Now I would like to turn to the second point.', true, null, 'Correct.'],
      ['This chart show the sales figures for 2024.', false, 'This chart shows the sales figures for 2024.', 'Third person -s.'],
      ['In conclusion, we recommend expanding to Peru.', true, null, 'Correct.'],
      ['Thank you for you attention.', false, 'Thank you for your attention.', 'your.'],
      ['If you have any questions, feel free to ask.', true, null, 'Correct.'],
    ],
  },
}
